-- ==========================================================
-- accounts seed — Стандарт IFRS загвар дансны төлөвлөгөө (хоёр хэлтэй)
-- Нийт: 138 данс. Код: 1 хөрөнгө · 3 өр · 5 өмч · 6 орлого · 7-8 зардал.
-- Хүснэгт хоосон үед л оруулна. Supabase SQL Editor-д ажиллуулна.
-- ==========================================================

DO $$
BEGIN
IF (SELECT COUNT(*) FROM accounts) = 0 THEN

INSERT INTO accounts (id, code, name, name_en, type, parent_id, is_active, note, fs_line, currency, nature, is_temp, temp_percent) VALUES
  (1, '110000', 'Мөнгөн хөрөнгө ба түүнтэй адилтгах', 'Cash & Cash Equivalents', 'asset', NULL, TRUE, NULL, NULL, 'MNT', 'Актив', FALSE, 0),
  (2, '110100', 'Кассын бэлэн мөнгө', 'Petty Cash', 'asset', 1, TRUE, NULL, 'СБТ 1.1.1 Мөнгө, түүнтэй адилтгах хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (3, '110200', 'Харилцах дансны мөнгө', 'Bank Current Account', 'asset', 1, TRUE, NULL, 'СБТ 1.1.1 Мөнгө, түүнтэй адилтгах хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (4, '110300', 'Хадгаламжийн дансны мөнгө', 'Savings Account', 'asset', 1, TRUE, NULL, 'СБТ 1.1.1 Мөнгө, түүнтэй адилтгах хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (5, '110400', 'Гадаад валютын кассын мөнгө', 'Foreign Currency Cash', 'asset', 1, TRUE, NULL, 'СБТ 1.1.1 Мөнгө, түүнтэй адилтгах хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (6, '110500', 'Гадаад валютын харилцах данс', 'Foreign Currency Bank Account', 'asset', 1, TRUE, NULL, 'СБТ 1.1.1 Мөнгө, түүнтэй адилтгах хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (7, '110600', 'Карт болон цахим мөнгө', 'Card & E-money', 'asset', 1, TRUE, NULL, 'СБТ 1.1.1 Мөнгө, түүнтэй адилтгах хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (8, '110700', 'Замд яваа мөнгө', 'Cash in Transit', 'asset', 1, TRUE, NULL, 'СБТ 1.1.1 Мөнгө, түүнтэй адилтгах хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (9, '110900', 'Бусад мөнгөн хөрөнгө', 'Other Cash', 'asset', 1, TRUE, NULL, 'СБТ 1.1.1 Мөнгө, түүнтэй адилтгах хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (10, '120000', 'Богино хугацаат хөрөнгө оруулалт', 'Short-term Investments', 'asset', NULL, TRUE, NULL, NULL, 'MNT', 'Актив', FALSE, 0),
  (11, '120100', 'Хугацаат хадгаламж (1 жил хүртэл)', 'Term Deposit (< 1yr)', 'asset', 10, TRUE, NULL, 'СБТ 1.1.5 Бусад санхүүгийн хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (12, '120200', 'Үнэт цаас (борлуулахад бэлэн)', 'Marketable Securities', 'asset', 10, TRUE, NULL, 'СБТ 1.1.5 Бусад санхүүгийн хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (13, '120900', 'Бусад богино хуг. хөрөнгө оруулалт', 'Other Short-term Investments', 'asset', 10, TRUE, NULL, 'СБТ 1.1.5 Бусад санхүүгийн хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (14, '130000', 'Дансны болон бусад авлага', 'Trade & Other Receivables', 'asset', NULL, TRUE, NULL, NULL, 'MNT', 'Актив', FALSE, 0),
  (15, '130100', 'Худалдан авагч, захиалагчийн авлага', 'Trade Receivables', 'asset', 14, TRUE, NULL, 'СБТ 1.1.2 Дансны авлага', 'MNT', 'Актив', FALSE, 0),
  (16, '130200', 'Хүүгийн авлага', 'Interest Receivable', 'asset', 14, TRUE, NULL, 'СБТ 1.1.4 Бусад авлага', 'MNT', 'Актив', FALSE, 0),
  (17, '130300', 'Ногдол ашгийн авлага', 'Dividend Receivable', 'asset', 14, TRUE, NULL, 'СБТ 1.1.4 Бусад авлага', 'MNT', 'Актив', FALSE, 0),
  (18, '130400', 'Ажилтны авлага', 'Employee Receivables', 'asset', 14, TRUE, NULL, 'СБТ 1.1.4 Бусад авлага', 'MNT', 'Актив', FALSE, 0),
  (19, '130500', 'Татварын авлага', 'Tax Receivable', 'asset', 14, TRUE, NULL, 'СБТ 1.1.3 Татвар, НДШ-ийн авлага', 'MNT', 'Актив', FALSE, 0),
  (20, '130600', 'НӨАТ-ын авлага', 'VAT Receivable', 'asset', 14, TRUE, NULL, 'СБТ 1.1.3 Татвар, НДШ-ийн авлага', 'MNT', 'Актив', FALSE, 0),
  (21, '130700', 'Холбоотой талуудын авлага', 'Related Party Receivables', 'asset', 14, TRUE, NULL, 'СБТ 1.1.4 Бусад авлага', 'MNT', 'Актив', FALSE, 0),
  (22, '130800', 'Бусад авлага', 'Other Receivables', 'asset', 14, TRUE, NULL, 'СБТ 1.1.4 Бусад авлага', 'MNT', 'Актив', FALSE, 0),
  (23, '130900', 'Эргэлзээтэй авлагын хасагдуулга (хасах)', 'Allowance for Doubtful Debts', 'asset', 14, TRUE, NULL, 'СБТ 1.1.4 Бусад авлага', 'MNT', 'Актив', FALSE, 0),
  (24, '140000', 'Урьдчилж төлсөн тооцоо ба зардал', 'Prepayments & Advances', 'asset', NULL, TRUE, NULL, NULL, 'MNT', 'Актив', FALSE, 0),
  (25, '140100', 'Нийлүүлэгчид урьдчилж төлсөн', 'Advances to Suppliers', 'asset', 24, TRUE, NULL, 'СБТ 1.1.7 Урьдчилж төлсөн зардал/тооцоо', 'MNT', 'Актив', FALSE, 0),
  (26, '140200', 'Урьдчилж төлсөн зардал', 'Prepaid Expenses', 'asset', 24, TRUE, NULL, 'СБТ 1.1.7 Урьдчилж төлсөн зардал/тооцоо', 'MNT', 'Актив', FALSE, 0),
  (27, '140300', 'Урьдчилж төлсөн татвар', 'Prepaid Tax', 'asset', 24, TRUE, NULL, 'СБТ 1.1.7 Урьдчилж төлсөн зардал/тооцоо', 'MNT', 'Актив', FALSE, 0),
  (28, '140900', 'Бусад эргэлтийн хөрөнгө', 'Other Current Assets', 'asset', 24, TRUE, NULL, 'СБТ 1.1.8 Бусад эргэлтийн хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (29, '150000', 'Бараа материал', 'Inventory', 'asset', NULL, TRUE, NULL, NULL, 'MNT', 'Актив', FALSE, 0),
  (30, '150100', 'Түүхий эд, үндсэн материал', 'Raw Materials', 'asset', 29, TRUE, NULL, 'СБТ 1.1.6 Бараа материал', 'MNT', 'Актив', FALSE, 0),
  (31, '150200', 'Туслах материал, сэлбэг', 'Supplies & Spare Parts', 'asset', 29, TRUE, NULL, 'СБТ 1.1.6 Бараа материал', 'MNT', 'Актив', FALSE, 0),
  (32, '150300', 'Дуусаагүй үйлдвэрлэл', 'Work in Progress', 'asset', 29, TRUE, NULL, 'СБТ 1.1.6 Бараа материал', 'MNT', 'Актив', FALSE, 0),
  (33, '150400', 'Бэлэн бүтээгдэхүүн', 'Finished Goods', 'asset', 29, TRUE, NULL, 'СБТ 1.1.6 Бараа материал', 'MNT', 'Актив', FALSE, 0),
  (34, '150500', 'Худалдааны бараа', 'Merchandise', 'asset', 29, TRUE, NULL, 'СБТ 1.1.6 Бараа материал', 'MNT', 'Актив', FALSE, 0),
  (35, '150600', 'Бага үнэтэй, түргэн элэгдэх зүйл', 'Low-value Items', 'asset', 29, TRUE, NULL, 'СБТ 1.1.6 Бараа материал', 'MNT', 'Актив', FALSE, 0),
  (36, '150700', 'Замд яваа бараа материал', 'Inventory in Transit', 'asset', 29, TRUE, NULL, 'СБТ 1.1.6 Бараа материал', 'MNT', 'Актив', FALSE, 0),
  (37, '150900', 'Бараа материалын үнэ бууралт (хасах)', 'Inventory Write-down', 'asset', 29, TRUE, NULL, 'СБТ 1.1.6 Бараа материал', 'MNT', 'Актив', FALSE, 0),
  (38, '160000', 'Үндсэн хөрөнгө', 'Property, Plant & Equipment', 'asset', NULL, TRUE, NULL, NULL, 'MNT', 'Актив', FALSE, 0),
  (39, '160100', 'Газар', 'Land', 'asset', 38, TRUE, NULL, 'СБТ 1.2.1 Үндсэн хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (40, '160200', 'Барилга, байгууламж', 'Buildings', 'asset', 38, TRUE, NULL, 'СБТ 1.2.1 Үндсэн хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (41, '160300', 'Машин, тоног төхөөрөмж', 'Machinery & Equipment', 'asset', 38, TRUE, NULL, 'СБТ 1.2.1 Үндсэн хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (42, '160400', 'Тээврийн хэрэгсэл', 'Vehicles', 'asset', 38, TRUE, NULL, 'СБТ 1.2.1 Үндсэн хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (43, '160500', 'Тавилга, эд хогшил', 'Furniture & Fixtures', 'asset', 38, TRUE, NULL, 'СБТ 1.2.1 Үндсэн хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (44, '160600', 'Компьютер, оффисын тоног төхөөрөмж', 'Computers & Office Equipment', 'asset', 38, TRUE, NULL, 'СБТ 1.2.1 Үндсэн хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (45, '160700', 'Барилгын явцад буй хөрөнгө', 'Construction in Progress', 'asset', 38, TRUE, NULL, 'СБТ 1.2.1 Үндсэн хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (46, '160800', 'Бусад үндсэн хөрөнгө', 'Other PP&E', 'asset', 38, TRUE, NULL, 'СБТ 1.2.1 Үндсэн хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (47, '160900', 'Хуримтлагдсан элэгдэл (хасах)', 'Accumulated Depreciation', 'asset', 38, TRUE, NULL, 'СБТ 1.2.1 Үндсэн хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (48, '170000', 'Биет бус хөрөнгө', 'Intangible Assets', 'asset', NULL, TRUE, NULL, NULL, 'MNT', 'Актив', FALSE, 0),
  (49, '170100', 'Програм хангамж', 'Software', 'asset', 48, TRUE, NULL, 'СБТ 1.2.2 Биет бус хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (50, '170200', 'Лиценз, эрхийн зөвшөөрөл', 'Licenses & Permits', 'asset', 48, TRUE, NULL, 'СБТ 1.2.2 Биет бус хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (51, '170300', 'Барааны тэмдэг, патент', 'Trademarks & Patents', 'asset', 48, TRUE, NULL, 'СБТ 1.2.2 Биет бус хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (52, '170400', 'Гудвил', 'Goodwill', 'asset', 48, TRUE, NULL, 'СБТ 1.2.2 Биет бус хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (53, '170800', 'Бусад биет бус хөрөнгө', 'Other Intangibles', 'asset', 48, TRUE, NULL, 'СБТ 1.2.2 Биет бус хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (54, '170900', 'Хуримтлагдсан хорогдол (хасах)', 'Accumulated Amortization', 'asset', 48, TRUE, NULL, 'СБТ 1.2.2 Биет бус хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (55, '180000', 'Урт хугацаат хөрөнгө оруулалт ба бусад', 'Long-term Investments & Other', 'asset', NULL, TRUE, NULL, NULL, 'MNT', 'Актив', FALSE, 0),
  (56, '180100', 'Охин/хараат компанид оруулалт', 'Investment in Subsidiaries', 'asset', 55, TRUE, NULL, 'СБТ 1.2.4 Урт хугацаат хөрөнгө оруулалт', 'MNT', 'Актив', FALSE, 0),
  (57, '180200', 'Урт хугацаат хадгаламж', 'Long-term Deposits', 'asset', 55, TRUE, NULL, 'СБТ 1.2.4 Урт хугацаат хөрөнгө оруулалт', 'MNT', 'Актив', FALSE, 0),
  (58, '180300', 'Урт хугацаат авлага', 'Long-term Receivables', 'asset', 55, TRUE, NULL, 'СБТ 1.2.4 Урт хугацаат хөрөнгө оруулалт', 'MNT', 'Актив', FALSE, 0),
  (59, '180400', 'Хойшлогдсон татварын хөрөнгө', 'Deferred Tax Asset', 'asset', 55, TRUE, NULL, 'СБТ 1.2.6 Хойшлогдсон татварын хөрөнгө', 'MNT', 'Актив', FALSE, 0),
  (60, '180900', 'Бусад урт хугацаат хөрөнгө', 'Other Non-current Assets', 'asset', 55, TRUE, NULL, 'СБТ 1.2.4 Урт хугацаат хөрөнгө оруулалт', 'MNT', 'Актив', FALSE, 0),
  (61, '310000', 'Дансны болон бусад өглөг', 'Trade & Other Payables', 'liability', NULL, TRUE, NULL, NULL, 'MNT', 'Пассив', FALSE, 0),
  (62, '310100', 'Нийлүүлэгч, гүйцэтгэгчийн өглөг', 'Trade Payables', 'liability', 61, TRUE, NULL, 'СБТ 2.1.1.1 Дансны өглөг', 'MNT', 'Пассив', FALSE, 0),
  (63, '310200', 'Холбоотой талуудын өглөг', 'Related Party Payables', 'liability', 61, TRUE, NULL, 'СБТ 2.1.1.1 Дансны өглөг', 'MNT', 'Пассив', FALSE, 0),
  (64, '310300', 'Урьдчилж авсан орлого', 'Deferred Income', 'liability', 61, TRUE, NULL, 'СБТ 2.1.1.8 Урьдчилж орсон орлого', 'MNT', 'Пассив', FALSE, 0),
  (65, '310900', 'Бусад өглөг', 'Other Payables', 'liability', 61, TRUE, NULL, 'СБТ 2.1.1.1 Дансны өглөг', 'MNT', 'Пассив', FALSE, 0),
  (66, '320000', 'Цалин ба нийгмийн даатгалын өглөг', 'Payroll & Social Insurance Payables', 'liability', NULL, TRUE, NULL, NULL, 'MNT', 'Пассив', FALSE, 0),
  (67, '320100', 'Цалингийн өглөг', 'Wages Payable', 'liability', 66, TRUE, NULL, 'СБТ 2.1.1.2 Цалингийн өглөг', 'MNT', 'Пассив', FALSE, 0),
  (68, '320200', 'Нийгмийн даатгалын шимтгэлийн өглөг', 'Social Insurance Payable', 'liability', 66, TRUE, NULL, 'СБТ 2.1.1.4 НДШ-ийн өглөг', 'MNT', 'Пассив', FALSE, 0),
  (69, '320300', 'ХХОАТ-ын суутгалын өглөг', 'PIT Withholding Payable', 'liability', 66, TRUE, NULL, 'СБТ 2.1.1.2 Цалингийн өглөг', 'MNT', 'Пассив', FALSE, 0),
  (70, '330000', 'Татварын өр төлбөр', 'Tax Payables', 'liability', NULL, TRUE, NULL, NULL, 'MNT', 'Пассив', FALSE, 0),
  (71, '330100', 'НӨАТ-ын өглөг', 'VAT Payable', 'liability', 70, TRUE, NULL, 'СБТ 2.1.1.3 Татварын өр', 'MNT', 'Пассив', FALSE, 0),
  (72, '330200', 'ААНОАТ-ын өглөг', 'Corporate Income Tax Payable', 'liability', 70, TRUE, NULL, 'СБТ 2.1.1.3 Татварын өр', 'MNT', 'Пассив', FALSE, 0),
  (73, '330300', 'Бусад татвар, хураамжийн өглөг', 'Other Taxes Payable', 'liability', 70, TRUE, NULL, 'СБТ 2.1.1.3 Татварын өр', 'MNT', 'Пассив', FALSE, 0),
  (74, '340000', 'Богино хугацаат зээл ба хүүгийн өглөг', 'Short-term Loans & Interest', 'liability', NULL, TRUE, NULL, NULL, 'MNT', 'Пассив', FALSE, 0),
  (75, '340100', 'Богино хугацаат зээл', 'Short-term Loans', 'liability', 74, TRUE, NULL, 'СБТ 2.1.1.5 Богино хугацаат зээл', 'MNT', 'Пассив', FALSE, 0),
  (76, '340200', 'Хүүгийн өглөг', 'Interest Payable', 'liability', 74, TRUE, NULL, 'СБТ 2.1.1.6 Хүүний өглөг', 'MNT', 'Пассив', FALSE, 0),
  (77, '340300', 'Ногдол ашгийн өглөг', 'Dividend Payable', 'liability', 74, TRUE, NULL, 'СБТ 2.1.1.7 Ногдол ашгийн өглөг', 'MNT', 'Пассив', FALSE, 0),
  (78, '350000', 'Хуримтлагдсан өр төлбөр ба нөөц', 'Accrued Liabilities & Provisions', 'liability', NULL, TRUE, NULL, NULL, 'MNT', 'Пассив', FALSE, 0),
  (79, '350100', 'Хуримтлагдсан зардлын өглөг', 'Accrued Expenses', 'liability', 78, TRUE, NULL, 'СБТ 2.1.1.10 Бусад богино хугацаат өр төлбөр', 'MNT', 'Пассив', FALSE, 0),
  (80, '350200', 'Урьдчилгаа татвар, нөөц', 'Provisions', 'liability', 78, TRUE, NULL, 'СБТ 2.1.1.9 Нөөц /өр төлбөр/', 'MNT', 'Пассив', FALSE, 0),
  (81, '410000', 'Урт хугацаат өр төлбөр', 'Long-term Liabilities', 'liability', NULL, TRUE, NULL, NULL, 'MNT', 'Пассив', FALSE, 0),
  (82, '410100', 'Урт хугацаат зээл', 'Long-term Loans', 'liability', 81, TRUE, NULL, 'СБТ 2.1.2.1 Урт хугацаат зээл', 'MNT', 'Пассив', FALSE, 0),
  (83, '410200', 'Бонд, өрийн бичиг', 'Bonds Payable', 'liability', 81, TRUE, NULL, 'СБТ 2.1.2.1 Урт хугацаат зээл', 'MNT', 'Пассив', FALSE, 0),
  (84, '410300', 'Санхүүгийн түрээсийн өглөг', 'Finance Lease Liability', 'liability', 81, TRUE, NULL, 'СБТ 2.1.2.1 Урт хугацаат зээл', 'MNT', 'Пассив', FALSE, 0),
  (85, '410400', 'Хойшлогдсон татварын өр', 'Deferred Tax Liability', 'liability', 81, TRUE, NULL, 'СБТ 2.1.2.3 Хойшлогдсон татварын өр', 'MNT', 'Пассив', FALSE, 0),
  (86, '410900', 'Бусад урт хугацаат өр төлбөр', 'Other Non-current Liabilities', 'liability', 81, TRUE, NULL, 'СБТ 2.1.2.1 Урт хугацаат зээл', 'MNT', 'Пассив', FALSE, 0),
  (87, '510000', 'Эзэмшигчийн өмч', 'Owner''s Equity', 'equity', NULL, TRUE, NULL, NULL, 'MNT', 'Пассив', FALSE, 0),
  (88, '510100', 'Өмч (хувь нийлүүлсэн хөрөнгө)', 'Share Capital', 'equity', 87, TRUE, NULL, 'СБТ 2.3.1 Өмч', 'MNT', 'Пассив', FALSE, 0),
  (89, '510200', 'Халаасны хувьцаа (хасах)', 'Treasury Shares', 'equity', 87, TRUE, NULL, 'СБТ 2.3.2 Халаасны хувьцаа', 'MNT', 'Пассив', FALSE, 0),
  (90, '510300', 'Нэмж төлөгдсөн капитал', 'Additional Paid-in Capital', 'equity', 87, TRUE, NULL, 'СБТ 2.3.3 Нэмж төлөгдсөн капитал', 'MNT', 'Пассив', FALSE, 0),
  (91, '520000', 'Нөөц ба дахин үнэлгээ', 'Reserves & Revaluation', 'equity', NULL, TRUE, NULL, NULL, 'MNT', 'Пассив', FALSE, 0),
  (92, '520100', 'Дахин үнэлгээний нөөц', 'Revaluation Reserve', 'equity', 91, TRUE, NULL, 'СБТ 2.3.4 Хөрөнгийн дахин үнэлгээний нэмэгдэл', 'MNT', 'Пассив', FALSE, 0),
  (93, '520200', 'Гадаад валютын хөрвүүлгийн нөөц', 'FX Translation Reserve', 'equity', 91, TRUE, NULL, 'СБТ 2.3.5 Гадаад валютын хөрвүүлэлтийн нөөц', 'MNT', 'Пассив', FALSE, 0),
  (94, '520300', 'Заавал байгуулах нөөц', 'Statutory Reserve', 'equity', 91, TRUE, NULL, 'СБТ 2.3.6 Эздийн өмчийн бусад хэсэг', 'MNT', 'Пассив', FALSE, 0),
  (95, '530000', 'Хуримтлагдсан ашиг (алдагдал)', 'Retained Earnings', 'equity', NULL, TRUE, NULL, NULL, 'MNT', 'Пассив', FALSE, 0),
  (96, '530100', 'Тайлант үеийн цэвэр ашиг (алдагдал)', 'Current Year Profit/(Loss)', 'equity', 95, TRUE, NULL, 'СБТ 2.3.7 Хуримтлагдсан ашиг', 'MNT', 'Пассив', FALSE, 0),
  (97, '530200', 'Өмнөх үеийн хуримтлагдсан ашиг', 'Prior Year Retained Earnings', 'equity', 95, TRUE, NULL, 'СБТ 2.3.7 Хуримтлагдсан ашиг', 'MNT', 'Пассив', FALSE, 0),
  (98, '610000', 'Үндсэн үйл ажиллагааны орлого', 'Operating Revenue', 'income', NULL, TRUE, NULL, NULL, 'MNT', 'Пассив', FALSE, 0),
  (99, '610100', 'Бараа борлуулсны орлого', 'Sales Revenue — Goods', 'income', 98, TRUE, NULL, 'ОДТ 1 Борлуулалтын орлого (цэвэр)', 'MNT', 'Пассив', FALSE, 0),
  (100, '610200', 'Ажил, үйлчилгээ үзүүлсний орлого', 'Service Revenue', 'income', 98, TRUE, NULL, 'ОДТ 1 Борлуулалтын орлого (цэвэр)', 'MNT', 'Пассив', FALSE, 0),
  (101, '610300', 'Борлуулалтын хөнгөлөлт, буцаалт (хасах)', 'Sales Discounts & Returns', 'income', 98, TRUE, NULL, 'ОДТ 1 Борлуулалтын орлого (цэвэр)', 'MNT', 'Пассив', FALSE, 0),
  (102, '620000', 'Бусад үйл ажиллагааны орлого', 'Other Income', 'income', NULL, TRUE, NULL, NULL, 'MNT', 'Пассив', FALSE, 0),
  (103, '620100', 'Түрээсийн орлого', 'Rental Income', 'income', 102, TRUE, NULL, 'ОДТ 4 Түрээсийн орлого', 'MNT', 'Пассив', FALSE, 0),
  (104, '620200', 'Хүүгийн орлого', 'Interest Income', 'income', 102, TRUE, NULL, 'ОДТ 5 Хүүний орлого', 'MNT', 'Пассив', FALSE, 0),
  (105, '620300', 'Ногдол ашгийн орлого', 'Dividend Income', 'income', 102, TRUE, NULL, 'ОДТ 6 Ногдол ашгийн орлого', 'MNT', 'Пассив', FALSE, 0),
  (106, '620400', 'Гадаад валютын ханшийн олз', 'FX Gain', 'income', 102, TRUE, NULL, 'ОДТ 13 Гадаад валютын ханшийн зөрүүний олз (гарз)', 'MNT', 'Пассив', FALSE, 0),
  (107, '620500', 'Үндсэн хөрөнгө борлуулсны олз', 'Gain on Disposal of PP&E', 'income', 102, TRUE, NULL, 'ОДТ 14 Үндсэн хөрөнгө данснаас хассаны олз (гарз)', 'MNT', 'Пассив', FALSE, 0),
  (108, '620600', 'Татаас, санхүүжилтийн орлого', 'Grants & Subsidies', 'income', 102, TRUE, NULL, 'ОДТ 8 Бусад орлого', 'MNT', 'Пассив', FALSE, 0),
  (109, '620900', 'Бусад орлого', 'Miscellaneous Income', 'income', 102, TRUE, NULL, 'ОДТ 8 Бусад орлого', 'MNT', 'Пассив', FALSE, 0),
  (110, '710000', 'Борлуулсан бараа (бүтээгдэхүүн)-ний өртөг', 'Cost of Sales', 'expense', NULL, TRUE, NULL, NULL, 'MNT', 'Актив', FALSE, 0),
  (111, '710100', 'Борлуулсан барааны өртөг', 'Cost of Goods Sold', 'expense', 110, TRUE, NULL, 'ОДТ 2 Борлуулсан бүтээгдэхүүний өртөг', 'MNT', 'Актив', FALSE, 0),
  (112, '710200', 'Борлуулсан бүтээгдэхүүний өртөг', 'Cost of Products Sold', 'expense', 110, TRUE, NULL, 'ОДТ 2 Борлуулсан бүтээгдэхүүний өртөг', 'MNT', 'Актив', FALSE, 0),
  (113, '710300', 'Үзүүлсэн ажил, үйлчилгээний өртөг', 'Cost of Services', 'expense', 110, TRUE, NULL, 'ОДТ 2 Борлуулсан бүтээгдэхүүний өртөг', 'MNT', 'Актив', FALSE, 0),
  (114, '720000', 'Үйл ажиллагааны зардал', 'Operating Expenses', 'expense', NULL, TRUE, NULL, NULL, 'MNT', 'Актив', FALSE, 0),
  (115, '720100', 'Цалин хөлсний зардал', 'Salaries & Wages', 'expense', 114, TRUE, NULL, 'ОДТ 10 Ерөнхий ба удирдлагын зардал', 'MNT', 'Актив', FALSE, 0),
  (116, '720200', 'Нийгмийн даатгалын шимтгэлийн зардал', 'Social Insurance Expense', 'expense', 114, TRUE, NULL, 'ОДТ 10 Ерөнхий ба удирдлагын зардал', 'MNT', 'Актив', FALSE, 0),
  (117, '720300', 'Элэгдэл, хорогдлын зардал', 'Depreciation & Amortization', 'expense', 114, TRUE, NULL, 'ОДТ 10 Ерөнхий ба удирдлагын зардал', 'MNT', 'Актив', FALSE, 0),
  (118, '720400', 'Түрээсийн зардал', 'Rent Expense', 'expense', 114, TRUE, NULL, 'ОДТ 10 Ерөнхий ба удирдлагын зардал', 'MNT', 'Актив', FALSE, 0),
  (119, '720500', 'Шатахуун, тээврийн зардал', 'Fuel & Transport', 'expense', 114, TRUE, NULL, 'ОДТ 9 Борлуулалт, маркетингийн зардал', 'MNT', 'Актив', FALSE, 0),
  (120, '720600', 'Цахилгаан, дулаан, ус, холбоо', 'Utilities & Communication', 'expense', 114, TRUE, NULL, 'ОДТ 10 Ерөнхий ба удирдлагын зардал', 'MNT', 'Актив', FALSE, 0),
  (121, '720700', 'Засвар үйлчилгээний зардал', 'Repairs & Maintenance', 'expense', 114, TRUE, NULL, 'ОДТ 10 Ерөнхий ба удирдлагын зардал', 'MNT', 'Актив', FALSE, 0),
  (122, '720800', 'Бичиг хэрэг, оффисын зардал', 'Office & Stationery', 'expense', 114, TRUE, NULL, 'ОДТ 10 Ерөнхий ба удирдлагын зардал', 'MNT', 'Актив', FALSE, 0),
  (123, '720900', 'Зар сурталчилгаа, маркетинг', 'Advertising & Marketing', 'expense', 114, TRUE, NULL, 'ОДТ 9 Борлуулалт, маркетингийн зардал', 'MNT', 'Актив', FALSE, 0),
  (124, '721000', 'Томилолт, зочломтгойн зардал', 'Travel & Entertainment', 'expense', 114, TRUE, NULL, 'ОДТ 10 Ерөнхий ба удирдлагын зардал', 'MNT', 'Актив', FALSE, 0),
  (125, '721100', 'Хандив, тусламжийн зардал', 'Donations', 'expense', 114, TRUE, NULL, 'ОДТ 10 Ерөнхий ба удирдлагын зардал', 'MNT', 'Актив', FALSE, 0),
  (126, '721200', 'Эргэлзээтэй авлагын зардал', 'Bad Debt Expense', 'expense', 114, TRUE, NULL, 'ОДТ 10 Ерөнхий ба удирдлагын зардал', 'MNT', 'Актив', FALSE, 0),
  (127, '721900', 'Бусад үйл ажиллагааны зардал', 'Other Operating Expenses', 'expense', 114, TRUE, NULL, 'ОДТ 10 Ерөнхий ба удирдлагын зардал', 'MNT', 'Актив', FALSE, 0),
  (128, '810000', 'Санхүүгийн зардал', 'Finance Costs', 'expense', NULL, TRUE, NULL, NULL, 'MNT', 'Актив', FALSE, 0),
  (129, '810100', 'Хүүгийн зардал', 'Interest Expense', 'expense', 128, TRUE, NULL, 'ОДТ 11 Санхүүгийн зардал', 'MNT', 'Актив', FALSE, 0),
  (130, '810200', 'Гадаад валютын ханшийн гарз', 'FX Loss', 'expense', 128, TRUE, NULL, 'ОДТ 13 Гадаад валютын ханшийн зөрүүний олз (гарз)', 'MNT', 'Актив', FALSE, 0),
  (131, '810300', 'Банкны шимтгэл, хураамж', 'Bank Charges', 'expense', 128, TRUE, NULL, 'ОДТ 11 Санхүүгийн зардал', 'MNT', 'Актив', FALSE, 0),
  (132, '820000', 'Бусад зардал ба алдагдал', 'Other Expenses & Losses', 'expense', NULL, TRUE, NULL, NULL, 'MNT', 'Актив', FALSE, 0),
  (133, '820100', 'Үндсэн хөрөнгө хассаны гарз', 'Loss on Disposal of PP&E', 'expense', 132, TRUE, NULL, 'ОДТ 14 Үндсэн хөрөнгө данснаас хассаны олз (гарз)', 'MNT', 'Актив', FALSE, 0),
  (134, '820200', 'Торгууль, алданги', 'Penalties & Fines', 'expense', 132, TRUE, NULL, 'ОДТ 12 Бусад зардал', 'MNT', 'Актив', FALSE, 0),
  (135, '820900', 'Бусад зардал', 'Miscellaneous Expenses', 'expense', 132, TRUE, NULL, 'ОДТ 12 Бусад зардал', 'MNT', 'Актив', FALSE, 0),
  (136, '890000', 'Татварын зардал', 'Income Tax Expense', 'expense', NULL, TRUE, NULL, NULL, 'MNT', 'Актив', FALSE, 0),
  (137, '890100', 'ААНОАТ-ын зардал', 'Corporate Income Tax', 'expense', 136, TRUE, NULL, 'ОДТ 19 Орлогын татварын зардал', 'MNT', 'Актив', FALSE, 0),
  (138, '890200', 'Хойшлогдсон татварын зардал', 'Deferred Tax Expense', 'expense', 136, TRUE, NULL, 'ОДТ 19 Орлогын татварын зардал', 'MNT', 'Актив', FALSE, 0);

PERFORM setval(pg_get_serial_sequence('accounts','id'),
               (SELECT MAX(id) FROM accounts));

END IF;
END $$;
