-- ==========================================================
-- accounts seed — реф accounting.db-гээс шилжүүлсэн дансны мод
-- Нийт: 367 мөр. parent_id холбоос хадгалагдсан тул id-г шууд оруулна.
-- Хүснэгт хоосон үед л оруулна (дахин ажиллуулахад давхардахгүй).
-- Supabase SQL Editor-д ажиллуулна.
-- ==========================================================

DO $$
BEGIN
IF (SELECT COUNT(*) FROM accounts) = 0 THEN

INSERT INTO accounts (id, code, name, type, parent_id, is_active, account_number, currency, nature, journal_type, department_code, department_name, bank_name, bank_account, is_temp, temp_percent) VALUES
  (1, '110000', 'Богино хугацааны хөрөнгө оруулалт', 'asset', NULL, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (2, '111000', 'Касс (бэлэн мөнгө)', 'asset', 1, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (3, '101200', 'Харилцах данс — ХХБ/ТДБ (411096635)', 'asset', 181, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (4, '101100', 'Харилцах данс — Голомт банк (1175156757)', 'asset', 181, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (5, '101300', 'Харилцах данс — М банк (9006906192)', 'asset', 181, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (6, '120000', 'Авлага', 'asset', NULL, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (7, '121000', 'Дансны авлага — харилцагч', 'asset', 6, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (8, '135000', 'Татварын авлага', 'asset', 6, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (9, '125000', 'Бусад богино хугацааны авлага', 'asset', 6, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (10, '124000', 'Ажилтанд олгосон аванс', 'asset', 6, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (11, '121100', 'Авлага — холбоотой этгээд', 'asset', 6, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (12, '121900', 'Эргэлзэгдэх авлагын нөөц', 'asset', 6, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (13, '126000', 'Урьдчилан төлсөн зардал', 'asset', NULL, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (14, '135100', 'Урьдчилан төлсөн ААТ', 'asset', 13, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (15, '151000', 'Тавилга, хэрэгслийн хуримтлагдсан элэгдэл (хасах)', 'asset', 13, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (16, '130000', 'Бараа материал', 'asset', NULL, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (17, '131000', 'Түлш (дизель, бензин)', 'asset', 16, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (18, '132000', 'Сэлбэг хэрэгсэл', 'asset', 16, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (19, '133000', 'Бусад бараа материал', 'asset', 16, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (20, '150000', 'Үндсэн хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (21, '160000', 'Биет бус хөрөнгө', 'asset', 20, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (22, '161000', 'Тээврийн хэрэгсэл — ачааны машин', 'asset', 20, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (23, '161500', 'Тоног төхөөрөмж', 'asset', 20, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (24, '161600', 'Барилга, байгууламж', 'asset', 20, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (25, '161900', 'Хуримтлагдсан элэгдэл — ТХ', 'asset', 20, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (26, '170000', 'Урт хугацааны хөрөнгө оруулалт', 'asset', NULL, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (27, '171000', 'Програм хангамж', 'asset', 26, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (28, '300000', 'Богино хугацааны өр төлбөр', 'liability', NULL, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (29, '330000', 'Богино хугацааны зээл, зээлийн өр', 'liability', 28, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (30, '331000', 'Дансны өглөг — нийлүүлэгч', 'liability', 29, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (31, '321000', 'Бусад богино хугацааны өр төлбөр', 'liability', 29, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (32, '331100', 'Ажилтанд төлөх цалин', 'liability', 28, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (33, '310000', 'Нийлүүлэгчийн өглөг', 'liability', 28, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (34, '315100', 'ААТ-ын өглөг', 'liability', 33, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (35, '315200', 'НӨТ-ын өглөг', 'liability', 33, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (36, '314100', 'ХХОАТ-ын өглөг', 'liability', 33, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (37, 'OLD_3140', 'НДШ өглөг', 'liability', 28, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (38, '332100', 'НД-ын өглөг', 'liability', 37, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (39, '332200', 'Ажил олгогчийн НДШ өглөг', 'liability', 37, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (40, 'OLD_3150', 'Бусад богино хугацаат өр', 'liability', 28, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (41, 'OLD_3151', 'Захиалагчаас авсан урьдчилгаа', 'liability', 40, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (42, '341000', 'Банкны богино хугацааны зээл', 'liability', 40, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (43, '333200', 'Хүүгийн өглөг', 'liability', 40, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (44, 'OLD_3154', 'Бусад өглөг', 'liability', 40, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (45, '333000', 'Хүлээн авсан аванс (бусад)', 'liability', 28, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (46, 'OLD_3211', 'НДШ тооцоо', 'liability', 45, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (47, '331300', 'Урамшуулал, шагналын нөөц', 'liability', 28, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (48, '400000', 'Урт хугацааны өр төлбөр', 'liability', NULL, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (49, '410000', 'Урт хугацааны зээл', 'liability', 48, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (50, '411000', 'Банкны урт хугацааны зээл', 'liability', 49, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (51, '421000', 'Лизингийн өглөг — тээврийн хэрэгсэл', 'liability', 48, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (52, '421100', 'Лизингийн өглөг — үл хөдлөх', 'liability', 48, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (53, '431000', 'Засварын нөөц', 'liability', 48, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (54, '432000', 'Хууль эрхийн нэхэмжлэлийн нөөц', 'liability', 48, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (55, '333300', 'Бусад богино хугацааны өглөг', 'liability', 28, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (56, '500000', 'Өөрийн хөрөнгө', 'equity', NULL, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (57, '510000', 'Өөрийн хөрөнгө', 'equity', 56, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (58, '511000', 'Нэмэлт төлбөртэй хувьцаа', 'equity', 57, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (59, 'OLD_5200', 'Нэмж төлөгдсөн капитал', 'equity', 56, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (60, 'OLD_5300', 'Хуримтлагдсан ашиг', 'equity', 56, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (61, '520000', 'Нөөц сан ба бусад', 'equity', 60, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (62, '521000', 'Тайлант оны цэвэр ашиг (алдагдал)', 'equity', 60, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (63, '600000', 'Орлого', 'income', NULL, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (64, '610000', 'Борлуулалтын орлого', 'income', 63, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (65, '611000', 'Ачааны тээврийн орлого', 'income', 64, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (66, '611100', 'Зорчигчийн тээврийн орлого', 'income', 64, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (67, '611300', 'Агуулахын үйлчилгээний орлого', 'income', 64, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (68, '620000', 'Бусад үйлчилгээний орлого', 'income', 63, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (69, '840000', 'Санхүүгийн зардал', 'income', NULL, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (70, '841000', 'Хүүгийн орлого', 'income', 69, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (71, 'OLD_7000', 'Борлуулсан бүтээгдэхүүний өртөг', 'expense', NULL, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (72, '710000', 'Борлуулалтын өртөг', 'expense', 71, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (73, '711000', 'Түлшний зардал', 'expense', 72, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (74, '711100', 'Тосолгооны материалын зардал', 'expense', 72, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (75, '719000', 'Бусад шууд тээврийн зардал', 'expense', 71, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (76, '715000', 'Замын хураамж, гүүрийн хураамж', 'expense', 75, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (77, '715100', 'Тээврийн зөвшөөрлийн хураамж / гааль', 'expense', 75, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (78, '713000', 'Жолоочийн цалин, урамшуулал', 'expense', 75, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (79, '714000', 'Засвар үйлчилгээний зардал', 'expense', 75, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (80, '717000', 'Тээврийн даатгал', 'expense', 75, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (81, '716000', 'Жолоочийн томилолт, хоол, байр', 'expense', 75, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (82, '800000', 'Ерөнхий, захиргааны зардал', 'expense', NULL, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (83, '810000', 'Хөдөлмөрийн хөлсний зардал', 'expense', 82, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (84, '811000', 'Захиргааны ажилтны цалин', 'expense', 83, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (85, '812000', 'Ажил олгогчийн НДШ/ЭМНДШ зардал', 'expense', 83, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (86, '811100', 'Захиргааны ажилтны НД шимтгэл (АО)', 'expense', 83, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (87, '820000', 'Ерөнхий үйл ажиллагааны зардал', 'expense', 82, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (88, '821000', 'Түрээсийн зардал', 'expense', 87, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (89, '821100', 'Нийтийн үйлчилгээний зардал', 'expense', 87, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (90, '821200', 'Харилцаа холбооны зардал', 'expense', 87, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (91, '821300', 'Оффисын хэрэглэлийн зардал', 'expense', 87, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (92, '821400', 'Аялал, томилолтын зардал', 'expense', 87, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (93, '830000', 'Санхүүгийн зардал', 'expense', 82, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (94, '831000', 'Зээлийн хүүгийн зардал', 'expense', 93, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (95, '831100', 'Лизингийн хүүгийн зардал', 'expense', 93, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (96, '850000', 'Элэгдэл, хорогдол', 'expense', 82, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (97, '851000', 'ТХ-ийн элэгдэл (ачааны машин)', 'expense', 96, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (98, '851500', 'Биет бус хөрөнгийн хорогдол', 'expense', 96, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (99, '866000', 'Бусад зардал', 'expense', 82, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (100, '831300', 'Ханшийн зөрүүгийн алдагдал / шимтгэл', 'expense', 99, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (101, '730000', 'Ерөнхий болон захиргааны зардал', 'expense', 82, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (102, '831200', 'Банкны шимтгэл, үйлчилгээний төлбөр', 'expense', 99, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (103, '900000', 'Татварын зардал', 'expense', NULL, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (104, '910000', 'Орлогын татварын зардал', 'expense', 103, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (105, '200201', 'Барилга, байгууламж (ҮХ)', 'asset', NULL, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (106, '200301', 'Машин, тоног төхөөрөмж (ҮХ)', 'asset', NULL, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (107, '200401', 'Тээврийн хэрэгсэл (ҮХ)', 'asset', NULL, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (108, '200501', 'Тавилга, эд хогшил (ҮХ)', 'asset', NULL, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (109, '200601', 'Компьютер, бусад хэрэгсэл (ҮХ)', 'asset', NULL, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (110, '200701', 'Бусад үндсэн хөрөнгө', 'asset', NULL, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (111, '200801', 'Холбооны тоног төхөөрөмж (ҮХ)', 'asset', NULL, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (112, '201001', 'Бусад эргэлтийн бус хөрөнгө', 'asset', NULL, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (113, '201201', 'Барилга — хуримтлагдсан элэгдэл', 'asset', NULL, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (114, '201301', 'Машин, тоног төхөөрөмж — хуримтлагдсан элэгдэл', 'asset', NULL, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (115, '201401', 'Тээврийн хэрэгсэл — хуримтлагдсан элэгдэл', 'asset', NULL, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (116, '201501', 'Тавилга, эд хогшил — хуримтлагдсан элэгдэл', 'asset', NULL, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (117, '201601', 'Компьютер, хэрэгсэл — хуримтлагдсан элэгдэл', 'asset', NULL, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (118, '201701', 'Бусад ҮХ — хуримтлагдсан элэгдэл', 'asset', NULL, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (119, '201801', 'Холбооны тоног — хуримтлагдсан элэгдэл', 'asset', NULL, FALSE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (120, '135200', 'Оруулсан НӨАТ-ын авлага', 'asset', NULL, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (121, '112000', 'Хугацаат хадгаламж (3 сар хүртэл)', 'asset', 1, TRUE, NULL, 'MNT', 'Актив', 'Харилцах', NULL, NULL, NULL, NULL, FALSE, 0),
  (122, '113000', 'Замд яваа мөнгө', 'asset', 1, TRUE, NULL, 'MNT', 'Актив', 'Харилцах', NULL, NULL, NULL, NULL, FALSE, 0),
  (123, '123000', 'НӨТ-ын буцаан авлага', 'asset', 6, TRUE, NULL, 'MNT', 'Актив', 'НӨАТ', NULL, NULL, NULL, NULL, FALSE, 0),
  (124, '124100', 'Ажилтнаас авах нэхэмжлэл', 'asset', 6, TRUE, NULL, 'MNT', 'Актив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (125, '131100', 'Тосолгооны материал', 'asset', 16, TRUE, NULL, 'MNT', 'Актив', 'Бараа материал', NULL, NULL, NULL, NULL, FALSE, 0),
  (126, '132100', 'Дугуй, хоолой', 'asset', 16, TRUE, NULL, 'MNT', 'Актив', 'Бараа материал', NULL, NULL, NULL, NULL, FALSE, 0),
  (127, '135300', 'ХХОАТ-ын буцаан авлага', 'asset', 8, TRUE, NULL, 'MNT', 'Актив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (128, '152000', 'Урт хугацааны авлага', 'asset', 20, TRUE, NULL, 'MNT', 'Актив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (129, '161100', 'Тээврийн хэрэгсэл — суудлын машин', 'asset', 20, TRUE, NULL, 'MNT', 'Актив', 'Үндсэн хөрөнгө', NULL, NULL, NULL, NULL, FALSE, 0),
  (130, '161200', 'Тээврийн хэрэгсэл — тусгай техник', 'asset', 20, TRUE, NULL, 'MNT', 'Актив', 'Үндсэн хөрөнгө', NULL, NULL, NULL, NULL, FALSE, 0),
  (131, '161700', 'Газар', 'asset', 20, TRUE, NULL, 'MNT', 'Актив', 'Үндсэн хөрөнгө', NULL, NULL, NULL, NULL, FALSE, 0),
  (132, '161800', 'Бүтээн байгуулалтад яваа хөрөнгө', 'asset', 20, TRUE, NULL, 'MNT', 'Актив', 'Үндсэн хөрөнгө', NULL, NULL, NULL, NULL, FALSE, 0),
  (133, '162000', 'Ашиглалтын эрхийн актив — Лизинг (ROU)', 'asset', 20, TRUE, NULL, 'MNT', 'Актив', 'Үндсэн хөрөнгө', NULL, NULL, NULL, NULL, FALSE, 0),
  (134, '162100', 'ROU актив — тээврийн хэрэгсэл', 'asset', 20, TRUE, NULL, 'MNT', 'Актив', 'Үндсэн хөрөнгө', NULL, NULL, NULL, NULL, FALSE, 0),
  (135, '162200', 'ROU актив — үл хөдлөх (гараж)', 'asset', 20, TRUE, NULL, 'MNT', 'Актив', 'Үндсэн хөрөнгө', NULL, NULL, NULL, NULL, FALSE, 0),
  (136, '162900', 'Хуримтлагдсан элэгдэл — ROU', 'asset', 20, TRUE, NULL, 'MNT', 'Актив', 'Үндсэн хөрөнгө', NULL, NULL, NULL, NULL, FALSE, 0),
  (137, '171100', 'Тусгай зөвшөөрөл', 'asset', 26, TRUE, NULL, 'MNT', 'Актив', 'Үндсэн хөрөнгө', NULL, NULL, NULL, NULL, FALSE, 0),
  (138, '171900', 'Хуримтлагдсан хорогдол — биет бус хөрөнгө', 'asset', 26, TRUE, NULL, 'MNT', 'Актив', 'Үндсэн хөрөнгө', NULL, NULL, NULL, NULL, FALSE, 0),
  (139, '314200', 'ХОТ-ын өглөг', 'liability', 33, TRUE, NULL, 'MNT', 'Пассив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (140, '315300', 'Бусад татварын өглөг', 'liability', 33, TRUE, NULL, 'MNT', 'Пассив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (141, '320000', 'Хуримтлагдсан зардал ба бусад богино хугацааны өр төлбөр', 'liability', NULL, TRUE, NULL, 'MNT', 'Пассив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (142, '331200', 'Ээлжийн амралтын нөөц', 'liability', 29, TRUE, NULL, 'MNT', 'Пассив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (143, '333100', 'Холбоотой этгээдийн өглөг', 'liability', 29, TRUE, NULL, 'MNT', 'Пассив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (144, '340000', 'Богино хугацааны зээл', 'liability', NULL, TRUE, NULL, 'MNT', 'Пассив', 'Харилцах', NULL, NULL, NULL, NULL, FALSE, 0),
  (145, '342000', 'Урт хугацааны зээлийн богино хэсэг', 'liability', 144, TRUE, NULL, 'MNT', 'Пассив', 'Харилцах', NULL, NULL, NULL, NULL, FALSE, 0),
  (146, '412000', 'Бондын өглөг', 'liability', 49, TRUE, NULL, 'MNT', 'Пассив', 'Харилцах', NULL, NULL, NULL, NULL, FALSE, 0),
  (147, '420000', 'Хойшлогдсон татварын өр төлбөр', 'liability', NULL, TRUE, NULL, 'MNT', 'Пассив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (148, '440000', 'Бусад урт хугацааны өр төлбөр', 'liability', NULL, TRUE, NULL, 'MNT', 'Пассив', 'Ерөнхий журнал', NULL, NULL, NULL, NULL, FALSE, 0),
  (149, '441000', 'Хойшлогдсон татварын өглөг', 'liability', 148, TRUE, NULL, 'MNT', 'Пассив', 'Ерөнхий журнал', NULL, NULL, NULL, NULL, FALSE, 0),
  (150, '512000', 'Хувьцааны урамшуулал', 'equity', 56, TRUE, NULL, 'MNT', 'Пассив', 'Ерөнхий журнал', NULL, NULL, NULL, NULL, FALSE, 0),
  (151, '530000', 'Ногдол ашиг', 'equity', 56, TRUE, NULL, 'MNT', 'Пассив', 'Ерөнхий журнал', NULL, NULL, NULL, NULL, FALSE, 0),
  (152, '540000', 'Бусад дэлгэрэнгүй орлого (OCI)', 'equity', 56, TRUE, NULL, 'MNT', 'Пассив', 'Ерөнхий журнал', NULL, NULL, NULL, NULL, FALSE, 0),
  (153, '611200', 'Тусгай тээврийн орлого (кран, техник)', 'income', 64, TRUE, NULL, 'MNT', 'Пассив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (154, '612000', 'НӨТ-гүй орлогын тохируулга', 'income', 64, TRUE, NULL, 'MNT', 'Пассив', 'НӨАТ', NULL, NULL, NULL, NULL, FALSE, 0),
  (155, '613000', 'Буцаалт, хөнгөлөлт', 'income', 64, TRUE, NULL, 'MNT', 'Пассив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (156, '621000', 'Засвар үйлчилгээний орлого (3-д)', 'income', 68, TRUE, NULL, 'MNT', 'Пассив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (157, '622000', 'Машин түрээсийн орлого', 'income', 68, TRUE, NULL, 'MNT', 'Пассив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (158, '700000', 'Санхүүгийн болон бусад орлого', 'income', NULL, TRUE, NULL, 'MNT', 'Актив', 'Ерөнхий журнал', NULL, NULL, NULL, NULL, FALSE, 0),
  (159, '712000', 'Сэлбэг хэрэгслийн зардал', 'expense', 72, TRUE, NULL, 'MNT', 'Актив', 'Бараа материал', NULL, NULL, NULL, NULL, FALSE, 0),
  (160, '712100', 'Дугуйн зардал', 'expense', 72, TRUE, NULL, 'MNT', 'Актив', 'Бараа материал', NULL, NULL, NULL, NULL, FALSE, 0),
  (161, '713100', 'Жолоочийн НД шимтгэл (АО)', 'expense', 72, TRUE, NULL, 'MNT', 'Актив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (162, '714100', 'Их засварын нөөц (зарцуулалт)', 'expense', 72, TRUE, NULL, 'MNT', 'Актив', 'Ерөнхий журнал', NULL, NULL, NULL, NULL, FALSE, 0),
  (163, '718000', 'Улсын бүртгэл, техникийн үзлэг', 'expense', 72, TRUE, NULL, 'MNT', 'Актив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (164, '811200', 'Сургалт, давтан сургалтын зардал', 'expense', 83, TRUE, NULL, 'MNT', 'Актив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (165, '811300', 'Ажилтны эрүүл мэндийн зардал', 'expense', 83, TRUE, NULL, 'MNT', 'Актив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (166, '841100', 'Ханшийн зөрүүгийн ашиг', 'income', 69, TRUE, NULL, 'MNT', 'Пассив', 'Ерөнхий журнал', NULL, NULL, NULL, NULL, FALSE, 0),
  (167, '851100', 'ТХ-ийн элэгдэл (суудлын машин)', 'expense', 96, TRUE, NULL, 'MNT', 'Актив', 'Үндсэн хөрөнгө', NULL, NULL, NULL, NULL, FALSE, 0),
  (168, '851200', 'Тоног төхөөрөмжийн элэгдэл', 'expense', 96, TRUE, NULL, 'MNT', 'Актив', 'Үндсэн хөрөнгө', NULL, NULL, NULL, NULL, FALSE, 0),
  (169, '851300', 'Барилгын элэгдэл', 'expense', 96, TRUE, NULL, 'MNT', 'Актив', 'Үндсэн хөрөнгө', NULL, NULL, NULL, NULL, FALSE, 0),
  (170, '851400', 'ROU активын элэгдэл (СТОУС 16)', 'expense', 96, TRUE, NULL, 'MNT', 'Актив', 'Үндсэн хөрөнгө', NULL, NULL, NULL, NULL, FALSE, 0),
  (171, '860000', 'Бусад орлого / зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'Актив', 'Ерөнхий журнал', NULL, NULL, NULL, NULL, FALSE, 0),
  (172, '861000', 'ҮХ борлуулалтын ашиг', 'income', 171, TRUE, NULL, 'MNT', 'Пассив', 'Үндсэн хөрөнгө', NULL, NULL, NULL, NULL, FALSE, 0),
  (173, '861100', 'ҮХ борлуулалтын алдагдал', 'expense', 171, TRUE, NULL, 'MNT', 'Актив', 'Үндсэн хөрөнгө', NULL, NULL, NULL, NULL, FALSE, 0),
  (174, '862000', 'Эргэлзэгдэх авлагын зардал', 'expense', 171, TRUE, NULL, 'MNT', 'Актив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (175, '863000', 'Засварын нөөцийн зардал', 'expense', 171, TRUE, NULL, 'MNT', 'Актив', 'Ерөнхий журнал', NULL, NULL, NULL, NULL, FALSE, 0),
  (176, '864000', 'Торгууль, алданги', 'expense', 171, TRUE, NULL, 'MNT', 'Актив', 'Авлага өглөг', NULL, NULL, NULL, NULL, FALSE, 0),
  (177, '865000', 'Бусад орлого (ҮА бус)', 'income', 171, TRUE, NULL, 'MNT', 'Пассив', 'Ерөнхий журнал', NULL, NULL, NULL, NULL, FALSE, 0),
  (178, '911000', 'Хойшлогдсон татварын зардал', 'expense', 103, TRUE, NULL, 'MNT', 'Актив', 'Ерөнхий журнал', NULL, NULL, NULL, NULL, FALSE, 0),
  (179, '100000', 'Мөнгөн хөрөнгө ба түүнтэй адилтгах', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (180, '100100', 'Кассын бэлэн мөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (181, '100200', 'Харилцах дансны мөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (182, '100300', 'Хадгаламжийн дансны мөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (183, '100400', 'Гадаад валютын кассын мөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (184, '100500', 'Гадаад валютын харилцах дансны мөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (185, '100600', 'Акредитив', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (186, '100700', 'Депозитын данс', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (187, '100800', 'Тооцоонд байгаа мөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (188, '100900', 'Бусад мөнгөн хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (189, '110400', 'Бусад богино хугацааны хөрөнгө оруулалт', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (190, '120100', 'Худалдан авагчийн авлага', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (191, '120200', 'Бусад авлага', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (192, '120300', 'Ажилчдын авлага', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (193, '120400', 'Урьдчилж олгосон зардал', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (194, '120500', 'НӨАТ-ын авлага', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (195, '120600', 'Татварын авлага', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (196, '120700', 'Хэтэрсэн зардлын нөхөн авлага', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (197, '120800', 'Холбоотой талуудын авлага', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (198, '120900', 'Эргэлзэгдэх авлагын нөөц (хасах)', 'asset', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (199, '130100', 'Түүхий эд', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (200, '130200', 'Материал', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (201, '130300', 'Дуусаагүй үйлдвэрлэл', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (202, '130400', 'Бэлэн бүтээгдэхүүн', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (203, '130500', 'Худалдааны бараа', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (204, '130600', 'Бага үнэтэй, түргэн элэгдэх зүйл', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (205, '130700', 'Хаягдал материал', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (206, '130800', 'Дамжин өнгөрүүлэх бараа', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (207, '130900', 'Бараа материалын нөөц (хасах)', 'asset', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (208, '140000', 'Урьдчилж төлсөн зардал ба бусад эргэлтийн хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (209, '140100', 'Урьдчилж төлсөн зардал', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (210, '140200', 'Нийлүүлэгчид урьдчилж төлсөн', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (211, '140300', 'Бусад эргэлтийн хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (212, '140400', 'Эргэлтийн хөрөнгийн зарим хэсэг', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (213, '150100', 'Газар', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (214, '150200', 'Барилга байгууламж', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (215, '150300', 'Машин тоног төхөөрөмж', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (216, '150400', 'Тээврийн хэрэгсэл', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (217, '150500', 'Тавилга, хэрэгсэл', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (218, '150600', 'Компьютер, тоног төхөөрөмж', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (219, '150700', 'Барилга байгууламжийн хуримтлагдсан элэгдэл (хасах)', 'asset', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (220, '150800', 'Машин тоног төхөөрөмжийн хуримтлагдсан элэгдэл (хасах)', 'asset', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (221, '150900', 'Тээврийн хэрэгслийн хуримтлагдсан элэгдэл (хасах)', 'asset', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (222, '151100', 'Компьютер, тоног төхөөрөмжийн хуримтлагдсан элэгдэл (хасах)', 'asset', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (223, '151200', 'Барилгын явцад байгаа хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (224, '151300', 'Урьдчилж төлсөн үндсэн хөрөнгийн өртөг', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (225, '151400', 'Бусад үндсэн хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (226, '151500', 'Бусад үндсэн хөрөнгийн хуримтлагдсан элэгдэл (хасах)', 'asset', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (227, '160100', 'Патент', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (228, '160200', 'Зохиогчийн эрх', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (229, '160300', 'Барааны тэмдэг', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (230, '160400', 'Програм хангамж', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (231, '160500', 'Лиценз', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (232, '160600', 'Гудвил', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (233, '160700', 'Бусад биет бус хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (234, '160800', 'Биет бус хөрөнгийн хуримтлагдсан элэгдэл (хасах)', 'asset', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (235, '170100', 'Охин компанид оруулсан хөрөнгө оруулалт', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (236, '170200', 'Нөхөрлөлд оруулсан хөрөнгө оруулалт', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (237, '170300', 'Урт хугацааны хадгаламж', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (238, '170400', 'Бусад урт хугацааны хөрөнгө оруулалт', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (239, '180000', 'Биологийн хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (240, '180100', 'Үйлдвэрлэлийн биологийн хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (241, '180200', 'Хөдөө аж ахуйн биологийн хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (242, '180300', 'Биологийн хөрөнгийн хуримтлагдсан элэгдэл (хасах)', 'asset', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (243, '190000', 'Бусад эргэлтийн бус хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (244, '190100', 'Барьцаанд тавьсан хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (245, '190200', 'Хойшлогдсон татварын хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (246, '190300', 'Урт хугацааны авлага', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (247, '190400', 'Бусад эргэлтийн бус хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (248, '200000', 'Хөрөнгө оруулалтын үл хөдлөх хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (249, '200100', 'Хөрөнгө оруулалтын газар', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (250, '200200', 'Хөрөнгө оруулалтын барилга байгууламж', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (251, '200300', 'Хөрөнгө оруулалтын барилгын хуримтлагдсан элэгдэл (хасах)', 'asset', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (252, '210000', 'Уул уурхайн хайгуул, үнэлгээний хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (253, '210100', 'Хайгуулын зардал', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (254, '210200', 'Ордын нөөцийн үнэлгээ', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (255, '220000', 'Борлуулахаар барьж байгаа эргэлтийн бус хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (256, '220100', 'Борлуулахаар барьж байгаа үндсэн хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (257, '220200', 'Борлуулахаар барьж байгаа бусад хөрөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (258, '230000', 'Урт хугацааны урьдчилж төлсөн зардал', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (259, '230100', 'Урт хугацааны урьдчилж төлсөн зардал', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (260, '230200', 'Урт хугацааны барьцааны мөнгө', 'asset', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (261, '310100', 'Нийлүүлэгчийн өглөг', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (262, '310200', 'Ажил гүйцэтгэгчийн өглөг', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (263, '310300', 'Холбоотой талуудын өглөг', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (264, '310400', 'Бусад өглөг', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (265, '320100', 'Цалин хөлсний өглөг', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (266, '320200', 'НДШ-ний өглөг', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (267, '320300', 'НӨАТ-ын өглөг', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (268, '320400', 'ААНОАТ-ын өглөг', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (269, '320500', 'ХАОАТ-ын өглөг', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (270, '320600', 'Хойшлуулсан орлого', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (271, '320700', 'Нэхэмжилсэн хураамжийн өглөг', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (272, '320800', 'Харилцагчаас урьдчилж авсан', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (273, '320900', 'Хуримтлагдсан өглөг', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (274, '330100', 'Богино хугацааны банкны зээл', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (275, '330200', 'Богино хугацааны бонд', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (276, '330300', 'Урт хугацааны зээлийн богино хугацааны хэсэг', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (277, '330400', 'Санхүүгийн лизингийн богино хугацааны хэсэг', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (278, '330500', 'Бусад богино хугацааны зээл', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (279, '410100', 'Урт хугацааны банкны зээл', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (280, '410200', 'Урт хугацааны бонд', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (281, '410300', 'Урт хугацааны санхүүгийн лизинг', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (282, '410400', 'Холбоотой талуудын урт хугацааны зээл', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (283, '410500', 'Бусад урт хугацааны зээл', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (284, '420100', 'Хойшлогдсон ААНОАТ-ын өр төлбөр', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (285, '430000', 'Нөөц', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (286, '430100', 'Баталгааны нөөц', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (287, '430200', 'Нөхөн сэргээлтийн нөөц', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (288, '430300', 'Тэтгэврийн нөөц', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (289, '430400', 'Бусад нөөц', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (290, '440100', 'Барьцаагаар авсан мөнгө', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (291, '440200', 'Урт хугацааны хойшлуулсан орлого', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (292, '440300', 'Бусад урт хугацааны өр төлбөр', 'liability', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (293, '510100', 'Дүрмийн сан', 'equity', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (294, '510200', 'Нэмэгдэл капитал', 'equity', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (295, '510300', 'Хувьцааны урамшуулал', 'equity', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (296, '510400', 'Хувьцааг буцаан авсан (хасах)', 'equity', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (297, '510500', 'Хуримтлагдсан ашиг (алдагдал)', 'equity', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (298, '510600', 'Тайлант үеийн цэвэр ашиг (алдагдал)', 'equity', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (299, '510700', 'Дахин үнэлгээний нөөц', 'equity', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (300, '510800', 'Гадаад валютын хөрвүүлтийн нөөц', 'equity', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (301, '510900', 'Бусад цогц орлогын нөөц', 'equity', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (302, '520100', 'Хуулийн нөөц сан', 'equity', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (303, '520200', 'Хөгжлийн сан', 'equity', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (304, '520300', 'Ногдол ашгийн өглөг', 'equity', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (305, '520400', 'Бусад нөөц сан', 'equity', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (306, '610100', 'Бараа, бүтээгдэхүүний борлуулалтын орлого', 'income', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (307, '610200', 'Үйлчилгээний орлого', 'income', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (308, '610300', 'Буцаалт, хямдрал (хасах)', 'income', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (309, '610400', 'НӨАТ (хасах)', 'income', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (310, '610500', 'Гадаад валютын орлого', 'income', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (311, '700100', 'Түрээсийн орлого', 'income', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (312, '700200', 'Ногдол ашгийн орлого', 'income', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (313, '700300', 'Хүүгийн орлого', 'income', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (314, '700400', 'Валют ханшийн ашиг', 'income', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (315, '700500', 'Хөрөнгө борлуулсны ашиг', 'income', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (316, '700600', 'Нөөц бусниулсны орлого', 'income', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (317, '700700', 'Татаас, тусламжийн орлого', 'income', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (318, '700800', 'Бусад үйл ажиллагааны орлого', 'income', NULL, TRUE, NULL, 'MNT', 'КТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (319, '710100', 'Борлуулсан бараа материалын өртөг', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (320, '710200', 'Борлуулсан бүтээгдэхүүний өртөг', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (321, '710300', 'Гадаадын борлуулалтын өртөг', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (322, '720000', 'Борлуулалт, маркетингийн зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (323, '720100', 'Зар сурталчилгааны зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (324, '720200', 'Борлуулалтын ажилтны цалин', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (325, '720300', 'Борлуулалтын НДШ', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (326, '720400', 'Борлуулалтын тээврийн зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (327, '720500', 'Борлуулалтын шимтгэл', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (328, '720600', 'Бусад борлуулалтын зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (329, '730100', 'Захиргааны ажилтны цалин', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (330, '730200', 'Захиргааны НДШ', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (331, '730300', 'Түрээсийн зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (332, '730400', 'Нийтийн үйлчилгээний зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (333, '730500', 'Харилцаа холбооны зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (334, '730600', 'Тээвэр, зорчилтын зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (335, '730700', 'Бичиг хэргийн зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (336, '730800', 'Хуулийн болон мэргэшлийн зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (337, '730900', 'Аудитын зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (338, '731000', 'Даатгалын зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (339, '731100', 'Засвар үйлчилгээний зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (340, '731200', 'Элэгдлийн зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (341, '731300', 'Биет бус хөрөнгийн элэгдлийн зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (342, '731400', 'Нийтийн хоол, зочломтгойн зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (343, '731500', 'Сургалт, хөгжлийн зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (344, '731600', 'Компьютерийн зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (345, '731700', 'Хамгаалалтын зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (346, '731800', 'Банкны үйлчилгээний хөлс', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (347, '731900', 'Бусад ерөнхий болон захиргааны зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (348, '840100', 'Зээлийн хүүгийн зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (349, '840200', 'Валют ханшийн алдагдал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (350, '840300', 'Санхүүгийн хэрэгслийн алдагдал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (351, '840400', 'Бусад санхүүгийн зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (352, '870000', 'Бусад үйл ажиллагааны зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (353, '870100', 'Хөрөнгө борлуулсны алдагдал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (354, '870200', 'Нөөц байгуулах зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (355, '870300', 'Тэтгэмж, дэмжлэгийн зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (356, '870400', 'Бусад үйл ажиллагааны зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (357, '910100', 'Тайлант үеийн ААНОАТ-ын зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (358, '910200', 'Хойшлогдсон ААНОАТ-ын зардал (орлого)', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (359, '920000', 'Тусгай зориулалтын данс', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (360, '920100', 'Дотоод тооцооны данс', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (361, '920200', 'Нөхцөлт хөрөнгө, өр төлбөр', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (362, '920300', 'Гарын авлагын данс', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (363, '132200', 'Засварын материал', 'asset', NULL, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (364, '132300', 'Оффисын хэрэглэл', 'asset', NULL, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (365, '132400', 'Аюулгүй ажиллагааны хэрэгсэл', 'asset', NULL, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (366, '811500', 'Урамшуулал цалин', 'expense', 84, TRUE, NULL, 'MNT', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 0),
  (367, '732000', 'Хангамжын зардал', 'expense', NULL, TRUE, NULL, 'MNT', 'ДТ', NULL, NULL, NULL, NULL, NULL, FALSE, 0);

-- BIGSERIAL дарааллыг хамгийн их id-ийн дараа тавина
PERFORM setval(pg_get_serial_sequence('accounts','id'),
               (SELECT MAX(id) FROM accounts));

END IF;
END $$;
