-- ==========================================================
-- accounts seed — Түмэн Тээх ХХК-ийн дансны төлөвлөгөө
-- Эх сурвалж: Дансны_Төлөвлөгөө_TT.xlsx (151 навч + класс/бүлгийн эх данс)
-- Код: AABBCC. Хоёр хэл (name/name_en), зардалд МУСГАА/татвар note.
-- Хүснэгт хоосон үед л оруулна. Supabase SQL Editor-д ажиллуулна.
-- Нийт: 218 данс (151 навч + 19 класс + 48 бүлэг).
-- ==========================================================

DO $$
BEGIN
IF (SELECT COUNT(*) FROM accounts) = 0 THEN

INSERT INTO accounts (id, code, name, name_en, type, parent_id, is_active, note, currency, nature, is_temp, temp_percent) VALUES
  (1, '110000', 'Мөнгө ба банкны данс', 'Cash & Bank', 'asset', NULL, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (2, '110100', 'Касс (Бэлэн мөнгө)', 'Petty Cash', 'asset', 1, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (3, '110101', 'Касс — үндсэн', 'Cash on Hand — Main', 'asset', 2, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (4, '110102', 'Касс — гарын мөнгө (жолоочид)', 'Petty Cash — Drivers', 'asset', 2, TRUE, 'Жолооч нарт олгосон бэлэн мөнгөний нөөц', 'MNT', 'Актив', FALSE, 0),
  (5, '110200', 'Банкны харилцах данс', 'Bank Current Accounts', 'asset', 1, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (6, '110201', 'ХХБ банк — MNT харилцах', 'Khan Bank — MNT Current', 'asset', 5, TRUE, 'Үндсэн үйл ажиллагааны данс', 'MNT', 'Актив', FALSE, 0),
  (7, '110202', 'ХХБ банк — USD харилцах', 'Khan Bank — USD Current', 'asset', 5, TRUE, 'Гадаад валютын данс', 'MNT', 'Актив', FALSE, 0),
  (8, '110203', 'Голомт банк — MNT харилцах', 'Golomt Bank — MNT Current', 'asset', 5, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (9, '110204', 'М банк — MNT харилцах', 'M Bank — MNT Current', 'asset', 5, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (10, '110205', 'ТДБ банк — MNT харилцах', 'TDB Bank — MNT Current', 'asset', 5, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (11, '120000', 'Авлага', 'Trade & Intercompany Receivables', 'asset', NULL, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (12, '121000', 'Худалдан авагчдын авлага', 'Trade Receivables', 'asset', 11, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (13, '121001', 'Тээврийн үйлчилгээний авлага', 'Transport Service Receivables', 'asset', 12, TRUE, 'Гэрээт үйлчлүүлэгчдийн авлага', 'MNT', 'Актив', FALSE, 0),
  (14, '121002', 'Нэхэмжлэлийн авлага (баталгаажаагүй)', 'Invoiced Receivables (Unconfirmed)', 'asset', 12, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (15, '121003', 'Эргэлзээтэй авлагын нөөц (-)', 'Allowance for Doubtful Accounts (-)', 'asset', 12, TRUE, 'Эсрэг данс — хасах утгатай', 'MNT', 'Актив', FALSE, 0),
  (16, '122000', 'Холбоотой байгуулагын авлага', 'Intercompany Receivables', 'asset', 11, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (17, '122001', 'Түмэн Ресурс ХХК — авлага', 'Tumen Resource LLC — Receivable', 'asset', 16, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (18, '122002', 'Түмэн Тээх Сити ХХК — авлага', 'Tumen Teekh City LLC — Receivable', 'asset', 16, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (19, '122003', 'Түмэн Ресурс Технологи ХХК — авлага', 'TRT LLC — Receivable', 'asset', 16, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (20, '122004', 'Түмэн Ресурс Менежмент ХХК — авлага', 'TRM LLC — Receivable', 'asset', 16, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (21, '130000', 'Бусад эргэлтийн хөрөнгө', 'Other Current Assets', 'asset', NULL, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (22, '131000', 'НӨАТ суутгал', 'VAT Input Credit', 'asset', 21, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (23, '131001', 'НӨАТ суутгал (авсан бармитаар)', 'VAT Input — Purchase Invoices', 'asset', 22, TRUE, 'e-Barimt-аар баталгаажсан', 'MNT', 'Актив', FALSE, 0),
  (24, '132000', 'Урьдчилж төлсөн зардал', 'Prepaid Expenses', 'asset', 21, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (25, '132001', 'Урьдчилж төлсөн түрээс', 'Prepaid Rent', 'asset', 24, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (26, '132002', 'Урьдчилж төлсөн даатгал', 'Prepaid Insurance', 'asset', 24, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (27, '132003', 'Бусад урьдчилж төлсөн', 'Other Prepayments', 'asset', 24, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (28, '133000', 'Ажилчидтай тооцоо', 'Employee Advances & Loans', 'asset', 21, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (29, '133001', 'Ажилчдад олгосон зээл', 'Employee Loans', 'asset', 28, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (30, '133002', 'Ажилчдад олгосон урьдчилгаа (цалин)', 'Salary Advances', 'asset', 28, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (31, '133003', 'Томилолтын зардлын урьдчилгаа', 'Travel Advance', 'asset', 28, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (32, '210000', 'Үндсэн хөрөнгө', 'PP&E', 'asset', NULL, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (33, '211000', 'Тавилга, эд хогшил', 'Furniture & Fixtures', 'asset', 32, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (34, '211001', 'Тавилга, эд хогшил — өртөг', 'Furniture & Fixtures — Cost', 'asset', 33, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (35, '211002', 'Тавилга, эд хогшил — хуримт. элэгдэл (-)', 'Furniture — Acc. Depreciation (-)', 'asset', 33, TRUE, 'Эсрэг данс', 'MNT', 'Актив', FALSE, 0),
  (36, '212000', 'Компьютер, техник хэрэгсэл', 'Computers & Equipment', 'asset', 32, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (37, '212001', 'Компьютер, техник — өртөг', 'Computers & Equipment — Cost', 'asset', 36, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (38, '212002', 'Компьютер, техник — хуримт. элэгдэл (-)', 'Computers — Acc. Depreciation (-)', 'asset', 36, TRUE, 'Эсрэг данс', 'MNT', 'Актив', FALSE, 0),
  (39, '213000', 'Оффисын тоног төхөөрөмж', 'Office Equipment', 'asset', 32, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (40, '213001', 'Оффисын тоног төхөөрөмж — өртөг', 'Office Equipment — Cost', 'asset', 39, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (41, '213002', 'Оффисын тоног төхөөрөмж — хуримт. элэгдэл (-)', 'Office Equipment — Acc. Depr. (-)', 'asset', 39, TRUE, 'Эсрэг данс', 'MNT', 'Актив', FALSE, 0),
  (42, '214000', 'Тээврийн хэрэгсэл', 'Vehicles', 'asset', 32, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (43, '214001', 'Тээврийн хэрэгсэл — өртөг', 'Vehicles — Cost', 'asset', 42, TRUE, 'Өмчлөлтэй байвал', 'MNT', 'Актив', FALSE, 0),
  (44, '214002', 'Тээврийн хэрэгсэл — хуримт. элэгдэл (-)', 'Vehicles — Acc. Depreciation (-)', 'asset', 42, TRUE, 'Эсрэг данс', 'MNT', 'Актив', FALSE, 0),
  (45, '215000', 'Бусад үндсэн хөрөнгө', 'Other Fixed Assets', 'asset', 32, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (46, '215001', 'Бусад үндсэн хөрөнгө — өртөг', 'Other Fixed Assets — Cost', 'asset', 45, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (47, '215002', 'Бусад үндсэн хөрөнгө — хуримт. элэгдэл (-)', 'Other Fixed Assets — Acc. Depr. (-)', 'asset', 45, TRUE, 'Эсрэг данс', 'MNT', 'Актив', FALSE, 0),
  (48, '220000', 'Биет бус хөрөнгө', 'Intangibles', 'asset', NULL, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (49, '221000', 'Програм хангамж', 'Software', 'asset', 48, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (50, '221001', 'Програм хангамж — өртөг', 'Software — Cost', 'asset', 49, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (51, '221002', 'Програм хангамж — хуримт. элэгдэл (-)', 'Software — Acc. Amortization (-)', 'asset', 49, TRUE, 'Эсрэг данс', 'MNT', 'Актив', FALSE, 0),
  (52, '222000', 'Лиценз, тусгай зөвшөөрөл', 'Licenses & Permits', 'asset', 48, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (53, '222001', 'Тусгай зөвшөөрөл, лиценз — өртөг', 'License — Cost', 'asset', 52, TRUE, 'Тээврийн тусгай зөвшөөрөл', 'MNT', 'Актив', FALSE, 0),
  (54, '222002', 'Лиценз — хуримт. элэгдэл (-)', 'License — Acc. Amortization (-)', 'asset', 52, TRUE, 'Эсрэг данс', 'MNT', 'Актив', FALSE, 0),
  (55, '230000', 'Урт хугацаат хөрөнгө оруулалт', 'Investments', 'asset', NULL, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (56, '231000', 'Оролцооны хувь', 'Equity Investments', 'asset', 55, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (57, '231001', 'Оролцооны хувь — охин компани', 'Investment in Subsidiaries', 'asset', 56, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (58, '310000', 'Гүйцэтгэгч, нийлүүлэгчдийн өглөг', 'AP', 'liability', NULL, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (59, '311000', 'Гэрээт жолооч, тээвэрчдийн өглөг', 'Contracted Driver Payables', 'liability', 58, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (60, '311001', 'Гэрээт жолооч — тухайн сарын өглөг', 'Contracted Drivers — Current Month', 'liability', 59, TRUE, 'Сар бүр тооцоолж гаргана', 'MNT', 'Пассив', FALSE, 0),
  (61, '311002', 'Гэрээт жолооч — өмнөх сарын өглөг', 'Contracted Drivers — Prior Month', 'liability', 59, TRUE, 'Тооцоо нийлсний дараа шилжинэ', 'MNT', 'Пассив', FALSE, 0),
  (62, '311003', 'Гэрээт жолооч — маргаантай дүн', 'Contracted Drivers — Disputed', 'liability', 59, TRUE, 'Маргаан шийдэгдэх хүртэл', 'MNT', 'Пассив', FALSE, 0),
  (63, '312000', 'Бусад нийлүүлэгчдийн өглөг', 'Other Supplier Payables', 'liability', 58, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (64, '312001', 'GPS, телематик үйлчилгээний өглөг', 'GPS / Telematics Payable', 'liability', 63, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (65, '312002', 'Даатгалын өглөг', 'Insurance Payable', 'liability', 63, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (66, '312003', 'Засвар, үйлчилгээний өглөг', 'Maintenance & Repair Payable', 'liability', 63, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (67, '312004', 'Бусад нийлүүлэгчдийн өглөг', 'Other Supplier Payables', 'liability', 63, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (68, '320000', 'Цалин, НДШ өглөг', 'Payroll Liabilities', 'liability', NULL, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (69, '321000', 'Ажилтны цалин, урамшуулал', 'Employee Compensation', 'liability', 68, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (70, '321001', 'Цалингийн өглөг', 'Salaries Payable', 'liability', 69, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (71, '321002', 'Урамшууллын өглөг', 'Bonus Payable', 'liability', 69, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (72, '321003', 'Ээлжийн амралтын өглөг', 'Accrued Annual Leave', 'liability', 69, TRUE, 'МУСГАА дагуу хуримтлуулна', 'MNT', 'Пассив', FALSE, 0),
  (73, '322000', 'Нийгмийн даатгалын өглөг', 'Social Insurance Payable', 'liability', 68, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (74, '322001', 'НДШ — ажилтны хувь (10%)', 'Employee Social Insurance (10%)', 'liability', 73, TRUE, 'Цалинаас суутгана', 'MNT', 'Пассив', FALSE, 0),
  (75, '322002', 'НДШ — ажил олгогчийн хувь (12.5%)', 'Employer Social Insurance (12.5%)', 'liability', 73, TRUE, 'Зардалд тооцно', 'MNT', 'Пассив', FALSE, 0),
  (76, '322003', 'ЭМНДШ өглөг', 'Health Insurance Payable', 'liability', 73, TRUE, 'Хязгаар: 7,920,000₮', 'MNT', 'Пассив', FALSE, 0),
  (77, '330000', 'Татварын өглөг', 'Tax Payables', 'liability', NULL, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (78, '331000', 'Орлогын татвар', 'Income Tax Payables', 'liability', 77, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (79, '331001', 'HHОАТ өглөг', 'Personal Income Tax (PIT) Payable', 'liability', 78, TRUE, 'Прогрессив: 10/15/20%', 'MNT', 'Пассив', FALSE, 0),
  (80, '331002', 'ААНБОАТ өглөг', 'Corporate Income Tax Payable', 'liability', 78, TRUE, '10% — тайлант жилийн татвар', 'MNT', 'Пассив', FALSE, 0),
  (81, '332000', 'Шууд бус татвар', 'Indirect Tax Payables', 'liability', 77, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (82, '332001', 'НӨАТ өглөг (тооцоолсон)', 'Output VAT Payable', 'liability', 81, TRUE, '10% — борлуулалтын НӨАТ', 'MNT', 'Пассив', FALSE, 0),
  (83, '332002', 'Бусад татварын өглөг', 'Other Tax Payable', 'liability', 81, TRUE, 'Газрын төлбөр гэх мэт', 'MNT', 'Пассив', FALSE, 0),
  (84, '340000', 'Холбоотой байгуулагын өглөг', 'Intercompany AP', 'liability', NULL, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (85, '341000', 'Компани хоорондын тооцоо', 'Related Party Payables', 'liability', 84, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (86, '341001', 'Түмэн Ресурс ХХК — өглөг', 'Tumen Resource LLC — Payable', 'liability', 85, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (87, '341002', 'Түмэн Тээх Сити ХХК — өглөг', 'TT City LLC — Payable', 'liability', 85, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (88, '341003', 'Түмэн Ресурс Технологи ХХК — өглөг', 'TRT LLC — Payable', 'liability', 85, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (89, '350000', 'Бусад богино хугацаат өр', 'Other Current Liab.', 'liability', NULL, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (90, '351000', 'Урьдчилгаа хүлээн авсан', 'Advance Received', 'liability', 89, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (91, '351001', 'Захиалагчаас урьдчилгаа', 'Customer Advance', 'liability', 90, TRUE, 'Үйлчилгээ үзүүлэхээс өмнө', 'MNT', 'Пассив', FALSE, 0),
  (92, '352000', 'Богино хугацаат зээл', 'Short-term Borrowings', 'liability', 89, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (93, '352001', 'Холбоотой байгуулагаас авсан зээл', 'Intercompany Loan Payable', 'liability', 92, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (94, '410000', 'Дүрмийн сан', 'Registered Capital', 'equity', NULL, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (95, '411000', 'Дүрмийн сан', 'Registered Capital', 'equity', 94, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (96, '411001', 'Эздийн хувь оруулалт', 'Owners'' Contribution', 'equity', 95, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (97, '430000', 'Хуримтлагдсан ашиг', 'Retained Earnings', 'equity', NULL, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (98, '431000', 'Хуримтлагдсан ашиг', 'Retained Earnings', 'equity', 97, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (99, '431001', 'Өмнөх оны хуримтлагдсан ашиг', 'Prior Year Retained Earnings', 'equity', 98, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (100, '431002', 'Тайлант оны цэвэр ашиг / алдагдал', 'Current Year Net Income / Loss', 'equity', 98, TRUE, 'Жилийн эцэст хааж шилжүүлнэ', 'MNT', 'Пассив', FALSE, 0),
  (101, '610000', 'Тээврийн үйлчилгээний орлого', 'Transport Revenue', 'income', NULL, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (102, '611000', 'Тусгай зориулалтын тээвэр', 'Dedicated / Shuttle Transport', 'income', 101, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (103, '611001', 'Ажилчдын тээвэр (shift bus)', 'Employee Shuttle Revenue', 'income', 102, TRUE, 'Корпорат гэрээт тээвэр', 'MNT', 'Пассив', FALSE, 0),
  (104, '611002', 'Корпорат тээвэр (гэрээт)', 'Corporate Contract Revenue', 'income', 102, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (105, '611003', 'VIP / тусгай тээвэр', 'VIP & Special Transport', 'income', 102, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (106, '612000', 'Ачааны тээвэр', 'Freight Transport', 'income', 101, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (107, '612001', 'Дотоод ачааны тээвэр', 'Domestic Freight Revenue', 'income', 106, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (108, '612002', 'Олон улсын ачааны тээвэр', 'International Freight Revenue', 'income', 106, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (109, '613000', 'Зорчигч тээвэр', 'Passenger Transport', 'income', 101, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (110, '613001', 'Маршрут тээвэр', 'Route Transport Revenue', 'income', 109, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (111, '613002', 'Яаралтай тээвэр', 'Express Transport Revenue', 'income', 109, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (112, '690000', '69 бүлэг', NULL, 'income', NULL, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (113, '691000', 'Санхүүгийн болон бусад орлого', 'Other Operating Income', 'income', 112, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (114, '691001', 'Торгууль, алданги хүлээн авсан', 'Penalty & Late Fee Income', 'income', 113, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (115, '691002', 'Тоног төхөөрөмж түрээслүүлсний орлого', 'Equipment Rental Income', 'income', 113, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (116, '691003', 'Ханшийн зөрүүний ашиг', 'FX Gain', 'income', 113, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (117, '691004', 'Бусад үйл ажиллагааны орлого', 'Other Operating Income', 'income', 113, TRUE, NULL, 'MNT', 'Пассив', FALSE, 0),
  (118, '710000', 'ББӨ — Тээврийн шууд зардал', 'COS', 'expense', NULL, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (119, '711000', 'Жолооч, хөдөлмөрийн зардал', 'Driver & Labour Costs', 'expense', 118, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (120, '711001', 'Гэрээт жолоочийн хөлс — тухайн сар', 'Contracted Driver Fee — Current Month', 'expense', 119, TRUE, 'Гол ББӨ данс — км эсвэл сар тооцоо | ББӨ (Шууд) · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (121, '711002', 'Гэрээт жолоочийн хөлс — өмнөх сар тооцоо', 'Contracted Driver Fee — Prior Month Adj.', 'expense', 119, TRUE, 'Тооцоо нийлэх дарааллын зөрүү | ББӨ (Шууд) · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (122, '711003', 'Туслах жолоочийн хөлс', 'Assistant Driver Fee', 'expense', 119, TRUE, 'ББӨ (Шууд) · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (123, '711004', 'Диспетчерийн хөлс (тээвэртэй шууд)', 'Dispatcher Fee (Direct)', 'expense', 119, TRUE, 'Зөвхөн шууд үйл ажиллагаатай холбоотой | ББӨ (Шууд) · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (124, '712000', 'Тээврийн хэрэгслийн зардал', 'Vehicle Operating Costs', 'expense', 118, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (125, '712001', 'GPS / телематик хяналтын зардал', 'GPS / Telematics Tracking Cost', 'expense', 124, TRUE, 'RFID, хяналтын систем | ББӨ (Шууд) · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (126, '712002', 'Каск даатгал (тээврийн хэрэгсэл)', 'Vehicle Comprehensive Insurance', 'expense', 124, TRUE, 'Гэрээт тээврийн хэрэгслийн даатгал | ББӨ (Шууд) · МУСГАА 4 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (127, '712003', 'Авто зам хураамж, гарцны төлбөр', 'Toll & Road Fee', 'expense', 124, TRUE, 'ББӨ (Шууд) · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (128, '712004', 'Тусгай зөвшөөрлийн зардал', 'Operating Permit / License Fee', 'expense', 124, TRUE, 'Жилийн тусгай зөвшөөрлийн хураамж | ББӨ (Шууд) · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (129, '712005', 'Машины угаалга, цэвэрлэгээ', 'Vehicle Cleaning & Washing', 'expense', 124, TRUE, 'ББӨ (Шууд) · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (130, '713000', 'Шатахууны зардал', 'Fuel Costs', 'expense', 118, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (131, '713001', 'Шатахуун — дизель', 'Fuel — Diesel', 'expense', 130, TRUE, 'Өмчлөлтэй тээврийн хэрэгсэлд | ББӨ (Шууд) · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (132, '713002', 'Шатахуун — бензин', 'Fuel — Petrol', 'expense', 130, TRUE, 'ББӨ (Шууд) · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (133, '713003', 'Шатахуун — хий (LPG/CNG)', 'Fuel — Gas (LPG/CNG)', 'expense', 130, TRUE, 'ББӨ (Шууд) · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (134, '714000', 'Засвар үйлчилгээ (тээврийн хэрэгсэл)', 'Vehicle Maintenance & Repair', 'expense', 118, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (135, '714001', 'ТО / урьдчилсан засвар', 'Scheduled Maintenance (ТО)', 'expense', 134, TRUE, '10,000-30,000 км тутам | ББӨ (Шууд) · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (136, '714002', 'Гэмтэл засвар', 'Breakdown Repair', 'expense', 134, TRUE, 'ББӨ (Шууд) · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (137, '714003', 'Дугуй, тоноглолын солилт', 'Tyre & Parts Replacement', 'expense', 134, TRUE, 'ББӨ (Шууд) · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (138, '720000', 'Цалин, НДШ, Түрээс', 'Payroll, NI, Rent', 'expense', NULL, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (139, '721000', 'Цалин — ажилтнаар', 'Salaries by Role', 'expense', 138, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (140, '721001', 'Захиралын цалин', 'Executive / Director Salary', 'expense', 139, TRUE, 'Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (141, '721002', 'Нягтлан бодогчийн цалин', 'Accounting Staff Salary', 'expense', 139, TRUE, 'Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (142, '721003', 'Логистик / диспетчерийн цалин', 'Logistics & Dispatch Salary', 'expense', 139, TRUE, 'Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (143, '721004', 'Борлуулалт, маркетингийн цалин', 'Sales & Marketing Salary', 'expense', 139, TRUE, 'Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (144, '721005', 'Захиргааны ажилтнуудын цалин', 'Administrative Staff Salary', 'expense', 139, TRUE, 'Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (145, '721006', 'IT, системийн мэргэжилтний цалин', 'IT & Systems Specialist Salary', 'expense', 139, TRUE, 'Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (146, '721007', 'Нийгмийн баталгааны нэмэгдэл (ажилтан)', 'Employee Benefits & Allowances', 'expense', 139, TRUE, 'Эрүүл мэнд, унаа, хоол тэтгэмж | Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (147, '721008', 'Урамшуулал, шагнал', 'Bonus & Incentive Pay', 'expense', 139, TRUE, 'Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (148, '722000', 'Ажил олгогчийн НДШ, ЭМНДШ', 'Employer Contributions', 'expense', 138, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (149, '722001', 'НДШ — ажил олгогч (12.5%)', 'Social Insurance — Employer (12.5%)', 'expense', 148, TRUE, 'Хязгааргүй — бүх цалинд | Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (150, '722002', 'ЭМНДШ — ажил олгогч (2%)', 'Health Insurance — Employer (2%)', 'expense', 148, TRUE, 'Хязгаар: цалин ≤ 7,920,000₮ | Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (151, '723000', 'Байрны болон тоног төхөөрөмжийн түрээс', 'Property & Equipment Rent', 'expense', 138, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (152, '723001', 'Оффисын байрны түрээс', 'Office Rent', 'expense', 151, TRUE, 'Үйл ажиллагааны · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (153, '723002', 'Зогсоол, гараж түрээс', 'Parking & Garage Rent', 'expense', 151, TRUE, 'Үйл ажиллагааны · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (154, '723003', 'Агуулах түрээс', 'Warehouse Rent', 'expense', 151, TRUE, 'Үйл ажиллагааны · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (155, '723004', 'Тоног төхөөрөмж, тавилгын түрээс', 'Equipment & Furniture Lease', 'expense', 151, TRUE, 'МУСГАА 16 — Right of Use | Үйл ажиллагааны · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (156, '724000', 'Утас, интернет, шуудан', 'Phone, Internet & Mail', 'expense', 138, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (157, '724001', 'Гар утас, корпорат холболт', 'Corporate Mobile Plan', 'expense', 156, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (158, '724002', 'Интернет, өгөгдлийн холболт', 'Internet & Data', 'expense', 156, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (159, '724003', 'Тогтмол утас, факс', 'Landline & Fax', 'expense', 156, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (160, '724004', 'Шуудан, курьерийн зардал', 'Postage & Courier', 'expense', 156, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (161, '725000', 'Дотоод болон гадаад томилолт', 'Domestic & International Travel', 'expense', 138, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (162, '725001', 'Дотоод томилолт — унааны зардал', 'Domestic Travel — Transport', 'expense', 161, TRUE, 'Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (163, '725002', 'Дотоод томилолт — хоол, байрны зардал', 'Domestic Travel — Accommodation', 'expense', 161, TRUE, 'Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (164, '725003', 'Гадаад томилолт — нислэгийн тасалбар', 'International Travel — Flights', 'expense', 161, TRUE, 'Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (165, '725004', 'Гадаад томилолт — виз, байр', 'International Travel — Visa & Hotel', 'expense', 161, TRUE, 'Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (166, '726000', 'Тоног төхөөрөмж, барилгын засвар', 'Equipment & Building Repair', 'expense', 138, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (167, '726001', 'Оффисын тоног төхөөрөмжийн засвар', 'Office Equipment Repair', 'expense', 166, TRUE, 'Үйл ажиллагааны · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (168, '726002', 'Компьютер, серверийн засвар', 'Computer & Server Repair', 'expense', 166, TRUE, 'Үйл ажиллагааны · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (169, '726003', 'Барилга, байгууламжийн засвар', 'Building & Premises Repair', 'expense', 166, TRUE, 'Үйл ажиллагааны · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (170, '727000', 'Аутсорс, зөвлөх үйлчилгээ', 'Outsourced & Advisory Services', 'expense', 138, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (171, '727001', 'Аудит, нягтлан бодох үйлчилгээ', 'Audit & Accounting Service', 'expense', 170, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (172, '727002', 'Хуулийн зөвлөх үйлчилгээ', 'Legal Advisory Service', 'expense', 170, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (173, '727003', 'Санхүүгийн зөвлөх үйлчилгээ', 'Financial Advisory Service', 'expense', 170, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (174, '727004', 'IT хөгжүүлэлт, нэвтрүүлэлт', 'IT Development & Implementation', 'expense', 170, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (175, '727005', 'Сургалт, хөгжлийн зардал', 'Training & Development', 'expense', 170, TRUE, 'Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (176, '727006', 'Бусад мэргэжлийн үйлчилгээ', 'Other Professional Services', 'expense', 170, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (177, '728000', 'Байгууллага, ажилтны даатгал', 'Corporate & Employee Insurance', 'expense', 138, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (178, '728001', 'Байгууллагын иж бүрэн даатгал', 'Corporate All-Risk Insurance', 'expense', 177, TRUE, 'Үйл ажиллагааны · МУСГАА 4 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (179, '728002', 'Ажилтны гэнэтийн осол даатгал', 'Employee Accident Insurance', 'expense', 177, TRUE, 'Үйл ажиллагааны · МУСГАА 4 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (180, '728003', 'Хариуцлагын даатгал (3-д этгээд)', 'Third-Party Liability Insurance', 'expense', 177, TRUE, 'Үйл ажиллагааны · МУСГАА 4 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (181, '728004', 'Кибер эрсдэлийн даатгал', 'Cyber Risk Insurance', 'expense', 177, TRUE, 'Үйл ажиллагааны · МУСГАА 4 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (182, '729000', 'Шимтгэл, хүү, ханш', 'Fees, Interest & FX', 'expense', 138, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (183, '729001', 'Банкны шимтгэл — ХХБ', 'Bank Charges — Khan Bank', 'expense', 182, TRUE, 'Үйл ажиллагааны · МУСГАА 9 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (184, '729002', 'Банкны шимтгэл — Голомт', 'Bank Charges — Golomt Bank', 'expense', 182, TRUE, 'Үйл ажиллагааны · МУСГАА 9 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (185, '729003', 'Банкны шимтгэл — М банк', 'Bank Charges — M Bank', 'expense', 182, TRUE, 'Үйл ажиллагааны · МУСГАА 9 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (186, '729004', 'Зээлийн хүүгийн зардал', 'Loan Interest Expense', 'expense', 182, TRUE, 'Санхүүгийн · МУСГАА 23 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (187, '729005', 'Ханшийн зөрүүний алдагдал', 'FX Loss', 'expense', 182, TRUE, 'Санхүүгийн · МУСГАА 21 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (188, '730000', 'Бусад зардал', 'Other Expenses', 'expense', NULL, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (189, '730001', 'Зар сурталчилгаа (онлайн)', 'Online Advertising', 'expense', 188, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (190, '730002', 'Зар сурталчилгаа (хэвлэл, радио)', 'Print & Radio Advertising', 'expense', 188, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (191, '730003', 'Бренд, дизайн зардал', 'Branding & Design', 'expense', 188, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (192, '730004', 'Үйлчлүүлэгч татах хөтөлбөр', 'Customer Acquisition Program', 'expense', 188, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (193, '730005', 'Арга хэмжээ, үзэсгэлэн', 'Events & Exhibitions', 'expense', 188, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (194, '731000', 'Ажилтны сайн сайхны зардал', 'Employee Welfare Costs', 'expense', 188, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (195, '731001', 'Сонгон шалгаруулалтын зардал', 'Recruitment Cost', 'expense', 194, TRUE, 'Зар, ярилцлага, шалгалт | Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (196, '731002', 'Ажилтны хоол, унааны тэтгэмж', 'Meal & Transport Allowance', 'expense', 194, TRUE, 'Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (197, '731003', 'Ажилтны эрүүл мэндийн зардал', 'Employee Medical Expense', 'expense', 194, TRUE, 'Эмчлүүлэлт, эрүүл мэндийн шалгалт | Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (198, '731004', 'Бусад ажилтны тэтгэмж', 'Other Employee Benefits', 'expense', 194, TRUE, 'Үйл ажиллагааны · МУСГАА 19 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (199, '732000', 'Оффисын болон бусад хэрэглэл', 'Office & General Supplies', 'expense', 188, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (200, '732001', 'Оффисын цаас, бичгийн хэрэгсэл', 'Office Stationery & Paper', 'expense', 199, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (201, '732002', 'Принтерийн хэрэглэл, тонер', 'Printer Supplies & Toner', 'expense', 199, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (202, '732003', 'Цэвэрлэгээний хэрэглэл', 'Cleaning Supplies', 'expense', 199, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (203, '732004', 'Бусад хангамжийн материал', 'Other Supplies', 'expense', 199, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (204, '733000', 'Үндсэн болон биет бус хөрөнгийн элэгдэл', 'Fixed & Intangible Asset D&A', 'expense', 188, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (205, '733001', 'Тавилга, эд хогшлын элэгдэл', 'Furniture & Fixtures Depreciation', 'expense', 204, TRUE, 'Шугаман арга, 5 жил | Үйл ажиллагааны · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (206, '733002', 'Компьютер, техник хэрэгслийн элэгдэл', 'Computer & Equipment Depreciation', 'expense', 204, TRUE, 'Шугаман арга, 3 жил | Үйл ажиллагааны · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (207, '733003', 'Оффисын тоног төхөөрөмжийн элэгдэл', 'Office Equipment Depreciation', 'expense', 204, TRUE, 'Шугаман арга, 5 жил | Үйл ажиллагааны · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (208, '733004', 'Тээврийн хэрэгслийн элэгдэл', 'Vehicle Depreciation', 'expense', 204, TRUE, 'Шугаман арга, 5-10 жил | Үйл ажиллагааны · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (209, '733005', 'Бусад үндсэн хөрөнгийн элэгдэл', 'Other Fixed Asset Depreciation', 'expense', 204, TRUE, 'Үйл ажиллагааны · МУСГАА 16 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (210, '733006', 'Програм хангамжийн элэгдэл (биет бус)', 'Software Amortization', 'expense', 204, TRUE, 'Шугаман арга, 3 жил | Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (211, '739000', 'Бусад үйл ажиллагааны зардал', 'Other Operating Costs', 'expense', 188, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (212, '739001', 'Хандив, ивээн тэтгэлт', 'Donations & Sponsorship', 'expense', 211, TRUE, 'Татварт хасагдахгүй (ААНБОАТ) | Үйл ажиллагааны · МУСГАА 38 · татвар: Үгүй — татварт хасагдахгүй', 'MNT', 'Актив', FALSE, 0),
  (213, '739002', 'Торгууль, алдангийн зардал', 'Penalty & Late Payment Charges', 'expense', 211, TRUE, 'Татварт хасагдахгүй | Үйл ажиллагааны · МУСГАА 38 · татвар: Үгүй — татварт хасагдахгүй', 'MNT', 'Актив', FALSE, 0),
  (214, '739003', 'Бусад үйл ажиллагааны зардал', 'Other Operating Expenses', 'expense', 211, TRUE, 'Үйл ажиллагааны · МУСГАА 38 · татвар: Тийм', 'MNT', 'Актив', FALSE, 0),
  (215, '810000', 'Орлогын татварын зардал', 'CIT', 'expense', NULL, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (216, '811000', 'ААНБОАТ', 'CIT — Annual', 'expense', 215, TRUE, NULL, 'MNT', 'Актив', FALSE, 0),
  (217, '811001', 'ААНБОАТ — тайлант жилийн татвар (10%)', 'CIT — Current Year Tax (10%)', 'expense', 216, TRUE, 'Монгол: 10% татварын хувь хэмжээ | Татвар · МУСГАА 12 · татвар: Татварын зардал', 'MNT', 'Актив', FALSE, 0),
  (218, '811002', 'ААНБОАТ — хойшлогдсон татвар', 'CIT — Deferred Tax', 'expense', 216, TRUE, 'МУСГАА 12 дагуу | Татвар · МУСГАА 12 · татвар: Татварын зардал', 'MNT', 'Актив', FALSE, 0);

PERFORM setval(pg_get_serial_sequence('accounts','id'),
               (SELECT MAX(id) FROM accounts));

END IF;
END $$;
