-- ============================================================
-- partners seed — хуучин accounting.db-гээс шилжүүлсэн идэвхтэй харилцагчид
-- Нийт: 931 мөр. Supabase SQL Editor-д ажиллуулна.
-- Хүснэгт хоосон үед л оруулна (дахин ажиллуулахад давхардахгүй).
-- ============================================================

DO $$
BEGIN
IF (SELECT COUNT(*) FROM partners) = 0 THEN

INSERT INTO partners (code, name, register, type, phone, email, address, aliases) VALUES
  (NULL, '"Доктор Муллер Фарма Монголиа" ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, '"Доктор Суллер Фарма Монголиа" ХХК', 'СЩ79092231', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1807', NULL),
  (NULL, '"Эрч хүч илч" ХХК', '287387', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1409', NULL),
  ('C10001-01', '155 сургууль', NULL, 'both', NULL, NULL, NULL, '["155 сургууль"]'::jsonb),
  ('C10186-01', '360 Файнанс ББСБ', NULL, 'both', NULL, NULL, NULL, '["360 Файнанс ББСБ"]'::jsonb),
  ('C10002-01', '3Btec', '6555705', 'both', '91068777', NULL, NULL, '["3Btec"]'::jsonb),
  ('C10185‑01', 'A Team LLC', NULL, 'both', NULL, NULL, NULL, '["A Team LLC"]'::jsonb),
  ('C10004-01', 'APU', '2702673', 'both', '88001876', 'Urangoo.m@apu.mn', 'Хан-Уул дүүргийн 2 дугаар хороо, Чингисийн өргөн чөлөө, АПУ ХК-ийн байр', '["Apu LLC", "Апу ХК"]'::jsonb),
  ('C10079-01', 'ATOP', '6565492', 'both', NULL, 'zayatuvshin@atop.mn', NULL, '["АТОП ХХК", "ATOP LLC"]'::jsonb),
  ('C10071-01', 'Abico', NULL, 'both', NULL, NULL, NULL, '["Abico foods", "Абико ХХК"]'::jsonb),
  ('C10073-01', 'Adsmart Network', '7046065', 'both', '99909309', NULL, 'Монгол Улс, Улаанбаатар хот 14241, Сүхбаатар дүүрэг, 1-р хороо, Олимпийн гудамж 4, Нью Хоризон оффис, 3-р давхар, 303 тоот', '["Адсмарт нэтворк ХХК"]'::jsonb),
  ('C10072-01', 'Agar United', NULL, 'both', NULL, NULL, NULL, '["Агар Юнайтед ХХК"]'::jsonb),
  ('C10218-01', 'Air Care LLC', NULL, 'both', NULL, NULL, NULL, '["Air Care LLC"]'::jsonb),
  ('C10003-01', 'Alpha Quartz', NULL, 'both', NULL, NULL, NULL, '["Alpha Quartz LLC"]'::jsonb),
  ('C10183-01', 'Arcadia Garden', NULL, 'both', NULL, NULL, NULL, '["Аркадиа Гарден ХХК", "Arcadia Garden"]'::jsonb),
  ('C10089-01', 'BSB', '5381894', 'both', '85257611', 'tsend-ayush.b@bsb.mn', NULL, '["БСБ Электроникс ХХК"]'::jsonb),
  ('C10010-01', 'BT Distribution', '6892183', 'both', '95909432', 'Import@globalnegdel.mn', 'Монгол, Улаанбаатар, Баянгол, 4-р хороо, , Юу Би Платинум төв 504 тоот', '["BT Distribution LLC", "БТ Дистрибьюшн ХХК"]'::jsonb),
  (NULL, 'Baatar bond baritsaa/2', NULL, 'both', NULL, NULL, 'Тауэр M2, Өрөө 1303', NULL),
  (NULL, 'Baatar bond baritsaa/3', NULL, 'both', NULL, NULL, 'Тауэр M2, Өрөө 1304', NULL),
  (NULL, 'Badalahu', 'EJ2977823', 'both', NULL, NULL, 'Тауэр M3, Өрөө 405', NULL),
  ('C10080-01', 'Barloworld Mongolia', NULL, 'both', NULL, NULL, NULL, '["Barlo world LLC", "Барловорлд Монголиа"]'::jsonb),
  ('C10007-01', 'Best Force', '6761879', 'both', NULL, NULL, 'Монгол, Улаанбаатар, Баянгол, 15-р хороо, энэбишийн гудамж, байр 128 тоот', '["BEST Force llc"]'::jsonb),
  ('C10008-01', 'Bluefin', '5695635', 'both', '99997878', NULL, 'Монгол, Улаанбаатар, Баянзүрх, 14-р хороо, , Баясах трейд ххк-н байр,201 тоот', '["БЛҮФИН КАТЕРИНГ ХХК", "Bluefin LLC"]'::jsonb),
  ('C10009-01', 'Bodi', '2040433', 'both', NULL, 'odmaa.g@bodigroup.mn', 'Park Place Office 3rd Floor, Chinggis Khaan Avenue - 24, Ulaanbaatar 14241, MN', '["Bodi International"]'::jsonb),
  ('C10011-01', 'Changhang Logistics', NULL, 'both', NULL, NULL, NULL, '["Changhang Logistics"]'::jsonb),
  ('C10012-01', 'Cosmic rays', NULL, 'both', NULL, NULL, NULL, '["Cosmic rays"]'::jsonb),
  ('C10014-01', 'DRE LLC', NULL, 'both', NULL, NULL, NULL, '["DRE LLC"]'::jsonb),
  (NULL, 'Diesel truck tools LLC', NULL, 'customer', NULL, NULL, NULL, NULL),
  ('C10113-01', 'EES', NULL, 'both', NULL, NULL, NULL, '["И И эс ххк", "И И Эс ХХК"]'::jsonb),
  ('C10015-01', 'Eco Gumin', '7055793', 'both', NULL, NULL, NULL, '["Eco Gumin LLC"]'::jsonb),
  ('C10178-01', 'Electro Complect', '2747081', 'both', NULL, NULL, NULL, '["ELECTROCOMPLECT LLC", "Электрокомплект ХХК", "ЭЛЕКТРОКОМПЛЕКТ"]'::jsonb),
  ('C10017-01', 'Everest Mizar', '8398615', 'both', '89502233', 'EMAA1441@GMAIL.COM', NULL, '["Everest MIzar LLC"]'::jsonb),
  ('C10018-01', 'FLSMIDTH', '5523028', 'both', '99828281', 'Enkhtsetseg.Sukhbaatar@flsmidth.com', 'Улаанбаатар, Сүхбаатар, 1-р хороо, Блюскай Товер 4давхар 402 тоот', '["FLS", "ФЛСМИДТ МОНГОЛИА ХХК"]'::jsonb),
  ('C10019-01', 'Global Electronics', NULL, 'both', NULL, NULL, NULL, '["Global Electronics LLC"]'::jsonb),
  ('C10020-01', 'Global Smart Solution', '5933579', 'both', '95909432', 'Import@globalnegdel.mn', NULL, '["Глобал Смарт Сольюшн ХХК", "Global Smart Solution LLC"]'::jsonb),
  ('C10021-01', 'Grand Good Express', NULL, 'both', NULL, NULL, NULL, '["Grandgoodsexpress LLC", "Гранд Гүүд Экспресс ХХК"]'::jsonb),
  ('C10096-01', 'Grand mining equipment', '6370888', 'both', '95900107', 'info@grandmining.mn', NULL, '["Гранд майнинг экюпмент ХХК", "Гранд майнинг ХХК"]'::jsonb),
  ('C10122-01', 'Green Gate International LLC', NULL, 'both', NULL, NULL, NULL, '["Green Gate International LLC"]'::jsonb),
  ('C10118-01', 'Ink Color', NULL, 'both', NULL, NULL, NULL, '["Инкколор ХХК", "Инкколор ХХК/Inkcolor LLC"]'::jsonb),
  ('C10188-01', 'Interasia Energy', NULL, 'both', NULL, NULL, NULL, '["interasia energy LLC"]'::jsonb),
  ('C10022-01', 'Intermed', '5387051', 'both', '80080127', 'khishigbayar.t@intermed.mn', NULL, '["Интермед эмнэлэг", "Intermed"]'::jsonb),
  ('C10023-01', 'Intersource', NULL, 'both', NULL, NULL, NULL, '["intersource inc"]'::jsonb),
  (NULL, 'JENMOUR NEW ENERGY LLC', NULL, 'customer', NULL, NULL, NULL, NULL),
  ('C10024-01', 'Jurmak', NULL, 'both', NULL, NULL, NULL, '["Jurmak LLC"]'::jsonb),
  ('C10025-01', 'Khaanza', '6092233', 'both', '99036907', 'anar@khs.mn', NULL, '["Khaanza Service LLC", "Хаанзаа сервис ХХК"]'::jsonb),
  ('C10027-01', 'LOGA', NULL, 'both', NULL, NULL, NULL, '["Loga international", "Лога интернэшнл ХХК"]'::jsonb),
  ('C10028-01', 'Loropiano', NULL, 'both', NULL, NULL, NULL, '["Loropiana LLC"]'::jsonb),
  ('C10029-01', 'Lyon partner', '8413711', 'both', '88106381', NULL, 'Улаанбаатар , СБД, 1-р хороо, SAV PLAZA ,1603тоот', '["Lyon partner alliance llc", "Лаёон Партнер аллаёонс ХХК"]'::jsonb),
  (NULL, 'M БАНК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'MAK Aranjin Zes CO.,ltd', NULL, 'customer', NULL, NULL, NULL, NULL),
  ('C10033-02', 'MCS CocaCola', '2663503', 'both', '89112384', 'Baasanjargal.a@mcscocacola.mn', NULL, '["М-Си-Эс Кока-кола ХХК"]'::jsonb),
  ('C10033-01', 'MCS International', '2090007', 'both', '88099759', 'otgontuul.g@mcsi.mn', 'Сүхбаатар дүүрэг 1-р хороо, Олимпийн гудамж 19А, Шангри-Ла оффис, 7 давхар 704 тоот, Улаанбаатар-14241 Монгол улс', '["М-Си-Эс-Интернейшнл ХХК", "М-Си-Эс-Интернэйшнл ХХК", "М-Си-Эс-Интернэйшнл ХХК_Ts", "MCS International", "М-Си-Эс-Интернэйшнл ХХК..", "М-Си-Эс-Интернейшнл ХХК..", "М-Си-Эс-Интернэйшнл ХХК..."]'::jsonb),
  ('C10189-01', 'MSM Group', NULL, 'both', NULL, NULL, NULL, '["MSM Груп ХХК"]'::jsonb),
  ('C10030-01', 'Major Drilling', '2704358', 'both', '99115005', 'boldo.tulga@majordrilling.com', 'Mongolia Building Workers street, Khoroo 3 Khan-Uul D , Ulaanbaatar', '["Major drilling mongolia llc", "Major Drilling LLC"]'::jsonb),
  ('C10125-01', 'Mandal Resource', NULL, 'both', NULL, NULL, NULL, '["Мандал ресурс ХХК.", "Мандал ресурс ХХК"]'::jsonb),
  ('C10032-01', 'Master Foods', '6446876', 'both', '89799944', 'procurement2@masterfoo
  ds.mn', NULL, '["Мастер фүүдс ХХК", "Master foods", "МАСТЕР ФҮҮДС ХХК"]'::jsonb),
  ('C10032-05', 'Max clean energy LLC', NULL, 'both', NULL, NULL, NULL, '["Max clean energy LLC"]'::jsonb),
  ('C10032-07', 'Max machinery industry LLC', NULL, 'both', NULL, NULL, NULL, '["Max machinery industry LLC"]'::jsonb),
  (NULL, 'Maxmining LLC', NULL, 'customer', NULL, NULL, NULL, NULL),
  (NULL, 'Medicont LLC', '5417627', 'customer', '91224512', NULL, NULL, NULL),
  ('C10036-01', 'Monlogistic', NULL, 'both', NULL, NULL, NULL, '["Monlogistics Worldwide LLC", "Monlogistic worldwide LLC"]'::jsonb),
  ('C10038-01', 'Murray Mining Services LLC', '6303102', 'both', '95029016', 'Luvsanravdan.tsolmonkhuu@murrays.mn', 'Khan Uul District, 15th Sub District
  Mahatma Gandhi Street, Galaxy Tower, Level 8 #802', '["MURRAY MINING SERVICES LLC", "МАРРИЙ МАЙНИНГ СЕРВИСЕС ХХК", "Murray Mining Services", "Маррий Майнинг Сервисес ХХК", "Маррий Майнинг сервисес"]'::jsonb),
  ('C10044-01', 'NMM', NULL, 'both', NULL, NULL, NULL, '["NMM LLC"]'::jsonb),
  ('C10039-01', 'Navigator Sealand', NULL, 'both', NULL, NULL, NULL, '["Navigator Sealand"]'::jsonb),
  ('C10041-01', 'New Bogat', '5609224', 'both', '99040340', NULL, NULL, '["NEW BOGAT LLC", "New Bogat"]'::jsonb),
  ('C10042-01', 'New Pound', NULL, 'both', NULL, NULL, NULL, '["Нью Фунт ХХК", "New pound LLC"]'::jsonb),
  ('C10043-01', 'Next', NULL, 'both', NULL, NULL, NULL, '["Next LLC", "Нэкст логистикс ХХК"]'::jsonb),
  ('C10190-01', 'Nomex', NULL, 'both', NULL, NULL, NULL, '["NOMEX LLC"]'::jsonb),
  (NULL, 'Nomin LLC', '2708892', 'customer', '89888611', NULL, NULL, NULL),
  (NULL, 'Pick Pack', NULL, 'customer', '88830163', NULL, 'Монгол улс, Улаанбаатар хот,
СБД, 1-р хороо, Чингисийн өргөн чөлөө,
Централ Парк, 14 давхар', NULL),
  ('C10049-02', 'Premium Concrete', '5528534', 'both', '88108320', 'zoljargal.b@premiumconcrete.mn', '23-р давхар, Шангри-Ла төв, 19A-C, Олимпийн гудамж, Сүхбаатар дүүрэг 1, Улаанбаатар хот 14241', '["Premium concrete LLC"]'::jsonb),
  ('C10192-01', 'RGLT', NULL, 'both', NULL, NULL, NULL, '["Ар Жи Эл Ти ХХК"]'::jsonb),
  ('C10052-01', 'SAADE', '5356083', 'both', '88021351', 'enkhtuul@saadegroup.mn', 'УБ, БЗД, 25-р хороо, ЮуБи тауэр 204 тоот', '["Saade constraction LLC", "Saade group LLC", "СААДИКОНСТРАКШН"]'::jsonb),
  ('C10053-01', 'SB Virgo', NULL, 'both', NULL, NULL, NULL, '["SB Virgo"]'::jsonb),
  ('C10056-01', 'SSPRITOJ', '8355649', 'both', NULL, NULL, NULL, '["SSPRITOJ LLC"]'::jsonb),
  (NULL, 'Shuugee LLC', '6577954', 'customer', NULL, NULL, 'Улаанбаатар  хот', NULL),
  ('C10013-01', 'Sky park plaza', NULL, 'both', NULL, NULL, NULL, '["Cкай парк плаза ХХК", "Cкай парк плаз ХХК"]'::jsonb),
  ('C10055-01', 'Sonoforte', NULL, 'both', NULL, NULL, NULL, '["Sonofort LLC", "Сонофортегрупп ХХК"]'::jsonb),
  ('C10057-01', 'Steadfastmongolia', NULL, 'both', NULL, NULL, NULL, '["Steadfastmongolia contruction LLC"]'::jsonb),
  ('C10058-01', 'Suns New Touch', NULL, 'both', NULL, NULL, NULL, '["Санс нью тоуч мэдикал ХХК", "Suns New Touch Medical LLC"]'::jsonb),
  (NULL, 'TO systems LLC', '2704781', 'customer', '99034404', NULL, 'ЧД, 18-р хороо, Яргайтын 22-р гудамж 342тоот', NULL),
  ('C10061-01', 'Transhydraulic', NULL, 'both', NULL, NULL, NULL, '["Transhydraulic", "Транс Хидроулик XXK"]'::jsonb),
  ('C10062-01', 'Tsenguun Khishig Trade', NULL, 'both', NULL, NULL, NULL, '["Tsenguun Khishig Trade LLC", "Tsenguun Khishig LLC"]'::jsonb),
  ('C10063-01', 'UBZB', '6436854', 'both', '97070766', 'munkhzaya.p@ubhotel.mn', NULL, '["UBZB LLC"]'::jsonb),
  ('C10064-01', 'ULE', '5182018', 'both', '99900801', 'Nyambayar.b@ule.mn', 'Baruun Turuun 56, A0301 Road, khoroo 32, Songinokhairkhan District, Ulaanbaatar, Mongolia', '["ULE LLC", "ULE LLC."]'::jsonb),
  ('C10175-01', 'UMS', '5166829', 'both', '99170783', 'enkhmaa.s@premiumconcrete.mn', NULL, '["UMS 5166829", "Юу Эм Эс ХХК", "UMS LLC"]'::jsonb),
  ('C10067-01', 'Unity Data', NULL, 'both', NULL, NULL, NULL, '["Unity Data Technology LLC"]'::jsonb),
  (NULL, 'XUE JIAN SI', 'ЮД78010614', 'both', NULL, NULL, 'Тауэр M3, Өрөө 707', NULL),
  ('C10191-01', 'Xinjian BJSL', NULL, 'both', '15188322131', 'sunyawen@xjbjsl.com', '3001, Unit 1, Building 3, Zhongnan Shanguye City, No 555 Changsha Road, Xinshi District, Urumqi, Xinjiang', '["Xinjiang BJSL"]'::jsonb),
  (NULL, 'Xinjiang BJSL', NULL, 'customer', '15188322131', NULL, '3001, Unit 1, Building 3, Zhongnan Shanguye City, No 555 Changsha Road, Xinshi District, Urumqi, Xinjiang', NULL),
  ('C10069-01', 'ZME', '5106842', 'both', '75058888', 'purevdorj.b@zme.mn', 'Оффис Блок#36В Манлайбаатар Дамдинсүрэнгийн гудамж, 18-р хороо Баянзүрх дүүрэг, Улаанбаатар, Монгол улс 13372', '["ZME LLC", "Зэт Эм И ХХК.", "Зэт Эм И ХХК", "ЗЭТ ЭМ И ХХК"]'::jsonb),
  (NULL, 'ubcapital baritsaa/2', NULL, 'both', NULL, NULL, 'Тауэр M2, Өрөө 1305', NULL),
  (NULL, 'ubcapital baritsaa/3', NULL, 'both', NULL, NULL, 'Тауэр M2, Өрөө 1306', NULL),
  (NULL, 'ЁНДОНЖАМЦ ПҮРЭВДОРЖ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'А нэг ХХК', '5534348', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1101 1110', NULL),
  (NULL, 'А.Күлдик', 'ЦД60052006', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'А.Намуунгоо', 'ВЮ01282600', 'both', NULL, NULL, 'Тауэр M3, Өрөө 806', NULL),
  (NULL, 'А.Наранзул', 'ХЛ67033105', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1408', NULL),
  (NULL, 'А.Сувд-Эрдэнэ', 'ЗЮ76100500', 'both', NULL, NULL, 'Тауэр M3, Өрөө 902', NULL),
  (NULL, 'А.Халиунаа', 'ТА9512141', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1602', NULL),
  (NULL, 'АБИКО фүүдс', '8457751', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'АВГААНДАШ БҮРЭН-ЭРДЭНЭ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'АВИРМЭД МӨНХБАТ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'АЕ ЛОЖИСТИК ГРУПП', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'АЙТҮҮЛС ХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'АЛТАНГЭРЭЛ АСЕМБОЛ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'АЛТАНГЭРЭЛ ГОМБОДОРЖ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'АЛТАНГЭРЭЛ СОДНОМПИЛ', '111680621956', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'АЛТАНХУЯГ ҮҮРИЙНЦОЛМОН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'АЛТГАНА РЕСУРСЕС ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'АМАРЖАРГАЛ БАЯРМАГНАЙ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'АМГАЛАН БАТЗОРИГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'АНАР ИНФИНИТИ СТЕП ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'АНУ ЭМҮ ГОО', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'АНХБАЯР НАСАНЖАРГАЛ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'АНХБАЯР ЭНХБОЛД', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'АПУ ТРЕЙДИНГ ХХК', '5105935', 'customer', '89836623', NULL, NULL, NULL),
  ('C10004-02', 'АПУ дэйри', '6229654', 'both', NULL, NULL, 'Улаанбаатар хот, Сүхбаатар дүүрэг 1 хороо, Чингисийн өргөн чөлөө 33/5', '["АПУ ДЭЙРИ", "Апу дэйри ХХК", "Апу дэйри", "АПУ ДЭЙРИ ХХК"]'::jsonb),
  (NULL, 'АРВИН ЭНХ ӨСӨХ ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'АРКИЛЕКТ ТРЭЙД ХХК', NULL, 'customer', NULL, NULL, NULL, NULL),
  (NULL, 'АРЦХҮҮ МӨНХ-ЭРДЭНЭ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'АСЛАНХҮҮ ХОСБАЯР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'АСФАЛЬТ БИТУМ ХХК', '7170313', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1810', NULL),
  (NULL, 'Абико ХХК', '5338131', 'customer', '99904283', NULL, 'ХУД, 3-р хороо, 22-р байшин Магнолиа оффис 5 давхарт', NULL),
  (NULL, 'Агар энержи ХХК', NULL, 'customer', NULL, NULL, NULL, NULL),
  (NULL, 'Азда трейдинг ХХК', '3803503', 'customer', NULL, NULL, 'Улаанбаатар  хот', NULL),
  (NULL, 'Азийн их хүлэг', '2837765', 'both', NULL, '1232@123', NULL, NULL),
  (NULL, 'Азтай элсэн чимээ ХХК', 'ЙС75022208', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Ай Жи Ти Си', '6216579', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Акалико монголиа ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Акарү ХХК', '2860341', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1805', NULL),
  (NULL, 'Алтай Хянган Хайрхан Транс ХХК', '6234038', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Алтай эколос ХХК', '6411851', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Алтан гялбаа од', '5686938', 'supplier', NULL, NULL, NULL, NULL),
  ('C10032-03', 'Алтгана Ресурс', NULL, 'both', NULL, NULL, NULL, '["Алтгана ресурс ХХК"]'::jsonb),
  (NULL, 'Альфа Илч ХХК', '6835619', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  ('C10217-01', 'Амарвишн ХХК', NULL, 'both', NULL, NULL, NULL, '["Amarvision LLC", "Амарвишн ХХК", "АМАРВИШН ХХК", "АМАРВИШН"]'::jsonb),
  (NULL, 'Амарок Ти Эс Ти ХХК', '6554024', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1101', NULL),
  (NULL, 'Амина, Хатанбаатар', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Аминзендеги ХХК', '6427243', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1503', NULL),
  (NULL, 'Амуулай ХХК', '2715953', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1801-1805', NULL),
  (NULL, 'Анагай ХХК Ж.Мөнхбат', '6200281', 'both', NULL, NULL, 'Тауэр M3, Өрөө 701', NULL),
  (NULL, 'Ант продакшн', '6974074', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Антифаер', '5744016', 'supplier', NULL, NULL, NULL, NULL),
  ('C10076-01', 'Ануурад Дриллинг', NULL, 'both', NULL, NULL, NULL, '["Ануурад дриллинг ХХК"]'::jsonb),
  (NULL, 'Ар Жи Эл Ти ХХК', '4283562', 'customer', '99726827', NULL, 'Дархан-Уул, Дархан, 17-р баг, Өргөө баг, 21 хороолол, 7а, 16', NULL),
  (NULL, 'Ардирон ХХК', '5715639', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1809', NULL),
  (NULL, 'Арж капитал ХХК', '2810301', 'customer', '88121595', NULL, 'УБ, Чингэлтэй дүүрэг, 5-р хороо, Самбуугийн гудамж-24, М-Плаза, 5 давхар', NULL),
  (NULL, 'Ариунзаяа', 'УД90062822', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1009', NULL),
  (NULL, 'Аркадиа Гарден ХХК', '6429289', 'customer', '88886018', NULL, '23-р давхар, Шангри-Ла төв, 19A-C, Олимпийн гудамж, Сүхбаатар дүүрэг 1, Улаанбаатар хот 14241', NULL),
  ('C10077-01', 'Аркилект трейд', '7161785', 'both', '99706089', 'zula89@gmail.com', 'Хан-Уул дүүрэг 18-хороо, Их Монгол гудамж Хүннү 2222 хотхон 105 байр, Улаанбаатар хот', '["Аркилект трэйд ХХК"]'::jsonb),
  (NULL, 'Аск Сийк Нок ХХК', '6880037', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1509', NULL),
  (NULL, 'Асралт Шахъяа ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Астериск Техноложис ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  ('C10005-01', 'Атар Ирээдүй', '2291509', 'both', '99286327', 'atarireedui@gmail.com', 'Улаанбаатар, ХУД-2-р хороо', '["Atar-Ireedui LLC", "Atar Ireedui LLC", "Атар Ирээдүй ХХК"]'::jsonb),
  (NULL, 'Аялуун фарм ХХК', '2787172', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1401-1403', NULL),
  (NULL, 'Б.Алтангэрэл', 'УХ84012737', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1602-1603', NULL),
  (NULL, 'Б.Алтанзул', 'ИЮ90081482', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1703', NULL),
  (NULL, 'Б.Анхбаяр', 'АЭ87072304', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1408', NULL),
  (NULL, 'Б.Ариун-Эрдэнэ', '7175585', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1807', NULL),
  (NULL, 'Б.Батгэрэл', 'УШ97092737', 'both', NULL, NULL, 'Тауэр PRK, Өрөө P-021', NULL),
  (NULL, 'Б.Болормаа', 'ЕЙ82061003', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1709', NULL),
  (NULL, 'Б.Ган-Эрдэнэ', NULL, 'both', NULL, NULL, 'Тауэр M2, Өрөө 1502', NULL),
  (NULL, 'Б.Лханасүрэн', 'ЖЬ51040177', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1709', NULL),
  (NULL, 'Б.Намуунцэцэг', 'ЗП00252803', 'both', NULL, NULL, 'Тауэр M1, Өрөө 301', NULL),
  (NULL, 'Б.Одбаяр', '6359582', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1608-1609', NULL),
  (NULL, 'Б.Одбаяр/Твин Аярас ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Б.Отгонбаяр', 'УХ68072613', 'both', NULL, NULL, 'Тауэр M3, Өрөө 406', NULL),
  (NULL, 'Б.Очгэрэл', 'УШ94090883', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1202', NULL),
  (NULL, 'Б.Оюунгэрэл', 'ЙЮ74052200', 'both', NULL, NULL, 'Тауэр M3, Өрөө 903', NULL),
  (NULL, 'Б.Оюунцэцэг', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Б.Төгөлдөр', 'УШ96101432', 'both', NULL, NULL, 'Тауэр M3, Өрөө 507', NULL),
  (NULL, 'Б.Ууганбаяр', 'CЮ86081210', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1407', NULL),
  (NULL, 'Б.Халиун', '6469396', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1110', NULL),
  (NULL, 'Б.Өлзийбаяр', '7212761', 'both', NULL, NULL, 'Тауэр M3, Өрөө 907', NULL),
  (NULL, 'Б.Өлзийтэгш', 'УХ92082748', 'both', NULL, NULL, 'Тауэр M1, Өрөө 509', NULL),
  (NULL, 'БААСАНЖАВ ДҮВЧИНДОРЖ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БААТАР АЮУШ', '111668001763', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'БААТАР ДЭЛГЭРЗАЯА', '111369090035', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'БААТАРЖАВ МӨНХБААТАР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БААТАРЗОРИГТ ЭНХБААТАР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БААТАРПҮРЭВ БАТОЧИР', '111603421229', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'БААТАРЦОГТ ВАНТӨМӨР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАДРАХ БАТСҮХ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАЙГАЛ БАТ-ЕРӨӨЛ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАЙГУУЛЛАГЫН ХАРИЛЦАХЫН ХҮҮНИЙ ТАТВАРЫН ӨГЛӨГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАТ ОД ЗУЛ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАТ ПЭЛЖИР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАТ-ОРГИЛ ДАВААСАМБУУ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАТ-ЭРДЭНЭ БАЯМБАСҮРЭН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАТ-ӨЛЗИЙ НАНДИН-ЭРДЭНЭ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАТБААТАР БЯМБАНОРОВ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАТБАЯР БАТЗОРИГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАТБОЛД ГАНЦЭЦЭГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАТСАЙХАН БАТБИЛЭГ', '625273891546', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'БАТСАЙХАН ЭНХМАНДАХ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАТСУУРЬ НАМЖИЛДОРЖ', '621062381533', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'БАТСҮХ СОСОРБУРАМ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАТХИШИГ МӨНХТҮШИГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАТЦЭН ЧОТОН ХХК', NULL, 'customer', NULL, NULL, NULL, NULL),
  (NULL, 'БАТЦЭНГЭЛ НЯМДАШ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАТЦЭРЭН УРТНАСАН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАТЭРДЭНЭ АМГАЛАН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАЯНЦОГТ УЯНГА', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАЯРАА ОЮУНДУЛАМ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАЯРЖАВХЛАН МӨНХЧУЛУУН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БАЯРТОГТОХ БАТБИЛЭГ', NULL, 'both', NULL, NULL, NULL, '["БАТБИЛЭГ БАЯРТОГТОХ"]'::jsonb),
  (NULL, 'БАЯСГАЛАН ЗОЛЖАРГАЛ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БЕСТ КОЛОР ИНТЕРНЭШНЛ ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БЛҮФИН КАТЕРИНГ ХХК', '3644367', 'customer', '80180988', NULL, '9th Floor, UBH Center, Peace avenue-23, 1st Khoroo, Sukhbaatar District, Ulaanbaatar 14241', NULL),
  (NULL, 'БНЦМҮ ХХК', '4551958', 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БОЛД ТӨГӨЛДӨР ТЭЭВЭР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БОЛДБААТАР ГАНБАТ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БОЛОР ДАВС ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  ('C10086-01', 'БОСА Импекс', '2774097', 'both', '99102716', NULL, 'БГД, 16 хороо, Өндөр Гэгээн Занабазарын гудамж, Орхоны-1', '["Боса Импекс ХХК", "Боса импекс"]'::jsonb),
  ('C10087-01', 'БОСА Кондитер', '2774097', 'both', '99102716', NULL, 'БГД, 16 хороо, Өндөр Гэгээн Занабазарын гудамж, Орхоны-1', '["БОСА КОНДИТЕР", "БОСА Кондитер ХХК"]'::jsonb),
  (NULL, 'БСБ Электроникс ХХК', NULL, 'customer', '85257611', NULL, NULL, NULL),
  (NULL, 'БУМСАМБУУ ТУЯА', '112523570523', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'БУНЪЯА БЭХБАЯР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БУЯН-ӨЛЗИЙ БАТ-ӨЛЗИЙ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БЭРЭХЭ АМААНДАХ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БЭСТ КОЙН ТРАНСФОРТ ТРАК ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БЯМБАСҮРЭН БАТТУЛГА', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'БЯМБАСҮРЭН СҮРЭНХҮҮ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Бат-Оргил Эталон', '2681927', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1203', NULL),
  (NULL, 'Батика ХХК/ Өлзийтэгш', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Батлайн ХХК', '2728354', 'both', NULL, NULL, 'Тауэр M3, Өрөө 409', NULL),
  ('C10194-01', 'Батсээр', NULL, 'both', NULL, NULL, NULL, '["Батсээр XXК"]'::jsonb),
  (NULL, 'Баттрейд си', '2068419', 'supplier', NULL, NULL, NULL, NULL),
  ('C10195-01', 'Батхулд Трейд', NULL, 'both', NULL, NULL, NULL, '["Батхулд Трейд XXК"]'::jsonb),
  (NULL, 'Батцогт', 'НЭ75082319', 'both', NULL, NULL, 'Тауэр M2, Өрөө 907', NULL),
  ('C10081-01', 'Баян Оргил Цамхаг', NULL, 'both', NULL, NULL, NULL, '["Баян оргил цамхаг ХХК"]'::jsonb),
  ('C10047-01', 'Баян Шувуу', '3866726', 'both', '91000889', 'ariunsaikhan.o@nvts.mn', NULL, '["Баян шувуу ХХК"]'::jsonb),
  (NULL, 'Баян өлзийт мишээл ххк', '3325229', 'customer', NULL, NULL, 'Улаанбаатар хот,', NULL),
  (NULL, 'Баян-Өндөр ХХК', '5332044', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1107-1108', NULL),
  ('C10006-01', 'Баянгол Мед', '2869225', 'both', '88190824', 'sales2@bayngolmed.mn', 'Монгол, Улаанбаатар, Баянгол, 11-р хороо, хасбаатар, Өөрийн байр -1', '["Bayangol Med LLC", "Bayngol Med LLC", "Баянгол Мед ХХК"]'::jsonb),
  (NULL, 'Баярбат', '5722039', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1506', NULL),
  (NULL, 'Баярсайхан', '6500234', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1603', NULL),
  (NULL, 'Бест эрэл ХХК', '3434877', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1601', NULL),
  ('C10196-01', 'Биг Могул', NULL, 'both', NULL, NULL, NULL, '["Биг могул транс"]'::jsonb),
  (NULL, 'Биг Рентал ХХК', NULL, 'customer', '99817795', NULL, NULL, NULL),
  (NULL, 'Бизачи ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  ('C10084-01', 'Бласттек', '2707349', 'both', '99201750', NULL, NULL, '["Бласттек ХХК"]'::jsonb),
  (NULL, 'Бодь инженеринг ХХК', '6096247', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1408', NULL),
  (NULL, 'Бодьцогт ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Борхон сутай ХХК', '6218199', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1702', NULL),
  (NULL, 'Борхон сутай групп ХХК', '5899788', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1808', NULL),
  ('C10187-01', 'Борхүү', NULL, 'both', NULL, NULL, NULL, '["Borhuu"]'::jsonb),
  (NULL, 'Брикланд ХХК', '5255937', 'customer', '99077632', NULL, 'Улаанбаатар хот, СБД, 1 хороо, Чингисийн өргөн чөлөө, Монгол Тв таур 803 тоот', NULL),
  (NULL, 'Буд-Ирээдүй ХХК', '5785863', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Будхүү', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Булган Акира сан', NULL, 'both', NULL, NULL, 'Тауэр M1, Өрөө 806', NULL),
  (NULL, 'Бургаст хонх ХХК', '6269087', 'both', NULL, NULL, 'Тауэр M3, Өрөө 803', NULL),
  (NULL, 'Бургаст хонх ХХК/6269087', '5414261', 'both', NULL, NULL, 'Тауэр M3, Өрөө 803', NULL),
  (NULL, 'Бурхант Хангай Энержи ХХК', '6283233', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Буучхүү ХХК', '5503868', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1704', NULL),
  (NULL, 'Буянт Бумба-Эрдэнэ ХХК', '5678455', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1210', NULL),
  (NULL, 'Бэст буйдан ХХК', '5141621', 'both', NULL, NULL, 'Тауэр PRK, Өрөө P-010', NULL),
  (NULL, 'Бэст шоп ХХК', '7144873', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1004', NULL),
  (NULL, 'БҮДЭЭ АМАРТҮВШИН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Бүрэн Минж Транс ХХК', '4083539', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Бүрэн их наяд', '5539498', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'В.Энхмаа', '5374006', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1009', NULL),
  (NULL, 'ВИ АЙ ПИ ХӨШИГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Верде мишээл ХХК', 'УШ98102909', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1206', NULL),
  (NULL, 'Влабур ХХК', '5368081', 'both', NULL, NULL, 'Тауэр M1, Өрөө 504-505', NULL),
  (NULL, 'Г. Нансалмаа', '5045002', 'both', NULL, NULL, 'Тауэр M1, Өрөө 910', NULL),
  (NULL, 'Г.Бадрах', 'ХП84050518', 'both', NULL, NULL, 'Тауэр B1, Өрөө Угаалга', NULL),
  (NULL, 'Г.Баярсайхан', 'ЦЖ84031270', 'both', NULL, NULL, 'Тауэр PRK, Өрөө P-012', NULL),
  (NULL, 'Г.Ванчигсүрэн', 'КВ91050104', 'both', NULL, NULL, 'Тауэр M3, Өрөө 703', NULL),
  (NULL, 'Г.Сайн-Учрал', 'НР74070264', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1003', NULL),
  (NULL, 'Г.Хандсүрэн', 'УМ82051504', 'both', NULL, NULL, 'Тауэр M1, Өрөө 908-909', NULL),
  (NULL, 'Г.Цолмон', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Г.Цолмон /ЧС83120706', 'ТД86021471', 'both', NULL, NULL, 'Тауэр M3, Өрөө 905', NULL),
  (NULL, 'Г.Цэнгэлмаа', '6693326', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1403', NULL),
  (NULL, 'ГАЛБАДРАХ ЭРДЭНЭ-ОЧИР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ГАЛСАНДОРЖ ГАНБОЛД', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ГАЛЭМГЭН ХАЙДАВ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ГАН ЧҮЛТЭМ ТЭЭВЭР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ГАНБАЯР БААСАНДОРЖ', '643120042729', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'ГАНБОЛД АМГАЛАНЦОГТ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ГАНБОЛД БОЛД', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ГАНБОЛД ДУМХҮҮ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ГАНГАН АЛТАНЦЭЦЭГ', '112223651188', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'ГАНПҮРЭВ МЭРГЭНШАГАЙ', '111687432555', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'ГАНПҮРЭВ ПҮРЭВХИШИГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ГАНТУЛГА ГООМАРАЛ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ГАЦУУРТ ПРОПЕРТИС ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ГОМБО ЭРДЭНЭ-ОЧИР', '111685850351', 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ГОМБОСҮРЭН БЯМБАБАЯР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ГОНГОР ЗОРИГОО', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ГРАНД БАЖА ТЕХНИК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ГЭРЭЛТ-ОД ДАШДОРЖ', NULL, 'both', NULL, NULL, NULL, NULL),
  ('C10091-01', 'Газар Шим', NULL, 'both', NULL, NULL, NULL, '["Газар шим үйлдвэр ХК"]'::jsonb),
  (NULL, 'Газар шим үйлдвэр ХК', '2577127', 'customer', '94969909', NULL, 'БГД 20 хороо, Газар шим үйлдвэр оффис', NULL),
  ('C10198-01', 'Гайхам', '5300509', 'both', NULL, NULL, NULL, '["Гайхам ХХК", "ГАЙХАМ"]'::jsonb),
  (NULL, 'Ган Баялагийн Орд ХХК', '6506364', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1205', NULL),
  ('C10092-01', 'Ган Хийц', NULL, 'both', NULL, NULL, NULL, '["Ган хийц ХХК"]'::jsonb),
  ('C10093-01', 'Ганбаатар', NULL, 'both', NULL, NULL, NULL, '["Ганбаатар"]'::jsonb),
  (NULL, 'Гламур ХХК', '5253225', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1503', NULL),
  (NULL, 'Глобал Ивент ХХК', '5623502', 'customer', '99107946', NULL, 'Улаанбаатар хот, БЗД, 25-р хороо Манлайбаатар Дамдинсүрэнгийн гудамж UB Tower plus офис 204тоот', NULL),
  (NULL, 'Глобал-Ацетилен ХХК', '5361184', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1601', NULL),
  ('C10095-01', 'Говь Рэмөүт Сэрвисес', '7178801', 'both', NULL, NULL, NULL, '["ГОВЬ РЭМӨҮТ СЕРВИСЭС ГХОХХК", "Говь Рэмөүт Сервисес ХХК", "Говь Рэмөүт Сэрвисес"]'::jsonb),
  (NULL, 'Говь чанар', '4614925', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Говь-Эрдэнэ Кашмер ХХК', '5360943', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1710', NULL),
  (NULL, 'Голденлотус', '5382319', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Голомтбанк', '2075377', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Гранд Гүүд Экспресс ХХК', '7073449', 'customer', '99924747', NULL, NULL, NULL),
  ('C10097-01', 'Грийн Нийд', NULL, 'both', NULL, NULL, NULL, '["Грийн нийд ХХК"]'::jsonb),
  (NULL, 'Гэзэгт', '2144255', 'supplier', NULL, NULL, NULL, NULL),
  ('C10099-01', 'Гэр групп', NULL, 'both', NULL, NULL, NULL, '["Гэр групп"]'::jsonb),
  ('C10100-01', 'Гэр Өргөө', NULL, 'both', NULL, NULL, NULL, '["Гэр Өргөө ТББ"]'::jsonb),
  (NULL, 'Гэр Өргөө ТББ', '8208468', 'customer', NULL, NULL, 'Улаанбаатар', NULL),
  (NULL, 'Гэрэгэ киоск', '5731089', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Гэрэлмаа', '7155505', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1406', NULL),
  ('C10098-01', 'Гүнтулга', NULL, 'both', NULL, NULL, NULL, '["Гүнтулга", "Гүн тулга"]'::jsonb),
  (NULL, 'Д.Доржпүрэв', 'МЗ77112435', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1203', NULL),
  (NULL, 'Д.Доржпүрэв-1', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Д.Жамбалдорж', 'ГГ93050713', 'both', NULL, NULL, 'Тауэр M3, Өрөө 510', NULL),
  (NULL, 'Д.Заяабадрах', 'ИУ91121413', 'both', NULL, NULL, 'Тауэр PRK, Өрөө P-057', NULL),
  (NULL, 'Д.Мэндсайхан', 'ПВ67062086', 'both', NULL, NULL, 'Тауэр M3, Өрөө 402', NULL),
  (NULL, 'Д.Мөнх-Эрдэнэ', 'УП95062011', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1707', NULL),
  (NULL, 'Д.Осоржамаа', 'АЭ57081072', 'both', NULL, NULL, 'Тауэр M2, Өрөө 905', NULL),
  (NULL, 'Д.Хулан', 'ЧН79020509', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1402', NULL),
  (NULL, 'Д.Шинэцоггени', 'МЮ85071277', 'customer', '88013387', NULL, NULL, NULL),
  (NULL, 'Д.Үүрийнтуяа', NULL, 'both', NULL, NULL, 'Тауэр M3, Өрөө 1510', NULL),
  (NULL, 'ДАВАА БАТБААТАР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДАВААДОРЖ ОДОНТУНГАЛАГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДАВААЖАВ БОЛДБААТАР', '420178670681', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'ДАГВАДОРЖ СОЛОНГО', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДАМБА ЭРДЭНЭЖАРГАЛ', '644967510563', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'ДАМДИН ЗАГДЗҮСЭМ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДАНДГАЙ БАТСҮХ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДАНИСТА ТРЕЙД ББСБ” ХХК', '2765446', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'ДАНС ХӨТӨЛСНИЙ ШИМТГЭЛ-CA900', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДАРИЙЖАВ СОСОРБАРАМ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДАРЦАГТ ГУА ХАЙРХАН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДАТАКОМ КЛАУД ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДАТАКОМ ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДАШ БАТЦООЖ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДАШ МӨНХТАЙВАН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДАШБААТАР МАРТ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДАШЗЭВЭГ САРАНЦЭЦЭГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДАШЗЭВЭГ ТӨГСЖАРГАЛ', '110757091449', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'ДАШНЯМ АМАРТҮВШИН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДДМТ Мөнхсүх', 'ЛЖ77020318', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1405', NULL),
  (NULL, 'ДДМТ Нармандах', 'ЧБ66081613', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1401', NULL),
  (NULL, 'ДДМТ Тулга', 'УК89041332', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1201', NULL),
  (NULL, 'ДДМТ Энхсаруул', 'ХП88020501', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1407', NULL),
  (NULL, 'ДИЖИТАЛ РЕНЬЮВЭБЛЬ ЭНЕРЖИ ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДОРЖ ГАНХУЯГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДОРЖСҮРЭН ЖАМСРАНЖАВ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДРИЙМ ФИНАЛ ДИЗАЙН ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДЭЛГЭРСАЙХАН БАТЦООЖ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ДЭНЗЭНШАРАВ БАЯРТОГТОХ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Дазл ХХК', '5017726', 'customer', '90116463', NULL, 'Улаанбаатар  хот', NULL),
  (NULL, 'Дайчин зам  ХХК', '5586623', 'customer', '80124886', NULL, 'Улаанбаатар  хот', NULL),
  (NULL, 'Далай шанд коммерс', '3330338', 'supplier', NULL, NULL, NULL, NULL),
  ('C10103-01', 'Дархан Ар Шанд', NULL, 'both', NULL, NULL, NULL, '["Дархан ар шанд ХХК", "Дархан ар шанд"]'::jsonb),
  (NULL, 'Дархан гантиг ХХК', '3450072', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Дата Ланд Технологи ХХК', '6594867', 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Дек ХХК', '2080486', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1703', NULL),
  (NULL, 'Дес ХХК', '5027357', 'both', NULL, NULL, 'Тауэр M1, Өрөө 804', NULL),
  (NULL, 'Ди Би Протех Консалт ХХК', '7023825', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1510', NULL),
  (NULL, 'Ди Эйч Эл форвардинг Монголиа', '6081436', 'both', NULL, NULL, 'Тауэр M3, Өрөө 705', NULL),
  (NULL, 'Ди би протех', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  ('C10104-01', 'Дижитал Концепт', '6531342', 'both', NULL, NULL, NULL, '["Дижитал Концепт", "Дижитал концепт"]'::jsonb),
  ('C10105-01', 'Доктор Авто Сервис', '5253209', 'both', '99006720', NULL, NULL, '["Доктор авто сервис", "Доктор авто сүлжээ ххк"]'::jsonb),
  (NULL, 'Долоон болдог ХХК', '2819449', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1503 1505', NULL),
  (NULL, 'Домогт Хан Алтай ХХК', '6084303', 'customer', '80873344', NULL, 'Улаанбаатар, Хан-Уул дүүрэг, Хан-Уул тауэр 10 давхар 1001 тоот', NULL),
  (NULL, 'Дорж ТАВАНЖИН', NULL, 'both', NULL, NULL, NULL, NULL),
  ('C10219-01', 'Дорнын Мандах Төмөр ХХК', NULL, 'both', NULL, NULL, NULL, '["ДОРНЫН МАНДАХ ТӨМӨР ХХК", "Дорнын Мандах Төмөр ХХК"]'::jsonb),
  (NULL, 'Дэлгэрэх ожс', '6085857', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Дэлхийн Стандарт Нэг Монгол', '8218528', 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Дэмбэрэл Нямбуу', 'ЦД74011673', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1008', NULL),
  (NULL, 'Дээдлэн дэвших их мандал', '7275473', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'ДҮГЭР ОЮУН-ЭРДЭНЭ', '111678931579', 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Дөлгөөн аравт ХХК', '6045502', 'customer', '88318883', NULL, 'Улаанбаатар  хот', NULL),
  (NULL, 'Дөлмандах', 'УХ88100150', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1206-1208', NULL),
  (NULL, 'Дөрвөн өлзий ХХК', '2056488', 'customer', '99908910', NULL, 'Улаанбаатар хот, БГД, 20-р хороо, Үйлдвэрийн баруун бүс, ХД50', NULL),
  (NULL, 'Евро Урлан ХХК', '6405665', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1507', NULL),
  (NULL, 'Евросити', '5688434', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Ж. Энх-Ундрах', '7119865', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1706', NULL),
  (NULL, 'Ж.Баасанжаргал', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Ж.Энхжаргал', 'РЭ78121406', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1907', NULL),
  (NULL, 'Ж.Энхцэцэг', 'ХП64042102', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1704-1705', NULL),
  (NULL, 'Ж.Энхцэцэг/Элабора  групп ХХК', '7217081', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'ЖАВЗАНДОРЖ МӨНХЗАЯА', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЖАВХЛАН БАЯРБААТАР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЖАВХЛАН НАРАНБААТАР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЖАВХЛАН ЦОЛМОНБААТАР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЖАЛМАА ЭРДЭНЭЦЭЦЭГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЖАМСРАН НЭРГҮЙ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЖАНЦАН ТӨРМӨНХ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЖИ ЗИ ИХ МӨНХ ХУРД ТРАНС', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЖИГМЭД ЦЭЭСҮРЭН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЖОНОН ЦАЙДАМ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЖЭМЗ ИН ГОЛД ХХК', '6008372', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Жаргалант парадайз групп ХХК', '6551734', 'customer', '99114862', NULL, 'Улаанбаатар хот, СБД, 1-р хороо, олимпийн гудамж, 14-р байр 7 тоот', NULL),
  (NULL, 'Женералмедиа холдинг', '5899524', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Женесис кеймп ХХК', '6013155', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1704', NULL),
  (NULL, 'Жигүүр гранд', '2543729', 'customer', '99997302', NULL, NULL, NULL),
  ('C10110-01', 'Жёото Карэ Монгол', '6924948', 'both', '94997062', NULL, NULL, '["Жёото Карэ Монгол ХХК"]'::jsonb),
  (NULL, 'ЗАГАЛ ЖАМБАЛСҮРЭН', '111693110645', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'ЗАМ ТЭЭВРИЙН АЖИЛЛАГСДЫН МЭРГЭЖЛИЙН БОЛОВСРОЛЫН ИНСТИТУТ НҮТББ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЗЕБРА ИНТЕРНЭШНЛ ДИСТРИБЬЮШН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЗЕБРА СЕЛЕКТ ДАБЛЬЮУ ЭНД ЭС', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЗЭТ ЭМ И ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Замын битум ХХК', NULL, 'customer', '99110838', NULL, NULL, NULL),
  (NULL, 'Зангиа битүби', '8425809', 'supplier', NULL, NULL, NULL, NULL),
  ('C10112-01', 'Зебра', '8459045', 'both', '93114999', 'Baasan.b@zebragroup.mn', 'Хан-Уул дүүрэг, Чингисийн өргөн чөлөө, 19-р хороо, Үйлдвэр Шаравын гудамж', '["Зебра Интернешнл"]'::jsonb),
  (NULL, 'Зоригт Алтантулга', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  ('C10070-01', 'Зүйдвинд монголиа', '6976808', 'both', '89052420', 'anastasiyakozhevnikova@flexway.mn', 'Улаанбаатар хот, БЗД 10-р хороо, Гацууртын зам 90, В6 агуулах', '["Zuindvind", "Зүйдвинд Монголиа ХХК", "Зүйндвинд", "Зүйндвинд ХХК"]'::jsonb),
  (NULL, 'ЗӨГИЙН БАЯЛАГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Зөв талст ХХК', '6701027', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1808', NULL),
  (NULL, 'И И Эс ХХК', '5894646', 'customer', '95049140', NULL, 'Улаанбаатар, Баянзүрх, 26-р хороо, дүнжингарав, 102, 27 тоот', NULL),
  (NULL, 'И.Уранчимэг', '5669464', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1404', NULL),
  (NULL, 'ИВАН БУНЧИНДУЛАМ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ИНТЕРНЭЙШНЛ МЕДИКАЛ СЕНТЕР ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Ивээлт гүн ХХК', '6131174', 'customer', '88001368', NULL, 'Улаанбаатар  хот', NULL),
  (NULL, 'Изуми ХХК', '5726107', 'both', NULL, NULL, 'Тауэр M3, Өрөө 706', NULL),
  (NULL, 'Икспанс модуль ХХК', '5455448', 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Илинкс Экспресс ХХК', '2734966', 'customer', '91202020', NULL, 'Баянгол дүүрэг 2-р хороо Гранд Плаза цогцолбор 1101 Улаанбаатар - 14250, Монгол Улс', NULL),
  ('C10116-01', 'Империал Партнер', NULL, 'both', NULL, NULL, NULL, '["Империал партнерс ХХК"]'::jsonb),
  (NULL, 'Империал партнерс ххк', '5852297', 'customer', '94094688', NULL, 'Улаанбаатар, Хан-Уул, 1-р хороо, ТВ5 Оффис 7давхар', NULL),
  (NULL, 'Инкколор ХХК/Inkcolor LLC', '5284376', 'customer', '88880731', NULL, 'Улаанбаатар  хот', NULL),
  (NULL, 'Интакс эс каунсл ХХК', '6205992', 'both', NULL, NULL, 'Тауэр M3, Өрөө 409', NULL),
  (NULL, 'Интерактив ХХК', '2097192', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1101-1110', NULL),
  (NULL, 'Интермед эмнэлэг', NULL, 'customer', NULL, NULL, NULL, NULL),
  (NULL, 'Интерэшиа энержи монголиа', '6902987', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Инфантс Тоддлерс ХХК', '6360033', 'both', NULL, NULL, 'Тауэр M1, Өрөө 302', NULL),
  (NULL, 'Инфинити Хьюман Капитал Менежмент Монгол ХХК', '7081793', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Инфинити аспирэйшн ХХК', '6433596', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1607', NULL),
  (NULL, 'Ирээдүйн баатрууд ХХК', '5474639', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1609', NULL),
  (NULL, 'Итгэл ивээлт үйлс ХХК', '7127705', 'both', NULL, NULL, 'Тауэр M1, Өрөө 708-710', NULL),
  (NULL, 'Итопиа Стор ХХК', '7191569', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Их Наяд Хөгжил ХХК', '5442311', 'both', NULL, NULL, 'Тауэр M3, Өрөө 705', NULL),
  ('C10119-01', 'Их Эрч', '2560704', 'both', '95199883', 'otgonbayar.a@energytech.mn', 'Улаанбаатар хот, СХД, 17-Р хороо, 1-р хороолол', '["Их эрч ХХК"]'::jsonb),
  (NULL, 'Их дельта инженеринг ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Их эзэн чингис ХХК', '2874873', 'both', NULL, NULL, 'Тауэр M1, Өрөө 601-602', NULL),
  (NULL, 'Их эрхэт говь ХХК', '3616177', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1608', NULL),
  (NULL, 'КАРТЫН ГҮЙЛГЭЭНИЙ ӨГЛӨГИЙН ТҮР ДАНС-ҮЦГТ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'КЕМ ТЕК ХХК', '6047637', 'customer', '86088519', NULL, 'УБ , СБД, 1-р хороо, Очир төв, 701-Б тоот', NULL),
  (NULL, 'КОЛЛПРО', NULL, 'both', NULL, NULL, NULL, '["КОЛЛПРО ХХК"]'::jsonb),
  (NULL, 'КОЛЬЯ БАЯРСҮРЭН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Капитис ББСБ ХХК', '5717892', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Квант майнинг ХХК', '6117384', 'customer', '99016288', NULL, NULL, NULL),
  (NULL, 'Конфрейт Агент  ХХК', '5854873', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1501-1502', NULL),
  ('C10121-01', 'Коожицү Монголиа', '6326714', 'both', '80117391', 'tengis@kohjitsu.com', NULL, '["Коожицү Монголиа ХХК"]'::jsonb),
  (NULL, 'Космикрайс ХХК', '8979009', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1201', NULL),
  ('C10200-01', 'Ксеро График', '5561493', 'both', NULL, NULL, NULL, '["Ксеро график ХХК", "КСЕРО ГРАФИК ХХК"]'::jsonb),
  (NULL, 'Куадро ХХК', '6177573', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Кэй Эс Би ХХК', '5089794', 'both', NULL, NULL, 'Тауэр M3, Өрөө 407', NULL),
  (NULL, 'Л.Мөнх-Эрдэнэ', 'СЮ88021511', 'both', NULL, NULL, 'Тауэр Parking, Өрөө P-029', NULL),
  (NULL, 'Л.Номгонмаа', 'ВБ77122000', 'both', NULL, NULL, 'Тауэр M3, Өрөө 509', NULL),
  (NULL, 'Л.Оюунжаргал', 'ЙЮ87072663', 'both', NULL, NULL, 'Тауэр M3, Өрөө 505', NULL),
  (NULL, 'ЛОНГ ХОУЛ ТРАК ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЛОТУС ТАНГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЛУУШААН ЦОГТБААТАР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЛХАГВАСҮРЭН БАЛЖИННЯМ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЛХАГВАСҮРЭН ВАНЧИНДОРЖ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЛХАМЖАВ САЯБУМ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Лайн арт ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Либра Энержи ХХК/ Петро хан ХХК', NULL, 'both', NULL, NULL, 'Тауэр M1, Өрөө', NULL),
  (NULL, 'Либра энержи ХХК', '6289312', 'customer', '94942844', NULL, 'Улаанбаатар, Баянзүрх, 18-р хороо, 13 хороолол, 13, 78 тоот', NULL),
  (NULL, 'Лога интернэшнл ХХК', '6119751', 'customer', '80084573', NULL, 'Улаанбаатар хот 1 р хороо, сөүл бизнес центр, 403тоот', NULL),
  ('C10124-01', 'М Агро', '5573548', 'both', '88887108', 'batkhuu.ts@metagro.mn', 'Улаанбаатар хот, Сүхбаатар дүүрэг 1 хороо, Чингисийн өргөн чөлөө-15, Цэнтрал Парк Бьюлдинг, 8 давхар', '["М АГРО ХХК", "М Агро ХХК"]'::jsonb),
  (NULL, 'М.Дөлмандах', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'М.Мөнхтуяа', NULL, 'both', NULL, NULL, 'Тауэр M3, Өрөө 909', NULL),
  (NULL, 'М.Сэлэнгэ', '8434735', 'both', NULL, NULL, 'Тауэр M2, Өрөө 906', NULL),
  (NULL, 'М.Уянга', NULL, 'both', NULL, NULL, 'Тауэр M3, Өрөө 1005', NULL),
  (NULL, 'М.Цэндсүрэн', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  ('C10031-01', 'МАК', '2095025', 'both', '99289099', 'ariunzaya.d@mak.mn', 'Улаанбаатар, Хан-Уул, 1-р хороо, 19 хороолол, чингисийн өргөн чөлөө, монголын алт ххк-ийн төв байр-44', '["MAK", "МАК", "Монголын алт МАК ХХК.", "Монголын алт МАК ХХК"]'::jsonb),
  ('C10031-03', 'МАК Евро Блок', NULL, 'both', NULL, NULL, NULL, '["МАК Блок"]'::jsonb),
  ('C10031-02', 'МАК Цемент', '5830974', 'both', '99138524', 'munkhzul.m@mak.mn', 'Улаанбаатар, Хан-Уул, 1-р хороо, 19 хороолол, чингисийн өргөн чөлөө, монголын алт ххк-ийн төв байр-44', '["МАК цемент ХХК", "MAK Цемент ХХК"]'::jsonb),
  (NULL, 'МАКС МАШИНЕРИ ИНДАСТРИ ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'МАКС РӨҮД ХХК', '5354013', 'customer', '80003557', '1232@123', 'УБ, Чингэлтэй дүүрэг, 5-р хороо, Самбуугийн гудамж-24, М-Плаза, 5 давхар', NULL),
  (NULL, 'МАНЖИР АРЦХҮҮ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'МВМ СОР ХХК', '6369715', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'МЕТМ арвижих', '6546234', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'МОНГОЛЫН МАРКЕТИНГИЙН ХОЛБОО НҮТББ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'МОСТ МОНИ ӨГЛӨГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'МТА.ТАТВАР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'МХААЭАМХ ТББ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'МЭЙЖОР ДРИЛЛИНГ МОНГОЛ ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'МЯГМАР ОТГОНЖАРГАЛ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Мааньт Хараат ХХК', '2687305', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1605', NULL),
  (NULL, 'Мазаалай петролиум ХХК', '6216544', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1203', NULL),
  (NULL, 'Макс клэйн энержи', '7243425', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Максон Консалтинг  ХХК', '6289541', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1204-1205', NULL),
  (NULL, 'Мандал ресурс ХХК', '5699134', 'customer', '94098912', NULL, 'Улаанбаатар ,Сүхбаатар дүүрэг, 1-р хороо, Энхтайвны , өргөн чөлөө, Авзага оффис, 3 давхар', NULL),
  ('C10203-01', 'Мастер Импекс', NULL, 'both', NULL, NULL, NULL, '["Материал Импекс"]'::jsonb),
  ('C10202-01', 'Мастер Ложистик', NULL, 'both', NULL, NULL, NULL, '["Мастер Ложистик ХХК"]'::jsonb),
  ('C10126-01', 'Мастер Электрик', NULL, 'both', NULL, NULL, NULL, '["Мастер электрик ХХК"]'::jsonb),
  ('C10201-01', 'Мастер айф', NULL, 'both', NULL, NULL, NULL, '["Мастер айфф ХХК"]'::jsonb),
  (NULL, 'Мега турбо электрик ХХК', '7196633', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Мегапластик Системс ХХК', '5708524', 'both', NULL, NULL, 'Тауэр M3, Өрөө 607', NULL),
  (NULL, 'Медиус ХХК', '5959012', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1504', NULL),
  (NULL, 'Мес плас ХХК', '7175473', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  ('C10127-01', 'Минж Оюу', '7115361', 'both', '88181617', 'minjuuhei0109@yahoo.com', 'Улаанбаатар, Чингэлтэй 4-р хороо, бага тойруу, 32, 46 тоот', '["Минж Оюу XXК"]'::jsonb),
  (NULL, 'Миний Сайхан Орон ХХК', '5192137', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1706', NULL),
  ('C10128-01', 'Миний дэлгүүр', '6225608', 'both', NULL, NULL, NULL, '["Миний дэлгүүр", "Миний дэлгүүр ХХК"]'::jsonb),
  (NULL, 'Мичи Гранд ХХК', '5732956', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Мобиком корпораци', '2072572', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Могойн гол ХХК', '2034859', 'customer', '88106430', NULL, 'Улаанбаатар  хот', NULL),
  ('C10130-01', 'Могул Ибиз', NULL, 'both', NULL, NULL, NULL, '["Могул Ибиз ХХК"]'::jsonb),
  (NULL, 'Модерн Хас ХХК', '5518105', 'both', NULL, NULL, 'Тауэр M3, Өрөө 601', NULL),
  ('C10184-01', 'Модерн гэр', NULL, 'both', NULL, NULL, NULL, '["Модерн гэр", "Модерн гэр XXK"]'::jsonb),
  (NULL, 'Мон Кабель Системс ХХК', '2087332', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1002', NULL),
  (NULL, 'Мон Медикал Клиник ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Мон Энержи консалтинг ХХК', '2790017', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1901', NULL),
  (NULL, 'Мон-Эгг ХХК', '2772086', 'customer', '88874222', NULL, 'НВЦ ХХК-ын өөрийн байр, Улаанбаатар хот', NULL),
  ('C10131-01', 'Монгол Контент', NULL, 'both', NULL, NULL, NULL, '["Монгол Контент", "Монгол Контент XXК"]'::jsonb),
  (NULL, 'Монгол Од Эдүкэйш Девелопмент ХХК', '7137281', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Монгол газар шим ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  ('C10205-01', 'Монгол дахь Австралийн худалдааны танхим', NULL, 'both', NULL, NULL, NULL, '["МОНГОЛ ДАХЬ АВСТРАЛИЙН ХУДАЛДААНЫ ТАНХИМ", "Монгол дахь Австралийн худалдааны танхим"]'::jsonb),
  (NULL, 'Монгол фарм дистрибюшн ХХК', '5976286', 'both', NULL, NULL, 'Тауэр M1, Өрөө 401-410', NULL),
  (NULL, 'Монголз ХХК', '8379009', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Монголз ХХК-1', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  ('C10132-01', 'Монголиан Стар Дистрибюшн', NULL, 'both', NULL, NULL, NULL, '["Монголиан стар дистрибюшин ХХК", "Монголиан стар дис"]'::jsonb),
  (NULL, 'Монголиан стар дистрибюшин ХХК', '5752833', 'customer', '99162636', NULL, 'Улаанбаатар хот, ХУД, 15-р хороо, Махатма Гандигийн гудамж, Галакси Тауэр 9 давхар', NULL),
  (NULL, 'Монголын тээвэр зуучлагчдын нэгдсэн холбоо', '8136599', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Монголын хөдөлмөрийн аюулгүй ажиллагаа эрүүл ахуйн менежментийн хүрээлэн', '8032653', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Монкабель Системс ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  ('C10034-01', 'Монкон', NULL, 'both', NULL, NULL, NULL, '["Монкон констракшин ХХК", "Moncon LLC"]'::jsonb),
  (NULL, 'Монкон констракшин ХХК', '5372852', 'customer', '94900887', NULL, 'СБД, 1-р хороо, Олимпын гудамж, Нью Хоризонс Оффис, 12 давхар', NULL),
  (NULL, 'Монкран Консалтинг ХХК', '5883849', 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Монлаа ХХК', '2045931', 'customer', '80071250', NULL, 'Улаанбаатар хот', NULL),
  ('C10134-01', 'Моннис Инженеринг', '5387582', 'both', '80022154', 'choinyam@monnis.com', NULL, '["Моннис Инженеринг ХХК"]'::jsonb),
  ('C10035-01', 'Монхорус', '2587807', 'both', '99200646', 'Zorigtbaatar@monhorus.mn', 'Улаанбаатар, Сүхбаатар, 2-р хороо, Монгол
  ном ХХк-ны байр, 6', '["Monkhorus LLC", "Монхорус-Интернэшнл", "Монхорус эрчим ХХК"]'::jsonb),
  ('C10135-01', 'Монхорус эрчим ХХК', '2541238', 'both', '99200646', NULL, 'Монхорус-Эрчим Хаяг: Монгол, Улаанбаатар, Сүхбаатар, 10-р хороо, 7 хороолол, 60, БДТТөвийн байр', NULL),
  (NULL, 'Морганайт Мега Трейд ХХК', '6300367', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1706-1710', NULL),
  (NULL, 'Моргонайт Мега Трейд ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Мэргэн хангал ХХК', '5095794', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1602', NULL),
  (NULL, 'Мэрриж Монгол ХХК', '6404049', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1607', NULL),
  (NULL, 'МӨНГӨНШАГАЙ БАТТАМИР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'МӨНХБАЛДАН ОТГОНСҮРЭН', '110779561159', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'МӨНХБАТ НАМУУНТУУЛ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'МӨНХСОЛОНГО ОРГИЛ', '5734673', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'МӨНХТӨР НОМИНЗУЛ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'МӨНХӨД МАНДАН ДЭЛГЭРХҮЙ ХИШИГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Мөнгөн туулын долгио', '7071089', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Мөнгөнбийр', '5057558', 'supplier', NULL, NULL, NULL, NULL),
  ('C10209‑01', 'Мөнх Сондор Гранд ХХК', NULL, 'both', NULL, NULL, NULL, '["МӨНХ СОНДОР ГРАНД ХХК", "Мөнх Сондор Гранд ХХК"]'::jsonb),
  ('C10193-01', 'Мөнхбат', NULL, 'both', NULL, NULL, NULL, '["Б.Мөнхбат"]'::jsonb),
  (NULL, 'Мөнхийн тун ХХК', '2024608', 'both', NULL, NULL, 'Тауэр M1, Өрөө 506', NULL),
  ('C10136-01', 'Мөрөн Ментор', '7005385', 'both', '80551582', NULL, 'БГД 4-р хороо 59-13тоот', '["Мөрөн ментор ХХК"]'::jsonb),
  (NULL, 'Н.Ану', 'ГЮ00221508', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1602', NULL),
  (NULL, 'Н.Номин-Эрдэнэ', '6972616', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1206', NULL),
  (NULL, 'Н.Норов', 'ОЭ83022875', 'both', NULL, NULL, 'Тауэр M2, Өрөө 901', NULL),
  (NULL, 'Н.Тамжид', '7124825', 'both', NULL, NULL, 'Тауэр M3, Өрөө 602-603', NULL),
  (NULL, 'Н.Цэцэгсанаа', 'ЧЛ75051363', 'both', NULL, NULL, 'Тауэр M3, Өрөө 801', NULL),
  (NULL, 'Н.Энхбаяр', 'ИЙ73032211', 'both', NULL, NULL, 'Тауэр M3, Өрөө 810', NULL),
  (NULL, 'НАРАНЗУЛ МӨНХ-АМГАЛАН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'НАРАНЦЭЦЭГ СЭНДЭНДОРЖ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'НАЦАГДОРЖ ТОДХАРАА', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'НБИК ХХК', '5403502', 'both', NULL, NULL, NULL, NULL),
  ('C10047-02', 'НВЦ', '6817013', 'both', '91000889', 'ariunsaikhan.o@nvts.mn', NULL, '["НВЦ ТРЕЙДИНГ ХХК", "NVTS LLC"]'::jsonb),
  (NULL, 'НОБУС ПРОПЕТИ ХХК', '8483582', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'НОВА ВЕНТУР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'НОМИН ЛОЖИСТИК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'НОМИН НОГООН ТОЛГОЙ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'НОМЭКС ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'НУТГИЙН БУЯНТ УУЛ ШИВЭЭТ ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'НЭРГҮЙ БЯМБАДУЛАМ', '111063190543', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'НЯМ БАЯСГАЛАН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'НЯМДОРЖ МЯГМАРДОРЖ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Налайх уран гар ХХК', '2728486', 'both', NULL, NULL, 'Тауэр M1, Өрөө 808-809', NULL),
  ('C10137-01', 'Намнан Индастри', '5971772', 'both', '88106568', NULL, NULL, '["Намнан Индастри ХХК"]'::jsonb),
  (NULL, 'Наран тээг ХХК', '2790459', 'customer', '95028101', NULL, NULL, NULL),
  (NULL, 'Наран шожи монголиа ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Нарт Гарден ХХК', '7056097', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1503', NULL),
  (NULL, 'Нисээч Интернэйшнл ХХК', '2745615', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1701', NULL),
  ('C10138-01', 'Нованекст Консалт', '6960413', 'both', '99011428', 'novanext2022@gmail.com', NULL, '["Нованекст консалт ХХК"]'::jsonb),
  ('C10045-01', 'Номин', '5213339', 'both', '89882566', 'Orgilzul.m@nomin.net', 'Улаанбаатар хот, СХД, 20 хороо, УБИ салбарын байр', '["Nomin LLC", "Номин трейдинг ХХК", "Номин"]'::jsonb),
  (NULL, 'Номин стандарт ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Номин трейдинг ХХК', NULL, 'customer', NULL, NULL, NULL, NULL),
  (NULL, 'Номин хайпермаркет', '6736076', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Нони ХХК', '2790564', 'both', NULL, NULL, 'Тауэр M1, Өрөө 706-707', NULL),
  ('C10139-01', 'Норконс', '5486637', 'both', '99159690', NULL, NULL, '["Норконс ХХК"]'::jsonb),
  (NULL, 'Нью Жуулчин Тур ХХК', '2738341', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1003-1006', NULL),
  (NULL, 'Нью Фунт ХХК', '2854988', 'customer', '99096389', NULL, 'Улаанбаатар хот', NULL),
  (NULL, 'Нэкст Групп ХХК', '5926483', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1006-1007', NULL),
  (NULL, 'Нэкст логистикс ХХК', '6600123', 'customer', '99074560', NULL, 'Улаанбаатар, Хан-Уул дүүрэг, 15-р хороо, стадион оргил', NULL),
  ('C10140-01', 'Нүүдэлчин Бариа', '7037441', 'both', '80977999', NULL, NULL, '["НҮҮДЭЛЧИН БАРИА", "Нүүдэлчин Бариа ХХК"]'::jsonb),
  (NULL, 'О.Маралгоо', 'ЦГ80071806', 'both', NULL, NULL, 'Тауэр M3, Өрөө 704', NULL),
  (NULL, 'О.Одончимэг', 'ЗЮ74012604', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1001', NULL),
  (NULL, 'О.Цолмон', '6419267', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1401', NULL),
  (NULL, 'ОДХҮҮ ТЭЛМЭН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ОНДОБАБУХАЙ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ОСОР АРИУНБОЛД', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ОСОР ПҮРЭВДОРЖ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ОТГОНБАЯР ЛХАГВАСҮРЭН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ОТГОНТУЯА УЯНГА', '110729091477', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'ОЧИРБАТ ОЛЗОД', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ОЮУНБААТАР БАЯСГАЛАН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ОЮУНБАТ УДВАЛ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ОЮУНГЭРЭЛ БАЛДАНДОРЖ', NULL, 'both', NULL, NULL, NULL, NULL),
  ('C10207-01', 'Од Номин Экспресс', NULL, 'both', NULL, NULL, NULL, '["Од Номин Экспрэсс ХХК"]'::jsonb),
  (NULL, 'Ойнбирж', '2026945', 'supplier', NULL, NULL, NULL, NULL),
  ('C10208-01', 'Олон улсын дунд сургууль', NULL, 'both', NULL, NULL, NULL, '["Олон улсын дунд сургууль"]'::jsonb),
  (NULL, 'Ононтуул', NULL, 'both', NULL, NULL, 'Тауэр M1, Өрөө 1602-1603', NULL),
  ('C10141-01', 'Орд гэр', '6382762', 'both', '88013387', NULL, NULL, '["Орд гэр", "Орд гэр ХХК"]'::jsonb),
  (NULL, 'Ори студиос', '6607632', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Осоржамаа', 'ИЭ85040864', 'both', NULL, NULL, 'Тауэр M2, Өрөө 905', NULL),
  (NULL, 'Очирбат Туул', 'ЧП83072403', 'both', NULL, NULL, 'Тауэр M3, Өрөө 604', NULL),
  (NULL, 'Оюунсүрэн', 'ЦБ84071168', 'both', NULL, NULL, 'Тауэр M2, Өрөө 902', NULL),
  (NULL, 'Оюунсүрэн/Ундрахсүн далай ХХК', '5473217', 'both', NULL, NULL, NULL, NULL),
  (NULL, 'П. Баярмаа', 'ВЮ78080504', 'both', NULL, NULL, 'Тауэр M3, Өрөө 610', NULL),
  (NULL, 'П.Бямбадорж', NULL, 'both', NULL, NULL, 'Тауэр M1, Өрөө 604', NULL),
  (NULL, 'П.Мөнхцэцэг', 'ЦВ86040162', 'both', NULL, NULL, 'Тауэр M3, Өрөө 506', NULL),
  (NULL, 'ПДМС ХХК', '2768453', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1008', NULL),
  (NULL, 'ПРЕМИУМ БЬЮЛДИНГ МАТЕРИАЛС ХХК', NULL, 'customer', NULL, NULL, NULL, NULL),
  (NULL, 'ПРЕМИУМ КОНКРИТ ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ПЭРЭНЛЭЙ ТӨМӨР-ОЧИР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Петростар', '5241901', 'supplier', NULL, NULL, NULL, NULL),
  ('C10048-01', 'Пик Пак', NULL, 'both', NULL, NULL, NULL, '["Pick Pack"]'::jsonb),
  ('C10049-01', 'Премиум', '6266258', 'both', '91119235', 'namuun.z@premiumbm.mn', 'Улаанбаатар хот, Сүхбаатар дүүрэг, 1-р хороо, Олимпийн гудамж 19/А, Шангри-Ла
  Оффис Центр, 23 -р давхар', '["Premium Building Materials LLC", "Премиум Бьюлдинг Материалс ХХК", "Премиум"]'::jsonb),
  ('C10049-03', 'Премиум Иннова', '6625223', 'both', '99170783', 'enkhmaa.s@premiumconcrete.mn', NULL, '["ПРЕМИУМ ИННОВА ХХК", "Премиум Иннова ххк"]'::jsonb),
  (NULL, 'Премиум нэксус', '6155804', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'ПҮРЭВДОРЖ БУЯНЗАЯА', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ПҮРЭВЖАВ ХАСБААТАР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ПҮРЭВНЯМ СОДХҮҮ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ПҮРЭВСҮРЭН ДАВААДУЛАМ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ПҮРЭВСҮРЭН МЯГМАРСҮРЭН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ПҮРЭВСҮРЭН ПҮРЭВСҮХ', NULL, 'both', NULL, NULL, NULL, NULL),
  ('C10146-01', 'Пүрэвсүрэн', NULL, 'both', NULL, NULL, NULL, '["Пүрэвсүрэн"]'::jsonb),
  (NULL, 'Р.Чагцал', 'ФЖ77092001', 'both', NULL, NULL, 'Тауэр M3, Өрөө 710', NULL),
  (NULL, 'Р.Чагцал/ Рийл Терапи ХХК', '7172081', 'both', NULL, NULL, 'Тауэр M3, Өрөө 710', NULL),
  (NULL, 'Реактив ХХК', '2068508', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1504', NULL),
  ('C10051-01', 'Реха Мед', '6193374', 'both', NULL, NULL, NULL, '["Reha med LLC"]'::jsonb),
  (NULL, 'Рэд крэйн', '8348405', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Рүйхэн энержи ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Рүүт оф кофиа', '7221953', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'С.Ариунтуяа', 'ХМ70061460', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1501', NULL),
  (NULL, 'С.Ган-Очир', '7111569', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1806', NULL),
  (NULL, 'С.Гэрэлтуяа', 'ХЖ74112404', 'both', NULL, NULL, 'Тауэр M1, Өрөө 901-902', NULL),
  (NULL, 'С.Наранцэцэг', 'ХО72012123', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1102', NULL),
  (NULL, 'С.Наранцэцэг/ХО72012123', '6971199', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1102', NULL),
  (NULL, 'С.Оюунгэрэл', '6234569', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1106', NULL),
  (NULL, 'САНДУЙЖАВ ХИШИГБАЯР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'САНЖААХҮҮ МӨНХБАЯР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'САРАН ХӨНДИЙ', NULL, 'both', NULL, NULL, NULL, NULL),
  ('C10004-03', 'СББ Трейд', '2702673', 'both', '88001876', 'Urangoo.m@apu.mn', 'Хан-Уул дүүргийн 2 дугаар хороо, Чингисийн өргөн чөлөө, АПУ ХК-ийн байр', '["АПУ СББ", "СББ Трейд ХХК"]'::jsonb),
  (NULL, 'СМАРТТРАК ДЕЛИВЕРИ', NULL, 'both', NULL, NULL, NULL, NULL),
  ('C10147-01', 'СОНОС', '7129561', 'both', '80977999', NULL, NULL, '["Сонос олон улсын хөгжмийн наадам ТББ"]'::jsonb),
  (NULL, 'СУВДАА БАТБААТАР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'СУГАРРАГЧАА НАМУУНАА', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'СУМАНЦАГААН АЗЗАЯА', NULL, 'both', NULL, NULL, NULL, NULL),
  ('C10211-01', 'Саммит Компьютер Технологи ХХК', NULL, 'both', NULL, NULL, NULL, '["Саммит Компьютер Технологи ХХК"]'::jsonb),
  (NULL, 'Саммит ХХК', NULL, 'customer', NULL, NULL, NULL, NULL),
  (NULL, 'Санс нью тоуч мэдикал ХХК', '8366144', 'customer', '80080166', NULL, 'Улаанбаатар хот', NULL),
  ('C10143-01', 'Сантранс Ложистик', NULL, 'both', NULL, NULL, NULL, '["Сантранс ложистикс ХХК"]'::jsonb),
  (NULL, 'Сантранс ложистикс ХХК', '6074405', 'customer', '90904433', NULL, 'ХУ дүүрэг, 3-р хороо, компорт плаза оффис 1102 тоот', NULL),
  (NULL, 'Сая мөнх ХХК', '6264417', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1406', NULL),
  (NULL, 'Свийт рөүд ХХК', '5156858', 'customer', '99908106', NULL, 'Улаанбаатар', NULL),
  (NULL, 'Силквэй Девелопмент', '6902421', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Силквэй хэйлт технологи ХХК', '6978266', 'customer', '89116888', NULL, 'Улаанбаатар, Баянзүрх, 26 хороо, их монгол хороолол, 305 байр 49 тоот', NULL),
  (NULL, 'Скаффолд Тарсс Эвэнт ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Смарт Жи Пи Эс ХХК', '6250343', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1105', NULL),
  (NULL, 'Солонго', 'УХ91070726', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1507', NULL),
  (NULL, 'Солонго капитал ББСБ', '3131475', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1207', NULL),
  (NULL, 'Солонго тамир ХХК', '5023904', 'both', NULL, NULL, 'Тауэр M3, Өрөө 404', NULL),
  (NULL, 'Солонго/УХ91070726', '5644925', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1507', NULL),
  (NULL, 'Сонофортегрупп ХХК', '5735262', 'customer', '99101521', NULL, 'Улаанбаатар, Сүхбаатар, 2-р хороо, 5 хороолол, сөүл, Эм Жи Жи Пропертис байр 3 давхар, 300А тоот', NULL),
  ('C10145-01', 'Соёолон Интернейшнл', '5644984', 'both', '99261122', NULL, 'Монгол, Улаанбаатар, Баянзүрх, 25-р хороо, манлайбаатар дамдинсүрэн, Ю-Би тауэр 83/2 1501 тоот', '["Соёолон ХХК", "Соёолон интернэшнл ХХК"]'::jsonb),
  ('C10148-01', 'Стандарт мах', NULL, 'both', NULL, NULL, NULL, '["Стандарт Мах"]'::jsonb),
  (NULL, 'Сувдан-Өргөө', '2666227', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Сэрүүн ХХК', '2020173', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1806-1807', NULL),
  (NULL, 'СҮХБААТАР БАТХҮҮ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'СҮХБААТАР ДҮҮРГИЙН НИЙГМИЙН ДААТГАЛЫН ГАЗАР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'СҮХБАТ БОДЬ', NULL, 'both', NULL, NULL, NULL, '["БОДЬ СҮХБАТ"]'::jsonb),
  ('C10149-01', 'Сүмбэр Жонш', '4614461', 'both', '99106244', NULL, NULL, '["Сүмбэр жонш ХХК"]'::jsonb),
  ('C10032-04', 'Сүү', '2077108', 'both', NULL, NULL, NULL, '["EB-СҮҮ ХК", "Сүү ХХК"]'::jsonb),
  (NULL, 'Т. Түмэнжаргал', 'ЧП85091109', 'both', NULL, NULL, 'Тауэр M1, Өрөө 807', NULL),
  (NULL, 'ТАЙВАНХҮҮ НАНДИНТҮШИГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ТАЛЫН ӨНГӨТ ДУСАЛ ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ТАМИР ШИНЭБАЯР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ТАШХАЙН ГОЛ ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ТДБ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ТОВУУДОРЖ ЧҮЛТЭМСҮРЭН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ТЭГШ ТПЛАНТ ХХК', NULL, 'customer', NULL, NULL, NULL, NULL),
  (NULL, 'ТЭНГЭС ЭРДЭНЭБАЯР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ТЭРГЭЛ ГАНЗАМ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ТЭРЭЛЖЖАРГАЛ', NULL, 'both', NULL, NULL, NULL, '["Тэрэлжжаргал"]'::jsonb),
  (NULL, 'ТЭЭГ ХАЙРХАН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Таван Богд Фүүдс Пицца ХХК', NULL, 'customer', NULL, NULL, NULL, NULL),
  (NULL, 'Таван Орд', '2635283', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1410', NULL),
  (NULL, 'Тайж Хурай Констракшн ХХК', '5811791', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Талын Адуу ХХК', '5525152', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1509', NULL),
  ('C10150-01', 'Тамаши Эссенс', '6862233', 'both', '80977999', NULL, NULL, '["Тамаши Эссенс ХХК"]'::jsonb),
  (NULL, 'Танзка Арт Дизайн ХХК', '5827876', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  ('C10151-01', 'Тера Экспресс', '5540836', 'both', '75770093', 'bayanmunkh@terraexpress.mn', 'Улаанбаатар, Сүхбаатар, 1-р хороо, Блю Скай 5-р давхарт 505 тоот', '["Тера экспресс ХХК", "ТЕРА-ЭКСПРЕСС ХХК", "Тера-Экспресс ХХК"]'::jsonb),
  (NULL, 'Техник Хаус ХХК', '5552648', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1105', NULL),
  (NULL, 'Техник өрөө', NULL, 'both', NULL, NULL, 'Тауэр M2, Өрөө 1301', NULL),
  (NULL, 'Ти Си Инженеринг ХХК', '6008623', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1604-1606', NULL),
  ('C10152-01', 'Ти Ти Жи Ви Си Өү', NULL, 'both', NULL, NULL, NULL, '["Ти Ти Жи Ви Си Өү ХХК"]'::jsonb),
  (NULL, 'Тогтсүх ОТГОНБААТАР', NULL, 'both', NULL, NULL, NULL, '["ОТГОНБААТАР ТОГТСҮХ"]'::jsonb),
  (NULL, 'Тод Бум ХХК', '5029635', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1505', NULL),
  (NULL, 'Тодгүн ТНН дрилинг', '8390673', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  ('C10153-01', 'Токи шоп', '8422168', 'both', '86117068', 'tergel-od.e@unitel.mn', NULL, '["Токи шоп ХХК"]'::jsonb),
  (NULL, 'Топ Ган Дриллинг ХХК', '6268048', 'customer', '99111848', NULL, 'Улаанбаатар  хот', NULL),
  (NULL, 'Топ кюзин ХХК', '6388272', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1204', NULL),
  (NULL, 'Торго', NULL, 'both', NULL, NULL, 'Тауэр M1, Өрөө 1801-1804', NULL),
  (NULL, 'Тотал шиппинг ХХК', '5273099', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1708', NULL),
  (NULL, 'Транс Хидроулик XXK', NULL, 'customer', NULL, NULL, NULL, NULL),
  (NULL, 'Тренд Мебель Монголиа ХХК', '5445825', 'both', NULL, NULL, 'Тауэр M3, Өрөө 307-309', NULL),
  ('C10156-01', 'Туушин', '2082675', 'both', '95953719', NULL, 'Туушин тауэр, Амарын гудамж-15, Улаанбаатар хот 14200-0048', '["Туушин ХХК", "ТУУШИН ХХК"]'::jsonb),
  ('C10158-01', 'Тэгш Плант', '5320259', 'both', NULL, NULL, NULL, '["Тэгш плант ХХК", "ТЭГШ ТПЛАНТ ХХК"]'::jsonb),
  (NULL, 'Тэргэл энд номуун хан хул', '7200369', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'ТҮВДЭННЯНДАГ СЭЛЭНГЭ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ТҮВШИНСАЙХАН ДЭЧИН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ТҮМЭНДЭМБЭРЭЛ МӨНХ-ОРГИЛ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ТҮМЭНДЭМБЭРЭЛ ТЭМҮҮЖИН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Түвдэн ТҮМЭНДЭМБЭРЭЛ', NULL, 'both', NULL, NULL, NULL, NULL),
  ('C10157-01', 'Түмэн Нинж', '5620104', 'both', '88067165', NULL, NULL, '["Түмэн нинж ХХК"]'::jsonb),
  ('T10001-1', 'Түмэн Ресурс', NULL, 'both', NULL, NULL, NULL, '["Түмэн Ресурс ХХК", "ТҮМЭН РЕСУРС ХХК"]'::jsonb),
  ('T10001-4', 'Түмэн Ресурс Менежмент', NULL, 'both', NULL, NULL, NULL, '["Түмэн Ресурс Менежмент"]'::jsonb),
  ('T10001-5', 'Түмэн Ресурс Технологи', NULL, 'both', NULL, NULL, NULL, '["Түмэн Ресурс Технологи"]'::jsonb),
  ('T10001-3', 'Түмэн Тээх Сити', NULL, 'both', NULL, NULL, NULL, '["Түмэн Тээх Сити"]'::jsonb),
  (NULL, 'Түмэн Тээх ХХК', '6906192', 'customer', '77751111 , 99044424', NULL, 'Улаанбаатар хот, Сүхбаатар дүүрэг 1-р хороо, Чингисийн өргөн чөлөө, Монгол тв таур 905 тоот', NULL),
  (NULL, 'Түмэндэмбэрэл ТЭМҮҮЛЭН', '820102373006', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'ТӨГС МӨНГӨН ТИТЭМ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ТӨГӨЛДӨР САРАНЧИМЭГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ТӨМӨРХУЯГ ГАНБАТ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ТӨРТОГТОХ ГАНСҮХ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Төв Азийн Зам', '5618819', 'customer', '95850717', NULL, 'Рокмон Оффис', NULL),
  (NULL, 'Төгс хамжлага ХХК', '8383502', 'customer', NULL, NULL, 'Улаанбаатар хот', NULL),
  (NULL, 'Төгсдэлгэр Дармаа', 'ИЦ75050563, АИ81101611', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1410', NULL),
  ('C10212-01', 'Төгөлдөр', NULL, 'both', NULL, NULL, NULL, '["Төгөлдөр"]'::jsonb),
  (NULL, 'Төгөлдөр Ундарга ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'У.Баярбат', 'УК99082305', 'both', NULL, NULL, 'Тауэр M1, Өрөө 510', NULL),
  ('C10159-01', 'УБ ОУДС', NULL, 'both', NULL, NULL, NULL, '["УБ ОУДСургууль"]'::jsonb),
  ('C10160-01', 'УБ Транс', NULL, 'both', NULL, NULL, NULL, '["УБ транс"]'::jsonb),
  (NULL, 'УЛАМБАЯР МӨНХ-ЭРДЭНЭ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'УРАНЗАЯА ЖАРГАЛСАЙХАН', NULL, 'both', NULL, NULL, NULL, '["ЖАРГАЛСАЙХАН УРАНЗАЯА"]'::jsonb),
  (NULL, 'УУГАНБААТАР ЦЭЛМЭН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Угалз гол ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Улаач Проперти ХХК', '6404138', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Улз Финанс ХХК', '6225705', 'both', NULL, NULL, 'Тауэр M2, Өрөө', NULL),
  (NULL, 'Улз гол ХХК', '2344343', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1801-1810', NULL),
  (NULL, 'Ундрам', 'ФМ86091641', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1604', NULL),
  (NULL, 'Ундрах сүүн далай ХХК', '5723116', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1201', NULL),
  (NULL, 'Универсал Авто комплекс ХХК', '2692643', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1705', NULL),
  (NULL, 'Уран Эния ХХК', '6071899', 'both', NULL, NULL, 'Тауэр M1, Өрөө 606-609', NULL),
  (NULL, 'Уран гар брэнд ХХК', '6113753', 'both', NULL, NULL, 'Тауэр M3, Өрөө 609', NULL),
  (NULL, 'Урангоо UA', 'ЧЕ86040506', 'both', NULL, NULL, 'Тауэр M2, Өрөө 903-904', NULL),
  (NULL, 'Уудам Говийн Гэрэл ХХК', '3613577', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1508', NULL),
  ('C10213-01', 'Уул Сорогшин', NULL, 'both', NULL, NULL, NULL, '["Уул сорогшин ХХК"]'::jsonb),
  (NULL, 'Ф.Цэнд-Аюуш', 'УБ85092501', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1205', NULL),
  (NULL, 'Фитнесс', NULL, 'both', NULL, NULL, 'Тауэр M2, Өрөө 1307', NULL),
  (NULL, 'Флексибле Ложистик', NULL, 'customer', NULL, NULL, 'Улаанбаатар хот', NULL),
  ('C10163-01', 'Флесибле Ложистик', NULL, 'both', NULL, NULL, NULL, '["Флексибле Ложистик"]'::jsonb),
  (NULL, 'Форте Майнинг Сапплай ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Х Солонго', 'ЧИ78050763', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1210', NULL),
  (NULL, 'Х.Амаржаргал', NULL, 'both', NULL, NULL, 'Тауэр M3, Өрөө 605', NULL),
  (NULL, 'Х.Батжаргал-Биг Боулинг', 'ХН74032479', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1708', NULL),
  (NULL, 'Х.Баянзул', 'ИЦ83081362', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1603', NULL),
  (NULL, 'Х.Билгүүн', 'УЗ97022311', 'both', NULL, NULL, 'Тауэр M1, Өрөө 801-802-810', NULL),
  (NULL, 'Х.Хашчулуун', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Х.Энхтайван', 'ИА75092537', 'both', NULL, NULL, 'Тауэр M3, Өрөө 804', NULL),
  (NULL, 'ХАВЧУУР БАТБААТАР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ХАЛТАРХҮҮ НАЙДАНХОРЛОО', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ХАНАН ЧУЛУУН ӨВ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ХИШИГТӨР МӨНХБАТ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ХОНГОР СЭРТЭНГИЙН ЭХ ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ХОНЬ ЧУЛУУЯ ГОЛ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ХУРАНДАА БАТБУЯН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Хаан Банк', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Хавцгайт Их Хайрхан ХХК', '5745098', 'both', NULL, NULL, 'Тауэр M2, Өрөө 908-909', NULL),
  (NULL, 'Хазон Вишн ХХК', '8399905', 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Хайтан Арвижих ХХК', '6353053', 'both', NULL, NULL, 'Тауэр M1, Өрөө 703-705', NULL),
  ('C10032-02', 'Хан Алтай Ресурс', '6413811', 'both', '88075628', 'Ganbat.sh@khanaltai.mn', 'УБ , Чингэлтэй дүүрэг , 5-р хороо, Самбуугийн гудамж, М-Плаза, 17-р давхар, 1701тоот', '["ХАН АЛТАЙ РЕСУРС ХХК", "Хан-алтай ресурс ХХК"]'::jsonb),
  (NULL, 'Хан шүтээн ХХК', '2623358', 'both', NULL, NULL, 'Тауэр M1, Өрөө 903-907', NULL),
  (NULL, 'Хангүгтрейд ХХК', '5468892', 'both', NULL, NULL, 'Тауэр M3, Өрөө 807', NULL),
  (NULL, 'Ханжин транс форвардер ХХК', '8388938', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1001', NULL),
  (NULL, 'Хатан зөгий транс ХХК', '5497396', 'both', NULL, NULL, 'Тауэр M3, Өрөө 606', NULL),
  (NULL, 'Хашхан ХХК', '2603756', 'both', NULL, NULL, 'Тауэр M3, Өрөө 301', NULL),
  (NULL, 'Хоум Скетч ХХК', '6013562', 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Хоёр Загал Жуулчин ХХК', '2586576', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1007', NULL),
  ('C10167-01', 'Хувь хүн', NULL, 'both', NULL, NULL, NULL, '["Хувь хүн"]'::jsonb),
  (NULL, 'Худалдаа хөгжлийн банк', '2635534', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Хужирт рашаан сувилал ХХК', '3551156', 'customer', '95028101', NULL, NULL, NULL),
  (NULL, 'Хун тайжийн өвөр ХХК', '6357253', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  ('C10169-01', 'Хурдан Загал Трейд', '6064205', 'both', '99096389', 'Bilgee0091@yahoo.com', NULL, '["Хурдан загал трейд ХХК"]'::jsonb),
  (NULL, 'Хэрмэл Угсаатан', '8435472', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1909', NULL),
  (NULL, 'Хэт Бат ХХК', NULL, 'both', NULL, NULL, 'Тауэр M3, Өрөө 502', NULL),
  ('C10214-01', 'Хятад компани', NULL, 'both', NULL, NULL, NULL, '["Хятад компани"]'::jsonb),
  (NULL, 'ХҮСЛЭН ПҮРЭВНЯМ', NULL, 'both', NULL, NULL, NULL, NULL),
  ('C10170-01', 'Хүслэн Юнайтед', NULL, 'both', NULL, NULL, NULL, '["Хүслэн Юнайтед XXК"]'::jsonb),
  (NULL, 'Хүслэн Юнайтед XXК', '6185398', 'customer', '99966530', NULL, 'Улаанбаатар хот', NULL),
  (NULL, 'Хүссэн зүг ХХК', '5127211', 'customer', '99102289', NULL, NULL, NULL),
  (NULL, 'ХӨЛӨГ ОВОО', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ХӨРС ПАКЕЖИНГ ХОРШОО', NULL, 'customer', NULL, NULL, NULL, NULL),
  (NULL, 'ХӨХЭНЭГЭ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ХӨХӨӨ ГАНЗОРИГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Хөвсгөл Их Тайга ХХК', '2673304', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1504-1505', NULL),
  (NULL, 'Хөгжил трейд ХХК', '2037319', 'customer', '86050259', NULL, 'ХУД 3-хороо Үйлдвэрийн гудамж 15д тоот', NULL),
  ('C10166-01', 'Хөрс', '8415595', 'both', '99159158', 'khurs.packaging.2023@gmail.com', 'Улаанбаатар хот Хан-Уул дүүрэг 17-хороо Их монгол, стадион оргил 128-196', '["Хөрс пакежинг хоршоо", "Хөрс ХХК"]'::jsonb),
  (NULL, 'Ц.Баясалжаргал', 'ЧС83120706', 'both', NULL, NULL, 'Тауэр M3, Өрөө 905', NULL),
  (NULL, 'Ц.Нарангуа', 'ЧС87090206', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Ц.Соёл-Эрдэнэ', 'ТБ79112366', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1103', NULL),
  (NULL, 'Ц.Энхжаргал', 'ХБ65010770', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1109', NULL),
  (NULL, 'Ц.Явуухулан', 'ВТ85102219', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1610', NULL),
  (NULL, 'ЦОГТОО ОТГОНБАТ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЦЭВЭЛМАА ДАМБИЙНЯМ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЦЭВЭЛРАВЖАА ДОРЖЗОВД', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЦЭВЭЭНЖАВ ПАГМА-ОРЛОМ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЦЭВЭЭНСҮРЭН ОРХОН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЦЭГМИД МӨНГӨНЗАГАС', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЦЭНГЭЛХҮҮ БАЯСГАЛАН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЦЭНД-АЮУШ БАТМӨНХ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЦЭРЭНБАЛТАВ БОЛД', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЦЭРЭНДАГВА ВАНЧИНДОРЖ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЦЭРЭНЧИМЭД МӨНХСҮЛД', NULL, 'both', NULL, NULL, NULL, NULL),
  ('C10172-01', 'Цагаан Өвөлжөө', NULL, 'both', NULL, NULL, NULL, '["Цагаан-Өвөлжөө ХХК"]'::jsonb),
  (NULL, 'Цагаан-Өвөлжөө ХХК', '5352827', 'customer', '99017861', NULL, 'Улаанбаатар, Сүхбаатар, 1-р хороо, нарны зам, 91, Санроуд барилга, 6 давхар', NULL),
  (NULL, 'Цасан цагаан өд ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Цахим мөнгөн соронз ХХК', '6050425', 'both', NULL, NULL, 'Тауэр M3, Өрөө 501', NULL),
  (NULL, 'Цилаажав Одгэрэл', 'АМ78040302', 'both', NULL, NULL, 'Тауэр M3, Өрөө 605', NULL),
  (NULL, 'Цогбаяр ЭНХМАНДАЛ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Цолмон', NULL, 'both', NULL, NULL, 'Тауэр M1, Өрөө 1606', NULL),
  (NULL, 'Цолмончимэг-г Н.Батцэцэг', 'ЦВ86050763', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1407', NULL),
  ('C10173-01', 'Цонх Констракшн', NULL, 'both', NULL, NULL, NULL, '["Цонх констрагшин ХХК"]'::jsonb),
  (NULL, 'Цэгц Хөрөнгө ББСБ', '5654513', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1104', NULL),
  ('C10032-06', 'Цэн газар ХХК', NULL, 'both', NULL, NULL, NULL, '["Цэн газар ХХК"]'::jsonb),
  ('C10176-01', 'Цэцэнс Майнинг', '5482046', 'both', '99034293', 'batkhuyag@tme.mn', 'Улаанбаатар хот, СБД 1-р хороо, Эмбасси Уан Бюлдинг 15давхар', '["Цэцэнс майнинг энд энержи ХХК", "ЦЭЦЭНС МАЙНИНГ ЭНД  ЭНЕРЖИ"]'::jsonb),
  (NULL, 'Цөм транс ХХК', '5397715', 'customer', '99114862', NULL, 'Улаанбаатар хот, СБД, 1-р хороо, олимпийн гудамж, 14-р байр 7 тоот', NULL),
  (NULL, 'Ч. Бямбадалай', 'ЧЙ72051318', 'both', NULL, NULL, 'Тауэр M3, Өрөө 809', NULL),
  (NULL, 'Ч.Дарханбаатар', 'АР75030115', 'both', NULL, NULL, 'Тауэр M3, Өрөө 906', NULL),
  (NULL, 'Ч.Сугармаа', 'ВЮ63020606', 'both', NULL, NULL, 'Тауэр M3, Өрөө 808', NULL),
  (NULL, 'Ч.Түмэнжаргал', 'РХ83092001', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1406', NULL),
  (NULL, 'ЧАНДМАНЬ ЦАГААН БОГЧ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЧИНЗОРИГ АМАРСАЙХАН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЧОЙДОРЖ ЭРДЭНЭХАНД', '111684610338', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'ЧУЛУУНБААТАР БОЛОР-ЭРДЭНЭ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЧУЛУУНБААТАР НЯМБААТАР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЧУЛУУНБААТАР ОТГОНБААТАР', '112590630304', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'ЧУЛУУНБААТАР ЭНХТӨР', '110709531955', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Чансаа хан хөхий холдинг ХХК', '5449545', 'both', NULL, NULL, 'Тауэр M3, Өрөө 702', NULL),
  (NULL, 'Чансаа хан хөхий холдинг ХХК/5449545', '6507611', 'both', NULL, NULL, 'Тауэр M3, Өрөө 702', NULL),
  (NULL, 'Чинзориг/ Вүүдмэн ХХК/2663252', 'ЧЗ84030313', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1701', NULL),
  (NULL, 'Чойжин темпл', '6112889', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Ш .Батсайхан', 'ВЭ85072216', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1601', NULL),
  (NULL, 'Ш.Амгаабазар', 'ЦГ70040502', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1605', NULL),
  (NULL, 'Ш.Дэлгэрмаа', '6835368', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1610', NULL),
  (NULL, 'Ш.Оюун', 'ЖЯ58022606', 'both', NULL, NULL, 'Тауэр M3, Өрөө 802', NULL),
  (NULL, 'Ш.Чимгээ', '7036281', 'both', NULL, NULL, 'Тауэр M3, Өрөө 508', NULL),
  (NULL, 'ШАГДАР БАТДАВАА', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ШАРХҮҮ ЭРДЭНЭДАВАА', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ШИЛДЭГ ФАСАД', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ШУНХЛАЙ КУГ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ШУНХЛАЙ ТРЕЙДИНГ ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Шар айраг хамтлаг ХХК', '6541577', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1010', NULL),
  (NULL, 'Шинжээравдан БАЯНМӨНХ', '408605338511', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Шинэст ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  ('C10199-01', 'Шинэцоггени', NULL, 'both', NULL, NULL, NULL, '["Д.Шинэцоггени"]'::jsonb),
  (NULL, 'Шунхлайпетролиум', '5512972', 'supplier', NULL, NULL, NULL, NULL),
  ('C10054-01', 'Шүүгээ', NULL, 'both', NULL, NULL, NULL, '["Shuugee LLC"]'::jsonb),
  (NULL, 'Э.Болор', '2018942', 'both', NULL, NULL, 'Тауэр M3, Өрөө 901', NULL),
  (NULL, 'Э.Булган', 'УЗ89072546', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1109', NULL),
  (NULL, 'Э.Золжаргал', 'ХГ67121900', 'both', NULL, NULL, 'Тауэр Parking, Өрөө P-003', NULL),
  (NULL, 'Э.Отгонцэцэг', 'АЮ75090125', 'both', NULL, NULL, 'Тауэр M1, Өрөө 605', NULL),
  (NULL, 'Э.Сайханцэцэг', 'ЧТ81102262', 'both', NULL, NULL, 'Тауэр M1, Өрөө 603', NULL),
  (NULL, 'Э.Солонго', '5968771', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1404', NULL),
  (NULL, 'Э.Энхбаяр', 'СВ85020615', 'both', NULL, NULL, 'Тауэр M3, Өрөө 504', NULL),
  (NULL, 'Э.Энхтөгөлдөр', 'ЙГ88090605', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1209', NULL),
  (NULL, 'ЭЙЯ ВИ СОЛЮШН ХХК', '6009875', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1106', NULL),
  (NULL, 'ЭМ ЭЛ ТАЛБАЙ ХХК', '6727808', 'customer', '80071250', NULL, 'Улаанбаатар  хот', NULL),
  (NULL, 'ЭМЖЖ  ХХК', '8329613', 'both', NULL, NULL, 'Тауэр M1, Өрөө 304-310', NULL),
  (NULL, 'ЭМЖЖ Эм ХХК', '5096502', 'both', NULL, NULL, 'Тауэр M1, Өрөө 303', NULL),
  (NULL, 'ЭМЖЖМед  ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  ('C10066-01', 'ЭНСИО', '5166829', 'both', '99170783', 'enkhmaa.s@premiumconcrete.mn', NULL, '["ЭНСИО"]'::jsonb),
  (NULL, 'ЭНХБААТАР АРИУНБАЯР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЭНХБАТ БҮТЭНБАЯР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЭНХБАЯР БАТСАЙХАН', '411607841314', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'ЭНХБАЯР ГАНБАЯР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЭНХЖАРГАЛ БАЯНЖАРГАЛ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЭНХТӨР ДОРЖСҮРЭН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЭНХТӨР ҮРЖИНБАТ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЭНЭРЭЛБУЯН НАРАН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЭРДЭНЭБААТАР ЖАВХЛАНТӨГС', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЭРДЭНЭХУЯГ БОРХҮҮ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Эй Эй Эй Энд Эс ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Эй Эн Өү Дизайн ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Эйч Эл Кэй Эм Эн ХХК', '5883474', 'customer', '99133548', NULL, 'Улаанбаатар хот', NULL),
  (NULL, 'Экстрем Эссэнс ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Элма хужирт ХХК', '2681013', 'customer', '95028101', NULL, NULL, NULL),
  (NULL, 'Эм Ай Эй ХХК', '5545897', 'customer', NULL, NULL, 'Улаанбаатар, Баянзүрх дүүрэг, 2-р хороо, 1а хэсэг цэргийн хотхон 1, 121.', NULL),
  (NULL, 'Эм Жи Ай Эм ХХК', '5069653', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1910', NULL),
  (NULL, 'Эм Ти Ди панда', '7078801', 'supplier', NULL, NULL, NULL, NULL),
  (NULL, 'Эм Эл Жи Финанс Гинко', '6480276', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1606-1607', NULL),
  (NULL, 'Эм Эл Жи Финанс Юү Би ББСБ', '2677385', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1608-1609', NULL),
  (NULL, 'Энгүй ундрага ХХК', '5280141', 'customer', '88007459', NULL, NULL, NULL),
  ('C10181-01', 'Энсада Трактрон', '4255801', 'both', '88885419', NULL, NULL, '["Энсада Трактрон ХХК"]'::jsonb),
  (NULL, 'Энто Фарм ХХК', '6590233', 'both', NULL, NULL, 'Тауэр M1, Өрөө 507-508', NULL),
  (NULL, 'Энх хүдэр эрдэнэс ХХК', '6580912', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1410', NULL),
  ('C10182-01', 'Эпирок Монголиа', '5004853', 'both', '99108508', NULL, NULL, '["Эпирок Монголиа ХХК"]'::jsonb),
  (NULL, 'Эра жимс ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Эра жимс ХХК/6381278', '5694744', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1405', NULL),
  (NULL, 'Эрдэнэ Мебель ХХК', 'УП99020355', 'both', NULL, NULL, 'Тауэр M3, Өрөө 302-306', NULL),
  ('C10075-01', 'Эрдэнэс Цагаан Суварга', '5824826', 'both', '99138524', 'munkhzul.m@mak.mn', NULL, '["Эрдэнэс Цагаан Суварга ХХК"]'::jsonb),
  (NULL, 'Эрдэнэчулуун', 'ФМ83012455', 'both', NULL, NULL, 'Тауэр M2, Өрөө 804', NULL),
  (NULL, 'Эрхэл Тэлмэн ХХК', 'РЭ90110623', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1409', NULL),
  (NULL, 'Эрхэт Тэгри Хүү Консалтинг ХХК', '8370923', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1509', NULL),
  (NULL, 'Эс жи прайм блюд ХХК', '7077177', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'ЮУ ЭЛ ЭКЮПМЕНТ КО ХХК', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЮУ ЭМ ЭС ХХК', NULL, 'customer', NULL, NULL, NULL, NULL),
  (NULL, 'Юнайтед Интернэйшнл Коммерс ХХК', '6058515', 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  ('C10083-01', 'Юнайтед Шиппинг', NULL, 'both', NULL, NULL, NULL, '["Юнайтед Шиппинг ХХК"]'::jsonb),
  (NULL, 'Юник спаркли ХХК', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  ('C10078-01', 'Юнисервис Солюшн', '2878593', 'both', '88086606', 'baigalmaa.e@uss.mn', 'Улаанбаатар хот Сүхбаатар дүүргийн 8- хороо, Сүхбаатарын талбай-2, Сентрал тауэр 910-911 тоот', '["Юнисервис Солюшн ХХК", "ЮНИСЕРВИС СОЛЮШН ХХК"]'::jsonb),
  (NULL, 'Юнитра ХХК', '2695316', 'both', NULL, NULL, 'Тауэр M3, Өрөө 708-709', NULL),
  ('C10164-01', 'Юрика', '6846548', 'both', '95030405', 'enerelbuyan@ureca.com', NULL, '["ЮРИКА ХХК", "Юрика ХХК"]'::jsonb),
  (NULL, 'ЮҮ ЖИ ЭС ЭС ХХК', '3627241', 'customer', '94006188', NULL, 'Хаяг : Хан-уул дүүрэг, Чингисийн гудамж, ТВ5 оффис #900', NULL),
  (NULL, 'Я.Хонгорзул', 'УК96043006', 'both', NULL, NULL, 'Тауэр M3, Өрөө 1202', NULL),
  (NULL, 'ЯАХҮҮ ДАГВАДОРЖ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЯГААН АРИУНЖАРГАЛ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ЯГААНБАНДИ БАТТОГТОХ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Ү.Бадамсүрэн', NULL, 'both', NULL, NULL, 'Тауэр , Өрөө', NULL),
  (NULL, 'Үндсэн-Орд', '2659107', 'supplier', NULL, NULL, NULL, NULL),
  ('C10162-01', 'Үүрэг Тек', '5190207', 'both', '88617745', 'nomon@uureg.mn', NULL, '["Үүрэг тек ХХК"]'::jsonb),
  (NULL, 'Ө.Атарцэцэг', 'ШЖ87082560', 'both', NULL, NULL, 'Тауэр M1, Өрөө 1702', NULL),
  (NULL, 'ӨВӨРТИЙН ХУРД ЗАМ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ӨГИЙДАЛАЙ МИНЖИНСОР', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ӨЛЗИЙХУТАГ ЖАМЪЯНЧОЙЖИЛ', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ӨНӨРСАЙХАН ЭНХТАЙВАН', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'ӨСӨХБАЯР УРАНГОО', NULL, 'both', NULL, NULL, NULL, NULL),
  (NULL, 'Өвөр Гэгээ Транс ХХК', '3637549', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1610', NULL),
  (NULL, 'Өлзийт голын ус ХХК', '6185797', 'customer', '99034553', NULL, NULL, NULL),
  (NULL, 'Өнөрбаян хайрхан ХХК', '6060854', 'both', NULL, NULL, 'Тауэр M2, Өрөө 1209', NULL);

END IF;
END $$;
